### ISSUE TITLE
Adding Preview9.0 compatibility

### ISSUE THREAD

**Issue by Baldhal** [cormiertyshawn895/Retroactive#1]
Preview9.0 (https://github.com/frhd/macOS-Preview9.0) doesn’t work anymore in Catalina (crash at opening any pdf but succeeds with other formats)
So, I’ve tried to put the Mojave version of PDFkit in Preview9.0 with install_name_tool but it still crashes at opening of any pdf file.
I’m not sure if Preview9.0 call call an other version of PDFKit.

**Comment by cormiertyshawn895** [comment]
Opened a pull request to make Preview 9.0 compatible with macOS Catalina (10.15).
https://github.com/frhd/macOS-Preview9.0/pull/3

You can also [download Preview 9.0 for macOS Catalina here](https://github.com/cormiertyshawn895/macOS-Preview9.0/archive/master.zip). You need to right click to open Preview.
