### ISSUE TITLE
Photo Stream and Photo Sharing - not working

### ISSUE THREAD

**Issue by sghild** [cormiertyshawn895/Retroactive#10]
Photo stream and photo sharing appear not to be working. Aperture complains "... you must be signed into your iCloud account." for it to work, even though I am signed in to iCloud. 

Thx

**Comment by cormiertyshawn895** [comment]
That's a known limitation at the moment. Fixing iCloud Photo Stream and iCloud Photo Sharing in Aperture is fairly involved, and requires #41 to be fixed first.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
