### ISSUE TITLE
Logic Pro 9 Graphics Glitch When Not in Full Screen

### ISSUE THREAD

**Issue by cmrnclrk** [cormiertyshawn895/Retroactive#101]
[
![Screen Shot 2020-06-19 at 3 31 44 PM](https://user-images.githubusercontent.com/61756879/85173916-4eed9480-b242-11ea-8797-69ebf5539a5d.png)
](url)
I am using Logic pro 9 on Mojave and a 2017 MacBook pro with Intel Iris Graphics. The arrange view glitches when using logic pro 9 not in full-screen mode. It works fine in full screen, however. 
Thank you so much for this App by the way!!! Happy to be using logic 9 once again.

**Comment by svetetikhiy** [comment]
Exactly same issue here on High Sierra.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
