### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by Andres-Brito** [cormiertyshawn895/Retroactive#102]
Dear friends:

I'm concern about Big Sur aka macOS XI. Will Retroactive be updated to keep on working with this new operating system?

**Comment by cormiertyshawn895** [comment]
Thank you for asking!

Today's [minor release (Version 7, Build 67)](https://github.com/cormiertyshawn895/Retroactive/releases/tag/1.7) added limited experimental support for unlocking Aperture and installing iTunes on macOS Big Sur Beta 1.

With limited support, Aperture can now launch, and is mostly functional on macOS Big Sur Beta 1. There are many graphical glitches, missing toolbar icons, and occasional crashes. iTunes 12.9.5 is fully functional with a few graphical glitches.

As time goes on and as macOS Big Sur develops, I will try my best to improve support for macOS Big Sur.

**Comment by Andres-Brito** [comment]
You are absolutely the best! Thank you very much indeed for your effort.
