### ISSUE TITLE
Aperture give "item #" for print sizes

### ISSUE THREAD

**Issue by vbsoto** [cormiertyshawn895/Retroactive#104]
Hi, Love the fact I can continue to use Aperture, but I'm experiencing problems when printing.  Each of my two epson printers, when attempting to print thru aperture only display paper sizes as "item 1", "item 2" and "item 3" each at 8.5 x 11.  There is no provision to modify or create new sizes.  It should display all sizes supported by the drivers.

Is this something that can be rectified?  Printing thru aperture is part of my normal workflow with it.

Thanks for your great service.

Victor

**Comment by AGILBERT01** [comment]
I have the same issue as well. Can this be fixed so that I can print directly from Aperture 3 with full print features as before?

**Comment by sad144** [comment]
This is happening to me also, along with random crashes as I scroll photos and waiting for thumbnails to populate in the viewer.

MP, Late 2019
3.3GHz, 12-Core Intel Xeon W
96GB of Ram
Radeon Pro Vega II, 32GB HBM2
1TB SSD
Referenced files store on 2700MB/s Promise Pegasus 2 RAID

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
