### ISSUE TITLE
Are iTunes.app and Music.app using the same libraries? 

### ISSUE THREAD

**Issue by mattpopovich** [cormiertyshawn895/Retroactive#105]
First, thanks for all your development to get this working. 

I just installed and wanted to see if changes I made in one app were viewable in the other app. Ex. I rated a song 4 stars in Music.app but did not see that change reflected in iTunes.app. I did the same in iTunes: rated the same song as 1 star and did not see that change reflected in the Music.app. 

Is this expected behavior? Are they using different libraries (.itl and .xml files in ~/Music/iTunes)?

**Comment by cormiertyshawn895** [comment]
Yes, this is expected. iTunes and Music use different libraries.

**Comment by mattpopovich** [comment]
Thanks, appreciate the quick response!
