### ISSUE TITLE
App Request: Cinema Tools

### ISSUE THREAD

**Issue by svizor** [cormiertyshawn895/Retroactive#106]
The Final Cut Pro 7 itself is not enough to exchange metadata. The Cinema Tools is critical.
Please add support for Cinema Tools 4.5.1.
UPD: After changing the CFBundleIdentifier Cinema Tools starts and seems to work, but The Final Cut Pro 7 cannot communicate with the Cinema Tools and reports: "Locating Cinema Tools", "Failed to launch the Cinema Tools application". Maybe in the The Final Cut Pro 7 it is possible to change the data about CFBundleIdentifier for Cinema Tools?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
