### ISSUE TITLE
How do you sync your iPhoto/Aperture/Photos library in iTunes 12.6.5.3?

### ISSUE THREAD

**Issue by pizzaonmychest** [cormiertyshawn895/Retroactive#107]
Hi! Love the software you created to get these running again. I was just wondering how you can get iTunes (12.6.5.3) to sync photos from Photos/iPhoto/Aperture libraries instead of finding pics in the pictures folder. Thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
