### ISSUE TITLE
Retroactive 1.8  over 1.7

### ISSUE THREAD

**Issue by oakhampton** [cormiertyshawn895/Retroactive#109]
Hi, I'm thrilled and full of admiration for Tyshawn Cormier that Retroactive 1.7 enabled me to use Mac Aperture in MacOS 10.15 Catalina.

Now Retroactive 1.8 is here, can I run Retroactive 1.8 on top of 1.7: ie can I apply the 1.8 version to the modified version of Aperture?  Or do I need to delete the modified Aperture, download the original version from the App store and apply 1.8 to that? And, is there any point in doing this?

I ask partly because Retroactive seems to be actively being developed (Big Sur is mentioned) and future versions of Retroactive may be needed to enable Aperture (and others) to run.

Thanks for your great service to Mac users
Roger

**Comment by cormiertyshawn895** [comment]
Yes, you can safely run Retroactive 1.8 on top of Retroactive 1.7. There's no need to delete the modified Aperture and re-download it from the Mac App Store.
