### ISSUE TITLE
Music won't play in iTunes when double clicked. (iTunes is set as default)

### ISSUE THREAD

**Issue by crowdcontrolol** [cormiertyshawn895/Retroactive#111]
I have a bug on my new machine with Retroactive iTunes 12.9.5.

The only way for me to import new music into iTunes is to open it when iTunes is closed, or if I physically drag and drop the file. Double clicking doesn't work when iTunes is currently running. And iTunes is set as the default program for music files.

If iTunes is open, and I try to open a new .mp3 file from my web browser, finder, or anywhere outside the iTunes library, it will attempt to open in a clone iTunes window for about 1 second, then that new window closes, and nothing happens with the file.

It's even worse when trying to import .aiff or .wav files when iTunes is open. The same duplicate iTunes window occures, but it gets stuck indefinitely bouncing up and down on my bar (loading). Force quit doesn't even work to get rid of it. And the bouncing icon really gets stuck. The only way to get it off is to force restart my computer.

I can avoid the issue by dragging and dropping into the working iTunes window. But why can't I double click new files to open them when iTunes is open? It only works on the initial click (if iTunes is not yet open). 

Frustrating because files opened perfectly from Retroactive iTunes on my 2017 Macbook Pro but now I have a 2019 16" model and its giving me this bug.

What can I do about this?

**Comment by Tonym69** [comment]
Bumping this question up as same issue. Running iTunes 12.9.5 on Big Sur, Retroactive 2.0

Double-clicking mp3 file only opens in iTunes when iTunes is closed first. If iTunes is open, it creates a duplicate iTunes dock icon but doesn't open or add the track.

Any suggested solutions for this please?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
