### ISSUE TITLE
Soundtrack Pro 3.01

### ISSUE THREAD

**Issue by pcode59** [cormiertyshawn895/Retroactive#112]
Hi I still cannot open Soundtrack Pro with Logic Po 9 - have I missed a step fixing Logic ?

My hopes are slightly dashed :(

**Comment by princeofsky** [comment]
Yeah, if only Soundtrack Pro could work :(

**Comment by adamschoales** [comment]
I too would love to see Soundtrack Pro resurrected.

**Comment by Denial-Steinberg** [comment]
I too would love to see Soundtrack Pro resurrected.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
