### ISSUE TITLE
Can view iPhone in iTunes but can't copy songs to it

### ISSUE THREAD

**Issue by Neucleus** [cormiertyshawn895/Retroactive#113]
Catalina 10.15.5
iTunes 12.9.5.5
Retroactive 1.8
Message: This iPhone is in use by another user on this Mac
I know this has been discussed a lot in this forum, but I think I've tried everything. My iPod works in iTunes just fine. When I connect my iPhone XS, I get this message. I can see my iPhone in iTunes and I can view all the playlists and songs, but I can't drag/drop any songs in to it from iTunes. Could be related to issue #11  

What I've tried:

Reinstalled iTunes 1.8
Enabled full disk access for iTunes and for the BASH script during Retro/iTunes install. Confirmed settings saved
Finder / Preferences > Locations : CDs, DVD, and iOS Devices (checked)
Restarted Mac
Open iTunes. Ran killall AMPDevicesAgent from Terminal. Plugged in iPhone
iPhone isn't showing in Finder. Shows in iTunes as view only. I can't add any songs to it

Update: July 25, 2020
- Installed OS update to Catalina 10.15.6
- Reinstalled iTunes 12.9.5.5
- Ensured Full Dis Access still correct
- Ran killall AMPDevicesAgent from Terminal
Still same issue :(

**Comment by Neucleus** [comment]
I'm still stuck on this. Is anyone able to help?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
