### ISSUE TITLE
iWork odd app behaviours/crashes

### ISSUE THREAD

**Issue by badawat** [cormiertyshawn895/Retroactive#114]
Hi Tyshawn,
Thanks so much for your amazing app.

Worked like a dream for fresh install of iWork as well as existing install from of FCP 3 from Sierra upgrade to Mojave. However:

Pages 4.3: when I create a new document any text input is interpreted as Enter/Return. The cursor just moves to the next line. Some templates wont open at all and just crash.

Keynote 5.3 crashes on opening. If I Reopen and choose a template is crashes immediately too. 

Numbers 2.3: when typing into the cells keystrokes are interpreted as Enter but if you click off the cell and the typed information is displayed correctly. Sums seem to function as intended. 

I'm happy to supply crash reports if useful. I'm running 10.14.6

FCP7 seems to be working fine, I've not given it a full test drive yet. This is the most exciting thing for me in quite some time!
Do you have any plans for the rest of the FCP3 suit such as Soundtrack, DVD Studio Pro and Cinema Tools?

Best and thanks again for your fine efforts!

**Comment by TheOnlineUser** [comment]
@badawat did you ever get it fixed? I am on 10.14.6 and use iWork on the daily. Never have any issues, particularly with Pages. Maybe try doing a fresh install of iWork? I have always installed the base installer and then immediately run the 4.3 upgrade package and then run Retroactive.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
