### ISSUE TITLE
Tethering a camera in Aperture

### ISSUE THREAD

**Issue by angrenez** [cormiertyshawn895/Retroactive#118]
The tethering a camera can be still started and the control the camera shot is still working. But the pictures will be not transferred to Aperture and get lost.

Thank you for your support!

**Comment by CharlesTam20** [comment]
Unfortunately, this issue still exists in v1.9 
My work around is to use Image Capture v8 on Big Sur

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
