### ISSUE TITLE
Aperture MacOS 10.15.6

### ISSUE THREAD

**Issue by angrenez** [cormiertyshawn895/Retroactive#119]
Unlocking Aperture in MacOS 10.15.6 with Retroactive 1.8 did not work. Using an unlocked Aperture copy (unlocked with 1.8 in MacOS 10.15.5) is working fine.

**Comment by cormiertyshawn895** [comment]
Can you please attach a screenshot of what you're seeing? Is it a crossed out Aperture icon, or does Aperture crash?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
