### ISSUE TITLE
No brushes in Aperture

### ISSUE THREAD

**Issue by JonGusson** [cormiertyshawn895/Retroactive#12]
After Retroactive my Aperture is doesn't have all the same brushes as before. I can no longer add adjustments or use brushes (skin smoothing, dodge etc.) All I get is "Retouch". I can add adjustments be copying them from another photo and stamp then on to the photo I'm working on but I can not add them from scratch.

**Comment by cormiertyshawn895** [comment]
Can you see the option to "Add Adjustment"? What does Aperture show here on your Mac?

<img width="506" alt="Screen Shot 2019-11-01 at 9 10 19 PM" src="https://user-images.githubusercontent.com/57056759/68065831-0487c980-fcec-11e9-9df9-87e286242bc1.png">

**Comment by JonGusson** [comment]
I appreciate your work a lot. Thank you! Nothing under Quick Brushes at all. No Adjustments can be added. I got the same result on two Macs.

![Screen Shot 2019-11-02 at 12 33 41 PM](https://user-images.githubusercontent.com/57267988/68070978-35f4a980-fd6d-11e9-90dc-f5bb299f81c8.jpg)

**Comment by cormiertyshawn895** [comment]
As I look at why this is happening, can you try the following workaround?

1. Quit Aperture.
1. Open Terminal, and paste in this command:
`open /Applications/Aperture.app/Contents/MacOS/Aperture`
1. Press `return` on your keyboard.
1. Try to add an adjustment to the photo.

**Comment by JonGusson** [comment]
I just tried this and it works. All the brushes and adjustment options are back. As soon as I quit Terminal Aperture shuts down. When I open Aperture without the Terminal command the brushes are not there.

**Comment by cormiertyshawn895** [comment]
Please [download and launch Retroactive 1.2](https://github.com/cormiertyshawn895/Retroactive/releases/download/1.2/Retroactive.1.2.zip), then choose to modify Aperture again. Brushes and adjustments should be available after re-modifying Aperture with Retroactive 1.2. If you still can't use brushes or add adjustments, please leave a comment and re-open the issue.

Retroactive 1.2 contains bug fixes and additional enhancements:
- Restores the ability to add adjustments and use Quick Brushes in Aperture
- Restores the ability to print photos in Aperture and iPhoto
- Resolves an issue where Aperture and iPhoto may fail to launch (Error 13)
- Adds support for modifying Aperture and iPhoto to be compatible with macOS Catalina before upgrading to macOS Catalina
