### ISSUE TITLE
iPhoto crashes on updating library

### ISSUE THREAD

**Issue by DmitryZ111** [cormiertyshawn895/Retroactive#120]
Hi!
First - excellent app, your work is wonderful! It was a pain that I could not access my old media libraries in iPhoto.
But! I faced a problem: I open a library, from the very start it says that I need to update it for the current version of iPhoto. Options are OK or quit. Quit shuts the app, OK shows progress bar for a second and then the app crashes. 
Would be grateful if you could fix it.

Catalina 10.15.3
iPhoto 9.6.1
MBP16

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
