### ISSUE TITLE
Aperture Support?

### ISSUE THREAD

**Issue by BobShawAU** [cormiertyshawn895/Retroactive#121]
Hi, 
I have tried Aperture in Catalina using RetroActive and this is fabulous news. Not an issue but I can't find anywhere else to post.

Have you considered getting a licence from Apple to market and support Aperture? There are a lot of users like me who need a solid professional database for photography and continue to use Aperture. Capture One does not support all cameras and Lightroom has a poor interface by comparison.

From Apple's perspective this should be a good thing, as it is a Mac only product.

Bob

**Comment by cormiertyshawn895** [comment]
Thank you for supporting Retroactive. ❤️

As you've mentioned, Capture One and Lightroom are also great alternatives for managing photos. With that said, I try my best to keep Aperture running on the latest version of macOS.

**Comment by BobShawAU** [comment]
Thanks for your response Tyshawn.

Unfortunately Capture One is useless to me as it doesn’t support all cameras, notably the best one, being Hasselblad.

Lightroom has a clunky interface compared to Aperture and uses ACR and not the operating system. 
It does not have some of the basic features of Aperture like X and Y co-ordinates on a crop that I need for consistent product photography.

If you were selling Aperture there would be a lot of buyers.

A  couple of years ago Apple blocked the use of newer cameras like the Canon M5 on Aperture by changing the way raw files are read.
Perhaps that is something that could be looked at.

Anyway, thanks for what you have done. It is amazing.

Regards,

Bob Shaw
Bob@AspirationImages.com
http://AspirationImages.com
0417 781 490
	

Like on Facebook
http://www.facebook.com/aspirationimages

Instagram aspirationimages









On 15 Nov 2020, at 8:43 pm, Tyshawn Cormier <notifications@github.com> wrote:


Thank you for supporting Retroactive. ❤️

As you've mentioned, Capture One and Lightroom are also great alternatives for managing photos. With that said, I try my best to keep Aperture running on the latest version of macOS.
