### ISSUE TITLE
Documentation about what doesn’t work in Xcode?

### ISSUE THREAD

**Issue by fancyham** [cormiertyshawn895/Retroactive#125]
Am very interested in using the latest Xcode in Mojave!  But can someone please write up something about what doesn’t work so that I can make an informed decision before trying it?

**Comment by cormiertyshawn895** [comment]
Everything works except Reality Composer and FileMerge.

**Comment by fancyham** [comment]
Thank you!

**Comment by kct3937** [comment]
Just unlocked and installed Xcode 11.7 on Mojave.  Thank you.  However the display seems to that of 11.3 while the Main page says it's 11.7.  I wanted to use the interactive editing in 11.7 but it doesn't show.  Do I need to do something else?

**Comment by fancyham** [comment]
Interactive SwiftUI layout editing doesn't work In Mojave (swiftUI is only part of Catalina would be my guess). 

The 'unlocked' Xcode 11.7 displays "SwiftUI Preview require macOS 11.15 or later" in the SwiftUI preview pane.
![Screen Shot 2020-09-17 at 12 46 37 PM](https://user-images.githubusercontent.com/3376957/93536125-119daf00-f8e4-11ea-8a90-b811c7f620e6.png)

**Comment by kct3937** [comment]
Thank you for your input. Did you read the reply to your first question in this thread? The point of Retroactive is to get the an app to work with the specified OS version...in this case XCode 11.7 with Mojave (OSX 10.14.6).  Shawn seems to indicate that it should with the exceptions he has noted.

**Comment by fancyham** [comment]
It's not an exception — XCode always required Catalina for SwiftUI preview, even in Xcode 11.3, which was still Mojave compatible.

Unfortunately, what you're looking for is added new functionality, not unlocking existing stuff.
