### ISSUE TITLE
Final Cut Pro 7 and DVD studio Pro 4.2.2 and Compressor 3.5

### ISSUE THREAD

**Issue by lf111** [cormiertyshawn895/Retroactive#126]
Hello
Everything works fine with Final cut pro 7 on High Sierra and Mojave.
But could you have the possibility to do the same with others app from Final cut studio ?
I mean DVD studio Pro 4.2.2 and Compressor 3.5 ?
Because this process remain the best for encode and authoring DVDs...
If Yes, thanks a lot !!!
LF

**Comment by mirozahorak** [comment]
DVD studio Pro would be great

**Comment by adamschoales** [comment]
For me it's Soundtrack Pro that I miss the most. It's still my favourite app for multitrack audio editing.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
