### ISSUE TITLE
Aperture: Full screen display bug

### ISSUE THREAD

**Issue by oakhampton** [cormiertyshawn895/Retroactive#127]
Hi,
Thank you for your continuing work on keeping Aperture alive - and kicking!
There is one bug I have found with full screen viewing of image(s): Key board 'F' switches to full screen; 'F' should revert to view in a window, but causes Aperture to crash and close.
Pressing Esc will revert full screen to windowed display, so all is not lost, but I still try to use the original keystroke, to my annoyance!
Please can this be fixed?
Roger

**Comment by themantripleman** [comment]
I'm having the same bug. Good to know that the escape key is an alternative for now but a real fix would be better. Hoping one is possible and not a nightmare to figure out. I have a crash log if you need it. 

I also thank you for your work on Retroactive. This is a huge deal for me. I have a lot of libraries with thousands of photos and to find a suitable Aperture alternative (no, not you Lightroom, it'll never be you) and migrate is a nightmare that I've been avoiding. 

Coincidentally, my name is also 

Roger

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
