### ISSUE TITLE
Xcode 12 support

### ISSUE THREAD

**Issue by AnthoPakPak** [cormiertyshawn895/Retroactive#128]
Hey!

First of all, thanks a lot for this tool, which allowed me to keep using a stable system while still being able to use Xcode newest versions!
I'm pretty sure you're aware of Xcode 12 GM being released a few days ago. I didn't found any information about it on the repo or in issues. So I wanted to ask, do you think Xcode 12 could be supported or it would be too much broken?

Thanks in advance ✌️

**Comment by Gcenx** [comment]
I’m also hoping it’ll be possible to use Xcode12 on Mojave

**Comment by nimrodbens** [comment]
@Gcenx i never want to part ways with mojave. i use the dashboard constantly and i don't want an OS that feels like a kid's toy.

**Comment by Mac-Man-APH** [comment]
Hi

I am also very grateful for the app and appreciate the hard work that goes into producing such a useful tool but an idea if Xcode 12 will have the same treatment and allow us to unlock it in Mojave.

**Comment by cormiertyshawn895** [comment]
Xcode 12 requires the Combine framework, which isn't available in macOS Mojave. It will be quite challenging to unlock Xcode 12 on macOS Mojave.

**Comment by AnthoPakPak** [comment]
Yeah that's what I understood too, guess I'll finally have to update my MBP to Big Sur…
Anyway, thanks for your answer and continuous support up to Xcode 11.7! ✌️

**Comment by WowbaggersLiquidLunch** [comment]
Given that Catalina has Combine, could Xcode 12.5 and later minor versions be unlocked for Catalina?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
