### ISSUE TITLE
FileMerge and Create ML apps from Xcode 11.7 suite are still locked

### ISSUE THREAD

**Issue by dandee** [cormiertyshawn895/Retroactive#129]
As title says: Xcode can be successfully unlocked but additional apps from the Xcode suite are still locked up.

<img width="616" alt="Screenshot 2020-09-24 at 21 06 11" src="https://user-images.githubusercontent.com/890495/94188691-489e3280-fe99-11ea-859c-17fdb3156d11.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
