### ISSUE TITLE
Zterm

### ISSUE THREAD

**Issue by TheReiner** [cormiertyshawn895/Retroactive#13]
Hi,

Did you think is possible to build for this app ?

https://www.dalverson.com/zterm/

Thanks and great job :)

**Comment by cormiertyshawn895** [comment]
ZTerm is 32-bit only, so it won't work with Retroactive. However, you can [set up a virtual machine to run macOS Mojave under macOS Catalina](https://kb.parallels.com/124786), then run ZTerm in that virtual machine.
