### ISSUE TITLE
OS Catalina conversion and migration of Aperture 3 issue with email and printing

### ISSUE THREAD

**Issue by AGILBERT01** [cormiertyshawn895/Retroactive#131]
I have successfully upgraded to OS Catalina, dowloaded the retroactive application V1.9 and successfully restored my Aperture 3 with my entire library. I have two issues still remaining. 1. I am unable to generate an email when I select a photo(s). It indicates "processing" but does not generate "Mail" as before. 

2. When I select print, I do not get a paper size selection but only have options "item 1, item 2, item 3". Is there a fix or shortcut to address these issues?

Thank you in advance

Andrew

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
