### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by Razormaid** [cormiertyshawn895/Retroactive#133]
Hi Tyshawn.  I'm Joseph Watt, producer and owner of Razormaid Productions, a dance remix and post production company since 1984.  We exclusively use Wave Editor, which I helped develop with Evan Alcott and Mathew Faust in Minneapolis, back in 2003.  In 2015 the company disbanded and Ev continued on his own.  

Although I am still friends with Ev, he wrote a different software to replace Wave Editor (Triumph) but it didn't have the fluidity of WE.  Because it's stuck in 32Bit forever, I was wondering if you might be able to assist us in getting it to work in Catalina?  

When I contacted Ev and Matthew to see if Razormaid could simply buy Wave Editor, I was told, "We abandoned it.  Actually, we never bothered to registered it or copyrighted it. We moved on to Triumph and just abandoned it.  You're free to do whatever you want, we just don't have an interest in it any longer (since 2009)".  

Ev said he can write a new Wave Editor II for us, but besides payment for his services, its going to take some time (according to Ev).

Is there any way you could look at it and see if your creative genius could help us get it running in Catalina?  We have full access to the code, but we know nothing about code or if it is even possible.  We installed it in Mojave via Parallels, but like all music running emulated, it jumpy and not really smooth enough for 14 hours a day use.  Occasional corrections?  Sure, but we need a more stable approach.

HELP!
Joseph
razrmaid@aol.com 
http://www.razormaid.com/index2.htm

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
