### ISSUE TITLE
Retroactive -- Aperture: Inspector> Adjustments is blank

### ISSUE THREAD

**Issue by mlinla** [cormiertyshawn895/Retroactive#134]
Hi Tyshawn,
Hope you are well.
Need your help please.
When in Aperture that was unlocked on Catalina using MBP mid-2015 I can see first two tabs of Inspector (Library and Info
<img width="387" alt="Screen Shot 2020-10-06 at 9 53 02 PM" src="https://user-images.githubusercontent.com/72484897/95288962-86e30c80-081e-11eb-948d-ec3a0a4172bc.png">
) but not the third one - Adjustments. 
<img width="384" alt="Screen Shot 2020-10-06 at 9 53 12 PM" src="https://user-images.githubusercontent.com/72484897/95288993-97938280-081e-11eb-847b-9dc435019d99.png">

Anything you can suggest please?
Thank you,
Max

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
