### ISSUE TITLE
Retroactive makes me very happy, finally i get back in control

### ISSUE THREAD

**Issue by Horndk** [cormiertyshawn895/Retroactive#135]
For something that feels like centuries apple have diminished the user experience to turn everything into a "shaken money tree" thus put themselves into the center of any experience regarding music, Movie, pictures and their organisation.

Now MY music is in the center again - not some store up my face constantly
Now MY pictures can be organised (iphoto/aperture) anyway i see fit and sorted in any direction

This is brilliant THANKS guys 👍 :-)

**Comment by cormiertyshawn895** [comment]
Thank you for your kind words!
