### ISSUE TITLE
Retroactive hangs on Extract iTunes 12.9.5

### ISSUE THREAD

**Issue by yourpaljimmy** [cormiertyshawn895/Retroactive#137]
Hi there,

When trying to install iTunes 12.9.5, Retroactive hangs when it gets to Extract iTunes. Works fine when I use Retroactive to install 12.6.5. When trying to install 12.9.5, I left it sit for several hours on the "extract" stage and nothing happens. I am running Catalina 10.15.7. I have tried restarting, redownloading, and other typical "fixes". The trouble with just using 12.6.5 is that my library was created with a newer version of iTunes and won't load.

Thanks in advance for any help that you may have.

![Screen Shot 2020-10-10 at 11 12 22 AM](https://user-images.githubusercontent.com/72663513/95659894-cc872a00-0ae9-11eb-917f-3770fe83046a.png)

**Comment by locksoft** [comment]
Same here on an M1 Mac Mini.
Any solution?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
