### ISSUE TITLE
to export videos

### ISSUE THREAD

**Issue by gibletizer** [cormiertyshawn895/Retroactive#138]
FYI, I thought it couldn't export videos but you just have to choose export original, not version. Also, you can't share videos to email.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
