### ISSUE TITLE
won't import from iphone

### ISSUE THREAD

**Issue by gibletizer** [cormiertyshawn895/Retroactive#139]
It keeps saying the phone is locked even though it's not and I clicked "Trust this computer" and entered  my passcode.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
