### ISSUE TITLE
iTunes just straight-up crashes.

### ISSUE THREAD

**Issue by octoturt** [cormiertyshawn895/Retroactive#14]
In the title. After the process, iTunes 10.7 won't launch.

**Comment by cormiertyshawn895** [comment]
Very strange. 
When iTunes crashes, can you copy and paste what's in the Problem Report into this Issue?

**Comment by octoturt** [comment]
Process:               iTunes [696]

Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               ???
Build Info:            iTunes-10702101~1
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           iTunes [696]
User ID:               501

PlugIn Path:             
PlugIn Identifier:       
PlugIn Version:          ??? (732.8)

Date/Time:             2019-11-02 23:00:14.198 -0400
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12
Bridge OS Version:     4.0 (17P572)
Anonymous UUID:        1024EFE2-9899-001A-DFC5-9C81871028F7


Time Awake Since Boot: 92 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b941000-000000010cae2000 [ 17.6M] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x000000010e832000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee42bebf8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010e832000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10b941000 -        0x10cae1fff + (???) <0CC47E12-134F-A9E1-7E4F-3EAC797C3050> 
       0x10e831000 -        0x10e8bf93f + (732.8) <42C11B81-6928-369F-B03E-D57355572700> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 148
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=18.7M resident=0K(0%) swapped_out_or_unallocated=18.7M(100%)
Writable regions: Total=9024K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9024K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            2748K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         512K        2 
__TEXT                            18.2M        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             85.4M       13 

Model: MacBookPro15,2, BootROM 1037.0.78.0.0 (iBridge: 17.16.10572.0.0,0), 4 processors, Quad-Core Intel Core i5, 2.3 GHz, 8 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Jul 24 2019 00:02:16 version 9.30.357.3.32.5.33 FWID 01-22b80374
Bluetooth: Version 7.0.0f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.1 Hub
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB 10/100/1000 LAN
USB Device: USB 3.1 Bus
USB Device: USB2.1 Hub
USB Device: USB2.0 Hub
USB Device: USB Laser Game Mouse
USB Device: Corsair K30A Gaming Keyboard
USB Device: USB3.0 Card Reader
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2

**Comment by cormiertyshawn895** [comment]
It looks the authentication timed out before Retroactive is able to sign iTunes 10.7. Did you accidentally click "Cancel" during the second authentication prompt?

Anyways, Retroactive → iTunes → "iTunes 10.7" → "Modify iTunes Again" should fix the issue.

You can also manually fix this:
- Spotlight Search > "Terminal".
- Paste this command into Terminal:
`sudo codesign -fs - /Applications/iTunes.app --deep`
- Terminal will ask for your login password. Type it in. (Your password won't be visible when you're typing it in, and that's normal.)
- Press the `return` key.
- Open iTunes again.

Let me know if this works for you.

**Comment by octoturt** [comment]
A few things:

1. Weirdly, I had never received a second prompt for authentication
2. Modifying again had been my first instinct and it didn't work
3. I just tried sign it again in Terminal and it.... failed. Then I installed Xcode and it succeeded and iTunes was able to launch!

Thanks for the help.
