### ISSUE TITLE
iTunes 10.7 won't access the mp3 files 

### ISSUE THREAD

**Issue by ulrichmeier** [cormiertyshawn895/Retroactive#140]
Dear Tyshawm,
thanks for providing Retroactive!
When I try to install iTunes 10.7 with Retroactive 1.9 on macOS Catalina 10.15.7 the installation procedure will not show a continue button after I did "Enable Full Disk Access". The option I get to continue is "I don't need to sync with iPod".
Then iTunes 10.7 starts, I see all playlist and all covers. When I try to play the song, it would not play any of the mp3 on disk. It plays the radio streams only.

Do you have a quick fix? The iTunes media is on the internal disk. Do you have any idea what might have gone wrong? If you needmore infos, pleas let me know.

Many thanks for your support,

Best regards,
Ulrich Meier   umeier@yahoo.com

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
