### ISSUE TITLE
iTunes 12.9.5.5 on Catalina not seeing Photos database?

### ISSUE THREAD

**Issue by piatigorsky** [cormiertyshawn895/Retroactive#143]
I have iTunes 12.9.5.5 installed on Catalina using Retroactive 1.5 (or possibly 1.6; it was several months ago). For photo management, I'm using the Photos app (5.0 (161.0.120)) in Catalina rather than iPhoto. It seems that iTunes somewhat recognizes the Photos database, since the albums that I created in Photos show up in the list in the photos tab in the iTunes sync interface, but no matter what I choose (sync all photos, or sync selected albums, or whatever other combination), no photos actually get synced, and iTunes always says the number of photos is 0. Is this expected behavior, and is there a workaround?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
