### ISSUE TITLE
Aperture Import (worked Big Sur, not Catalina)

### ISSUE THREAD

**Issue by xmacvicar** [cormiertyshawn895/Retroactive#145]
Hey there!

Love what Retroactive is doing here. Just thought I'd provide some feedback. I was on the Big Sur public beta when I first installed aperture (earlier today) and I noticed some things:

Import from SD card worked fast! Previews were amazing. This DOES NOT work on Catalina. The import function initiates, but no files from the SD card appear in the preview pane. This worked fine in Big Sur public beta.

Generally, navigating around the app on Big Sur was less buggy than it is on Catalina. I can't pinpoint it exactly, but I had less random crashes, etc. What is more problematic is that my install of Aperture on Catalina was a fresh one as I just formatted this afternoon.
<img width="2560" alt="Screen Shot 2020-10-28 at 10 38 30 PM" src="https://user-images.githubusercontent.com/784172/97518785-52222b00-196e-11eb-9504-61e2518ad81d.png">

**Comment by xmacvicar** [comment]
In this import window, there should be files appearing! Not sure if its a disk access issue, but in my Privacy prefs. I set Aperture to have full disk access and Files and Folders

**Comment by xmacvicar** [comment]
Here is another screenshot. You can see the folders all with 0 by them. But one folder has a "2" to indicate 2 photos in it. Some show the downward arrow indicating they are yet to be imported. All of these folders have many images in them, but when imported just simply show 0. I am not sure if this is an aperture/OS X issue, or one that is a combination of aperture and retroactive.

<img width="330" alt="Screen Shot 2020-10-28 at 10 52 22 PM" src="https://user-images.githubusercontent.com/784172/97519906-72eb8000-1970-11eb-9a41-5ae1aa0ae026.png">

**Comment by cormiertyshawn895** [comment]
Thank you for your feedback. [Retroactive 1.9 (Build 85) and later](https://github.com/cormiertyshawn895/Retroactive/releases/) added an option to optimize Aperture for macOS Catalina, which improves stability and re-enables the ability to import photos from removable volumes such as SD cards.
<img width="1123" alt="optimize-for-catalina" src="https://user-images.githubusercontent.com/57056759/99198587-865b6100-274e-11eb-9a6c-482b421c818a.png">

Please [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/), unlock Aperture again, and choose "Optimize for macOS Catalina".
