### ISSUE TITLE
Release 1.9 is 1.8?

### ISSUE THREAD

**Issue by JamaicanRumCream** [cormiertyshawn895/Retroactive#146]
The download link on the 1.9 release points to 1.8.

**Comment by ylluminate** [comment]
Yes, he accidentally put the 1.8 download in the 1.9 button - it needs to be fixed. If you scroll down you'll see the 1.9 zip at the bottom of the 1.9 release on the releases page.

**Comment by cormiertyshawn895** [comment]
@ylluminate is right, I put in the 1.8 download in the 1.9 button. This is fixed now.
