### ISSUE TITLE
iPhone (with ios 14.1 on Mac with 10.15.5) not showing up in iTunes

### ISSUE THREAD

**Issue by sfrazr** [cormiertyshawn895/Retroactive#147]
Greetings,

Once I discovered Retroactive, 
I was able to connect my iPhone 6s Plus until I recently updated the iPhone's ios.
Now my iPhone (with ios 14.1 on Mac with 10.15.5) is not showing up in iTunes.

I read all of the threads about various options to get it to work...
including the Terminal killall AMPDevices Agent, adding iTunes to have all access in System Preferences, restarting iTunes, etc

No dice (so far).

Please advise.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
