### ISSUE TITLE
Sync iPad through iTunes "cannot be synced. The required folder can not be found"

### ISSUE THREAD

**Issue by k9malinda** [cormiertyshawn895/Retroactive#148]
I have updated everything and reinstalled.  Goes all the way through sync and then get that- I use Retroactive to sync photos from MacBook pro to several iPads and it is imperative since iTunes will carry the actual file name with it (FinDER changes it to IMG_1234). 

How do I get around this?
<img width="1245" alt="Screen Shot 2020-11-11 at 7 28 19 AM" src="https://user-images.githubusercontent.com/74306045/98817403-aa860d80-23ef-11eb-8a0e-583a18e13360.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
