### ISSUE TITLE
Can't Run on Mojave

### ISSUE THREAD

**Issue by Am1nCmd** [cormiertyshawn895/Retroactive#15]
Hello, thx for your work.

![image](https://user-images.githubusercontent.com/15339573/68100660-b6491500-fefb-11e9-8dac-7b5d7b64441b.png)

I'm hoping this apps can work on 10.14.6 too, cz iTunes with Appstore is not working on 10.14.6

**Comment by l0bz1k** [comment]
iTunes 12.9.5 runs perfect on my Mojave 10.14.6

**Comment by Am1nCmd** [comment]
> iTunes 12.9.5 runs perfect on my Mojave 10.14.6

did I say iTunes 12.9.5? 

No, iTunes with appstore only on latest 12.6.5 see detail for this retroactive https://github.com/cormiertyshawn895/Retroactive/blob/master/screenshots/5.jpg

**Comment by cormiertyshawn895** [comment]
On macOS Mojave, iTunes 12.9.5 is protected by System Integrity Protection. Therefore, Retroactive can't readily modify or downgrade the existing iTunes app.

If you are willing to [disable System Integrity Protection](http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/), you can [install iTunes 12.6.5 on macOS Mojave by following bogdanw's instructions](https://forums.macrumors.com/threads/apples-special-version-of-itunes-that-still-has-an-app-store-currently-incompatible-with-macos-mojave.2143244/post-27613162).
