### ISSUE TITLE
MacOS BigSur release version and Retroactive 1.9

### ISSUE THREAD

**Issue by adamsdp** [cormiertyshawn895/Retroactive#150]
With MacOS Big Sur (11.0.1) being released today, can anyone confirm compatibility with the great work done in Retroactive 1.9? I notice it works with beta releases, just want to make sure it is compatible with the final release (and in particular Aperture).

Also, can I make a donation anywhere?!

**Comment by h0lz** [comment]
+1
(I'm also very interested in an answer to this.)

**Comment by jacke1vt** [comment]
It seems to work fine on the release version of Big Sur.  I haven't gone through *every* menu path or feature but it launches, views, imports fine.

**Comment by cormiertyshawn895** [comment]
Retroactive 1.9 works on the public release of macOS Big Sur 11.0.1. Donation is not available at the moment.
