### ISSUE TITLE
How do I install iTunes version of my choice? 

### ISSUE THREAD

**Issue by AegeanNet** [cormiertyshawn895/Retroactive#153]
I would like to install iTunes 12.6.4, or 12.4.3 on Big Sur. Wondering what would be the best way to install it? Reason being, it shows the Artists artwork in square shape that takes the mostly played album for that artist in your library. Rather than relying on Apple servers to get the artist artwork. Thanks.

**Comment by Mactendo** [comment]
I second that. I want to install 12.4.3 for the colourful background albums view, which was removed in 12.5
After a basic version number fix it is able to launch but gives an error -45076 then quits. macOS 10.15.7

UPD Ok, I was able to do it. I downloaded iTunes 12.4.3 from Apple (there's a link on the web) and I think I just changed its permissions as described [here](https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-2#post-27614012). Then I installed iTunes 12.6.5 via _Retroactive_ and moved iTunes 12.4.3 to the iTunes 12.6/Contents/MacOS/ bundle. Then launched iTunes 12.6 and it works.

Maybe I did something else to 12.4.3 before packing it inside 12.6, I'm not sure, it took almost a day of various trials and errors.

**Comment by SaintBilly** [comment]
> I second that. I want to install 12.4.3 for the colourful background albums view, which was removed in 12.5
> After a basic version number fix it is able to launch but gives an error -45076 then quits. macOS 10.15.7
> 
> UPD Ok, I was able to do it. I downloaded iTunes 12.4.3 from Apple (there's a link on the web) and I think I just changed its permissions as described [here](https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-2#post-27614012). Then I installed iTunes 12.6.5 via _Retroactive_ and moved iTunes 12.4.3 to the iTunes 12.6/Contents/MacOS/ bundle. Then launched iTunes 12.6 and it works.
> 
> Maybe I did something else to 12.4.3 before packing it inside 12.6, I'm not sure, it took almost a day of various trials and errors.

hello Mactendo. Can you please describe me how you did it? Because I also want the 12.4.3 badly. If you have 3 minutes of free time, pls write to me analytically the steps needed, because I tried according to your descriptions and it sitll gives me the same errors

**Comment by Mactendo** [comment]
> hello Mactendo. Can you please describe me how you did it? Because I also want the 12.4.3 badly. If you have 3 minutes of free time, pls write to me analytically the steps needed, because I tried according to your descriptions and it sitll gives me the same errors

Hi, SaintBilly. I don't remember the exact steps besides what I wrote above. I'll try to recreate it in a few days and will get back with the results.

**Comment by SaintBilly** [comment]
Thank you very much I really appreciate it, I am not an experienced user, thus I have a hard time with it
________________________________

**Comment by SaintBilly** [comment]
> > hello Mactendo. Can you please describe me how you did it? Because I also want the 12.4.3 badly. If you have 3 minutes of free time, pls write to me analytically the steps needed, because I tried according to your descriptions and it sitll gives me the same errors
> 
> Hi, SaintBilly. I don't remember the exact steps besides what I wrote above. I'll try to recreate it in a few days and will get back with the results.

Hello! Hope you are doing fine. Did you happen to find a viable workaround for that issue?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
