### ISSUE TITLE
iPhoto support in iTunes 12.9.5.5 for device synching

### ISSUE THREAD

**Issue by triton2021** [cormiertyshawn895/Retroactive#154]
dear tyshawn

1. retoractive is a great great piece of work and it works perfectly fine to use iPhoto under Catalina and Big Sur! **congrats!!!** (... and my iPhoto library with 95+k pictures runs on Big Sur with retroactive faster than on Mojave...)

2. I need to synch iPhoto albums with iPhones/ipads, but iTunes 12.9.5.5 does not offer synching with iPhoto... it only allows "Photos" or "choose folder". would it be possible to bring back "iPhotos"? 
here is a screenshot of the "reactive" iTunes under big sur

<img width="804" alt="big_sur_itunes_12 9 5 5_missing_sync_iphotos" src="https://user-images.githubusercontent.com/74570915/99315646-3ae6a700-2863-11eb-8176-735d996eb190.png">

and here is the same under Mojave
<img width="906" alt="mojave_itunes_12 9 5 5_with_sync_iphotos" src="https://user-images.githubusercontent.com/74570915/99315662-3fab5b00-2863-11eb-9f17-4b38c9fea29f.png">

thx, triton

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
