### ISSUE TITLE
Retroactive fails to unlock Aperture on macOS Big Sur running under Rosetta

### ISSUE THREAD

**Issue by michel-blanchard** [cormiertyshawn895/Retroactive#155]
I have attached the report for the error that occurs when trying to launch Aperture after unlocking with Retroactive.
[rapport.txt](https://github.com/cormiertyshawn895/Retroactive/files/5551489/rapport.txt)

**Comment by marcefn** [comment]
Same problem here with a brand new MacBook Pro M1. Is there any hope?
[Report.txt](https://github.com/cormiertyshawn895/Retroactive/files/5561737/Report.txt)

**Comment by sbingner** [comment]
`sudo codesign --force -s - /Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager`

**Comment by cormiertyshawn895** [comment]
Thank you for your feedback. This should be fixed in [Retroactive 1.9 (Build 86) and later](https://github.com/cormiertyshawn895/Retroactive/releases/). 

Please [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/) and unlock Aperture again.

**Comment by michel-blanchard** [comment]
Thanks, will try the new build.

**Comment by marcefn** [comment]
Working again! Thanks a lot. 👏👏👏
