### ISSUE TITLE
Cant finishing the installation on the step "Enable full disc access" while installing iTunes on BigSur

### ISSUE THREAD

**Issue by vaniks2407** [cormiertyshawn895/Retroactive#159]
Nothing happens on the step "Enable full disc access" while installing iTunes on BigSur.  Press the button, Enable access for iTunes, than nothing happens, can't finish the installation. I need iPod support, please help ))

**Comment by cormiertyshawn895** [comment]
Which language is your Mac set to? You can find out at System > Language & Region > Preferred languages.

**Comment by vaniks2407** [comment]
Russian, Russia

Вс, 22 нояб. 2020 г. в 14:19, Tyshawn Cormier <notifications@github.com>:

**Comment by vaniks2407** [comment]
I have changed the language to English, now I can see “tips” (drag me into
the list),

Retroactive and iTunes already in the list

When I try “drag” retroactive app from downloads to the list - there’s
system message “Retroactive will not have full disk access until its quit”,
press “quit and reopen” but then it’s Retroactive message “unable to quit
retroactive”





Вс, 22 нояб. 2020 г. в 14:20, Ivan Dick <vaniksdfr@gmail.com>:

**Comment by MacMuser** [comment]
It's not the Retroactive app you have to drag but the little icon that says Drag me.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
