### ISSUE TITLE
iWork '09 only supports exports in a VM workarounds on Mac host?

### ISSUE THREAD

**Issue by UInt2048** [cormiertyshawn895/Retroactive#163]
I'm using Retroactive to run older software inside a VM of older macOS software. As shown in the picture, I'm running this on real Apple hardware (despite not sharing all the information with High Sierra). Can I use anything from my macOS host to give Retroactive enough to do more than just export in the VM (besides actually dual-booting an older version of macOS just to run Retroactive)? 😉 

![image](https://user-images.githubusercontent.com/46784000/100685292-1651fb00-334a-11eb-9c93-6489d81b5661.png)

**Comment by cormiertyshawn895** [comment]
The editing canvas in iWork’09 requires OpenGL graphics acceleration, which is not available in virtual machines. You’ll need to run Retroactive on a real Mac with macOS High Sierra or macOS Mojave.
