### ISSUE TITLE
App misreading available space on computer

### ISSUE THREAD

**Issue by cowboyteevee** [cormiertyshawn895/Retroactive#165]
I have 57GB of free space on my HD, but attempting to install results in this message after I Authenticate: 
"There isn't enough free space to install iTunes. 
Your startup disk only has 12 GB available. To install iTunes, your startup disk needs to at least have 20 GB of available space.
Free up some space and try again." 
Is anyone else experiencing this? 
Using Retroactive 1.9
Thanks for any help!

**Comment by dmuiX** [comment]
Actuallly yes on my Macbook 13 on Big Sur. Here I have a separate Partition for my Data as I share it with Windows and Linux. So I have Macintosh HD (for the System Files) Macintosh HD - Data (For my User FIles) in a AFPS Container and an additional Partiton Data formated with HFS and Veracrypt encrypted. On the Second Data Partition I have linked my user folders: Movies, Pictures, Downloads, Documents and Music to Macintosh HD Data.
On my Hackingtosh Desktop installation was working just fine. Here I have left everything as it was. So just one AFPS Container with Macintosh HD and Macintosh HD Data.
So could be that it has something todo with my this partition layout.
As I think about it: I have installed and downloaded and copied much stuff on my Macbook, its not that tidied up at the moment.
My Hackintosh is much cleaner and does not have that much stufff...could be that too....
@cormiertyshawn895  
What does your partition layout look like?
Not sure what can be done about that...except a new installation...=?

UPDATE:
You can forget about everything I wrote above. But  I will not delete it. Although I think nobody saw it so far :D.

This has something todo with time machine snapshots:
My disk utility programm is showing just the amount of free space that the programm is telling me. Currently 13GB. It needs 20GB.
Disk utility tells me also there is 33.33GB removable. This is the amount that snapshots do occupy. 
So I would say the solution is to let time machine backup all current snapshots and then delete them. 
Well before deleting these snapshots I would check which are already created: 
```
tmutil listlocalsnapshotdates
```
For me it was like just from today and yesterday and my time machine backup was not complete. So I thought okay forget about it will install itunes and make a backup afterwards. To delete all snapshots here is a script:
```
for d in $(tmutil listlocalsnapshotdates | grep "-"); do sudo tmutil deletelocalsnapshots $d; done
```
source: https://apple.stackexchange.com/questions/340905/how-to-delete-all-local-timemachine-snapshots

And YES it worked. Disk utility still tells me there is 33.33GB removable. This musst be just a display error as the complete free space is now 47GB. So it freed everything up. 

AND YES finally itunes is getting installed :)

**Comment by dmuiX** [comment]
@devs you can close this topic

**Comment by dmuiX** [comment]
fixes it

**Comment by dmuiX** [comment]
close

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
