### ISSUE TITLE
iPhotoLibraryUpgrader support?

### ISSUE THREAD

**Issue by uwealtmann** [cormiertyshawn895/Retroactive#166]
It would be great if it would be possible to support the iPhotoLibraryUpgrader too to get access to older iPhoto libraries.

**Comment by Mac-Man-APH** [comment]
Hi

I thought I was doing something wrong after updating iPhone to iOS 14.2 as I could no longer sync my photos. iPhotoLibary is not selectable (greyed out) but somehow I did make it in picture source but it says 0 pictures available.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
