### ISSUE TITLE
Final Cut Pro 7 Not Unlocking

### ISSUE THREAD

**Issue by jamesbaileytv** [cormiertyshawn895/Retroactive#167]
I installed FCP 7 and ran Retroactive, clicked 'unlock', and nothing happened. FCP still has a 'no' symbol over its icon and does not open (I get the 'update to the newest version' prompt). I am on Mojave (10.14.6) and using Retroactive 1.9.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
