### ISSUE TITLE
iTunes 12.9.5 Crash on Mac mini M1

### ISSUE THREAD

**Issue by giorgiobrit** [cormiertyshawn895/Retroactive#168]
This is the error:

Process:               iTunes [1628]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1625]
User ID:               501

Date/Time:             2020-12-13 19:26:19.161 +0100
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        765B8560-9235-653C-40A1-3DD6321D69EE

Time Awake Since Boot: 28000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x0000000307f2cab0   pc: 0x00007ffdffbcc68c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 18064
    thread_create: 0
    thread_set_state: 0

Model: Macmini9,1, BootROM 6723.50.2, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Sep 11 2020 18:25:33 version 18.20.222.10.7.8.97 FWID 01-17360706
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100/1000 LAN 2, Ethernet, en8
Network Service: Wi-Fi, AirPort, en1
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: USB3.0 Hub
USB Device: 4-Port USB 3.0 Hub
USB Device: 4-Port USB 3.0 Hub
USB Device: JMS56x Series
USB Device: USB 10/100/1000 LAN
USB Device: USB2.0 Hub
USB Device: USB Optical Mouse
USB Device: USB2.0 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: 4-Port USB 2.0 Hub
USB Device: USB Mass Storage Device
USB Device: PC-LM1E Camera
USB Device: Keyboard Hub
USB Device: NS1068
USB Device: Apple Keyboard
USB Device: Scarlett 6i6 USB
Thunderbolt Bus: Mac mini, Apple Inc., 0.0
Thunderbolt Bus: Mac mini, Apple Inc., 0.0

**Comment by honghaoz** [comment]
Same issue, crashed on launch

<img width="1112" alt="CleanShot 2020-12-20 at 18 18 22@2x" src="https://user-images.githubusercontent.com/3926785/102732500-c1bdf200-42ef-11eb-9c23-154bb2d22a2f.png">

```
Process:               iTunes [8079]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [8076]
Responsible:           bash [8076]
User ID:               501

Date/Time:             2020-12-20 18:16:57.886 -0800
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        3467A271-4747-4325-708F-0C7CB4DBD0E1


Time Awake Since Boot: 13000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000030fdbfab0   pc: 0x00007ffdffeb746c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 463849
    thread_create: 0
    thread_set_state: 0

Model: MacBookAir10,1, BootROM 6723.61.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Oct 20 2020 12:49:54 version 18.20.222.14.7.8.100 FWID 01-ba327c2d
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0
```

iTunes 11.4 and iTunes 10.7 works well on M1 MacBook.

**Comment by giorgiobrit** [comment]
any solution?

**Comment by quietmansoath** [comment]
Also having the same issue as the OP, with the same settings (itunes 12.9.5 crash on mac mini M1, Big Sur)

```
Process:               iTunes [3027]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [3024]
Responsible:           bash [3024]
User ID:               501

Date/Time:             2020-12-25 14:40:46.404 -0500
OS Version:            macOS 11.0 (20A2411)
Report Version:        12
Anonymous UUID:        66BCFA15-942A-466D-BBE3-C096A412BA9D

Sleep/Wake UUID:       A4E46E1E-8BC9-4C9F-AA98-D3579026C46B

Time Awake Since Boot: 15000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000031011aac0   pc: 0x00007ffdffd467ec cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 9047
    thread_create: 0
    thread_set_state: 0

Model: Macmini9,1, BootROM 6723.41.11, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Sep 11 2020 18:25:33 version 18.20.222.10.7.8.97 FWID 01-17360706
Bluetooth: Version 8.0.0f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB 3.0 Bus
USB Device: 2.4G Wireless Mouse
USB Device: USB Receiver
Thunderbolt Bus: Mac mini, Apple Inc., 0.0
Thunderbolt Bus: Mac mini, Apple Inc., 0.0
```

**Comment by RR19840** [comment]
> any solution?

i'm waiting too... it worked on big sur on my 2015 MacBook pro but crashes on the new m1 MacBook.

so annoying!

**Comment by Shadester** [comment]
I can run an older version with the M1. Tried the 11.4 and it works. Will try 12.6.5, but I'm not sure it will work. Edit: 12.6.5 also works.

**Comment by occamsrazorben** [comment]
Also crashes on opening with M1 Mini and 12.9.5. I got 12.6.5 to install but the problem is my existing iTunes library that I am trying to migrate is made with 12.9.5 and so won't open with previous version. Has anyone got this to work on M1 since the previous posts?

**Comment by tocotronaut** [comment]
Same problem here.
Macbook Air M1 16GB RAM / 1TB SSD

Fresh install today ->  iTunes 12.9.5 ->  Crashes almost instantly.

**Comment by sztenni** [comment]
Same issue here: MacBook Air M1 8GB Ram, SSD 512GB, Big Sur 11.4
Tried also fresh install, it crashes instantly

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.
