### ISSUE TITLE
Aperture randomly crashes while browsing photo on Big Sur

### ISSUE THREAD

**Issue by 98827ddb7e5a2c2e261912a23d9251d6** [cormiertyshawn895/Retroactive#170]
For the first glance it might be a system/graphic card related compatibility issue. It shows "Graphics kernel error" in the crash report. 

My Mac is:
MacBook Pro (16-inch, 2019)
2.3 GHz 8-Core Intel Core i9
AMD Radeon Pro 5500M 4 GB
Running macOS Big Sur 11.0.1 (20B29)

Full crash report:
[full_error_report.txt](https://github.com/cormiertyshawn895/Retroactive/files/5694471/full_error_report.txt)

**Comment by cpdesjardins** [comment]
My issue seems related so I am conveying it by way of comment to this Open Issue.

(1)  I am getting Aperture crashes frequently, when browsing from image to image and when editing for horizon line or cropping.  It sometimes results in database corruption which must be repaired.

(2)  Video performance has become very poor.  Scrolling a thumbnail view is very slow for thumbnails to appear and you cannot jump to the end, the thumbnails won't appear.

My Mac is:
iMac Retina 5K 2020
3.3 GHz 6-Core Intel Core i5
AMD Radeon Pro 5300 4 GB
Running macOS Big Sur 11.0.1 (20C69)

[Aperture 2020 01 20.txt](https://github.com/cormiertyshawn895/Retroactive/files/5844894/Aperture.2020.01.20.txt)

**Comment by sad144** [comment]
Aperture crashes when I scroll more than 4 images using the left and right keys. Also, it takes up to a minute to populate images on the thumbnail viewer screen.

MP, Late 2019
3.3GHz, 12-Core Intel Xeon W
96GB of Ram
Radeon Pro Vega II, 32GB HBM2
1TB SSD
Referenced files store on 2700MB/s Promise Pegasus 2 RAID

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
