### ISSUE TITLE
Aperture does not work when opening from GUI on Big Sur

### ISSUE THREAD

**Issue by poyynt** [cormiertyshawn895/Retroactive#171]
**System details:
2017 Intel MacBook Pro
macOS Big Sur v11.1 build 20C69
Aperture version 1.9 build 86**

After updating to Big Sur and re-activating Aperture with Retroactive 1.9 (86), when I try to launch it from the GUI (via either Retroactive itself, Spotlight, Launchpad or Finder), it shows this error and exits:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/28945566/102251223-c5c9c880-3f19-11eb-8c8a-89c67db2b70d.png">

However when launching it via Terminal, it works as expected.

Console logs for a GUI launch:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/28945566/102251363-f14cb300-3f19-11eb-9357-8c201fbf7a74.png">
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/28945566/102251380-f90c5780-3f19-11eb-8fa0-de661ad0b4e6.png">

Note: My photo library is located on my external drive, with `drwxr-xr-x@` permissions.
<img width="255" alt="image" src="https://user-images.githubusercontent.com/28945566/102251484-1c370700-3f1a-11eb-90ab-64460538384f.png">

Note 2: I tried activating again, didn't work.

Note 3: I also tried to try [this](https://github.com/cormiertyshawn895/Retroactive/issues/132#issuecomment-731733971), but It didn't show the "Optimize for Catalina" option.

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
Try launching Aperture while holding "command + option + shift" to bring up the library repair dialogue. Then choose either "Repair Permissions" or "Repair Database", see if that helps.

<img width="607" alt="Aperture Library Repair Dialogue" src="https://user-images.githubusercontent.com/4169770/102301895-c9e5fc80-3f92-11eb-8f0c-1dbfba70ae9d.png">

**Comment by poyynt** [comment]
@Berylsnw I still get the same error, plus this:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/28945566/102359144-a5efde80-3fc5-11eb-9cdf-349246958a37.png">

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
Then it seems like the options left are:

1. Install Catalina on a different volume and use that to recover/access your Aperture library.
2. Try “Rebuild” option. That takes a LOT of time and for me not that much difference/improvement comparing to “Repair”.
3. Use “Photos” app to open/convert your Aperture library see if that helps. (Launch “Photos” while holding down “option” key, then choose your Aperture library. It won’t do anything to your original Aperture library so feel free to try)

For me, I’d say find a way to recover the library and MOVE ON. I just found out even though my library loads perfectly fine. Aperture became sort of unusable on Big Sur. Even browsing photos will cause “graphic kernel error” and crash. Maybe it’s something to do with my particular hardware/graphics card. 

Anyway, I’m planning to move to Lightroom or Photos and solve this once and for all. For super fine retouching I always use Photoshop so what really matters is just library managing. Which sadly I found out Lightroom and Photos are not checking all the boxes, at least for me.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
