### ISSUE TITLE
Is it possible to install the 12.4 version of itunes, is there any workaround for it? That version has the build in option for a total custom colors interface, a future that's missing from all other versions. 

### ISSUE THREAD

**Issue by SaintBilly** [cormiertyshawn895/Retroactive#172]

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
