### ISSUE TITLE
Dyld symbol not found on Big Sur

### ISSUE THREAD

**Issue by Baldhal** [cormiertyshawn895/Retroactive#173]
I used to read pdfs with a modified Preview9.0.app (https://github.com/frhd/macOS-Preview9.0/pull/3 and https://github.com/cormiertyshawn895/macOS-Preview9.0/archive/master.zip) but it crashes on launch since Big Sur :

> Dyld Error Message: Symbol not found: OBJC_IVAR$_NSImageCell._icFlags Referenced from: /Users/USER/Downloads//Preview.app/Contents/MacOS/Preview Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit in /Users/USER/Downloads//Preview.app/Contents/MacOS/Preview

I tried to fix it following this method (https://medium.com/@cormiertyshawn895/deep-dive-how-does-retroactive-work-95fe0e5ea49e). My main idea is to put the Catalina version of AppKit.framework inside Preview.app and redirect the calls inside. I tried with this command but it doesn't seem to work :

> sudo install_name_tool -change "/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit" "@executable_path/../Frameworks/AppKit.framework/Versions/C/AppKit" /[…]/Preview9.0.app/Contents/Frameworks/AppKit.framework/Versions/C/AppKit

Am I doing it wrong ?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
