### ISSUE TITLE
iPhone does not show up in iTunes 12.6.5 (installed with Retroactive)

### ISSUE THREAD

**Issue by furera** [cormiertyshawn895/Retroactive#174]
I have installed Retroactive 1.9 on my MacBook Pro M1 with Mac OS Big Sur Version 11.0.1. in order to use iTunes 12.6.5

Since I use Cloud Music Library on my iPhone 7s, I cannot access and administrate my Music Library I have created from my Music CDs. Therefore I wanted to use iTunes again. I could install iTunes 12.6.5 via Retroactive but unfortunately, when I connect my iPhone it does not show up in iTunes.

I haven't found a known issue on GitHub about this problem. Do you have any advice? Thanks a lot

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
