### ISSUE TITLE
Aperture – Metadata presets not working

### ISSUE THREAD

**Issue by EddCh** [cormiertyshawn895/Retroactive#176]
Firstly I just want to say a HUGE thank you for the creation of Retroactive – which is an awesome app and very much appreciated by this Aperture user.

Aside from the 1.9 patched version of Aperture 3.6 mostly working very well and stable on my Mac Pro 2013 (32GB, 3.5 GHz 6-Core, running macOS Catalina 10.15.7), I have noticed that access to managing metadata presets does not work. When selecting a metadata-related menu option (ie. Aperture>Presets>Metadata… or perhaps Metadata>Batch Change… or from the "Info Inspector" palette cog wheel) nothing happens. Normally a 'dialogue' window pops up with the relevant settings to choose from. However Lifting/Stamping metadata DOES work as well as keywording, rating and colour labelling.

All other forms of presets management from the Aperture>Presets menu—"Image Export", "Web Export", "File Naming…", "Folder Naming…" and "Slideshow…"—appear to work fine. It's just the "Metadata…" that does not work.

**Comment by GalaxyEmperor** [comment]
Is there any reports on that in Console?
Open 'Console' and select 'system.log'. Retry to select Metadata in Aperture and check if something is printed to the console.

**Comment by EddCh** [comment]
> Is there any reports on that in Console?
> Open 'Console' and select 'system.log'. Retry to select Metadata in Aperture and check if something is printed to the console.

OK, so this is what the system.log recorded at the time that I tried to use a metadata function, specifically "Manage Presets" and "Batch Change". Nothing happens on screen after the command is selected.


**Jan 14 16:31:06 Macintosh-2 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.02000000-0600-0000-0000-000000000000[1942]): Service exited due to SIGKILL | sent by mds[181]
Jan 14 16:31:07 Macintosh-2 com.apple.xpc.launchd[1] (com.cisco.videoguardmonitor[2040]): Service exited with abnormal code: 126
Jan 14 16:31:07 Macintosh-2 com.apple.xpc.launchd[1] (com.cisco.videoguardmonitor): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 16:31:17 Macintosh-2 com.apple.xpc.launchd[1] (com.cisco.videoguardmonitor[2046]): Service exited with abnormal code: 126
Jan 14 16:31:17 Macintosh-2 com.apple.xpc.launchd[1] (com.cisco.videoguardmonitor): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jan 14 16:31:27 Macintosh-2 com.apple.xpc.launchd[1] (com.cisco.videoguardmonitor[2057]): Service exited with abnormal code: 126**

![Screenshot 2021-01-14 at 16 36 10](https://user-images.githubusercontent.com/76597145/104620428-e73be280-5686-11eb-8178-0d23e2a7a101.jpg)
![Screenshot 2021-01-14 at 16 35 55](https://user-images.githubusercontent.com/76597145/104620432-e7d47900-5686-11eb-96e8-c7695ca8278c.jpg)

**Comment by GalaxyEmperor** [comment]
It looks like the 'com.cisco.videoguardmonitor' is causing the problem.
check here and consider removing the videoguardmonitor.

Open the 'Activity Monitor' and enter in the search field something like 'guard' to find it. You can select it and press cmd-i to get more infos about it.
Probably it is launched by a plist file. It is likely in your '/Users/username/Library/LaunchAgents' folder, but could be in '/Library/LaunchAgents'

**Comment by EddCh** [comment]
> It looks like the 'com.cisco.videoguardmonitor' is causing the problem.
> check here and consider removing the videoguardmonitor.
> 
> Open the 'Activity Monitor' and enter in the search field something like 'guard' to find it. You can select it and press cmd-i to get more infos about it.
> Probably it is launched by a plist file. It is likely in your '/Users/username/Library/LaunchAgents' folder, but could be in '/Library/LaunchAgents'

I looked for that, found 3 .plist files that had "videoguard" in its name inside the LaunchAgents folder and removed them. Restarted my Mac, opened Aperture and it still does not do anything when I try using the Metadata functions. This time the system.log recorded the following:

**Jan 14 18:58:39 Macintosh-2 diagnosticd[917]: System mode client started - Console (916) - mode: 0xb, filter: "<empty>"
Jan 14 18:59:00 Macintosh-2 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.04000000-0100-0000-0000-000000000000[812]): Service exited due to SIGKILL | sent by mds[181]
Jan 14 18:59:06 Macintosh-2 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.recentsd.937): Failed to bootstrap path: path = /System/Library/PrivateFrameworks/CoreRecents.framework/Versions/A/Support/recentsd, error = 2: No such file or directory
Jan 14 18:59:08 Macintosh-2 com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0D000000-0200-0000-0000-000000000000[895]): Service exited due to SIGKILL | sent by mds[181]
Jan 14 18:59:22 Macintosh-2 com.apple.xpc.launchd[1] (com.apple.CloudDocs.MobileDocumentsFileProvider[730]): Service exited due to SIGKILL | sent by launchd[1]**

**Comment by GalaxyEmperor** [comment]
This System Messages are not related to Aperture, but rather to iCloud synching.
Have you tried to reboot into Recovery Mode (hold down the keyboard shortcut Command-R while booting) and launch DiskUtility, use FirstAid to check your hard disk.

**Comment by EddCh** [comment]
> This System Messages are not related to Aperture, but rather to iCloud synching.
> Have you tried to reboot into Recovery Mode (hold down the keyboard shortcut Command-R while booting) and launch DiskUtility, use FirstAid to check your hard disk.

Yes, I have already run Disk FirstAid (and have just done so again) but everything was fine.

In all other instances, the Mac Pro and Aperture is running perfectly fine. No crashes or anything else. Even when the functionality does nothing when I try to use it, the program does not crash or glitch in any way – I can just carry on as though I never selected the function at all.

**EDIT: Issue #181 seems to have a similar problem.**

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
