### ISSUE TITLE
cannot enable full disk access

### ISSUE THREAD

**Issue by jimh54** [cormiertyshawn895/Retroactive#178]
I have attempted to enable full disk access in big sur for this app, for itunes, and for MacUpdater apps. I followed the directions you provide to open the security and privacy settings and dragged the itunes app to the window as instructed but the app will not launch after completing the task. the icon bounces once but will not launch. I enabled iPhoto also and it does launch. can you help?

**Comment by GalaxyEmperor** [comment]
Have you entered your PassWord in the System Preferences? Click the Lock button left…

![Full Disk Access 1](https://user-images.githubusercontent.com/62428938/104587445-383bde80-5667-11eb-9443-8a753c209bab.jpg)

**Comment by MacMuser** [comment]
It's not the iTunes app to drag to the window but the actual icon thingie with the large arrow, saying Drag Me. Then a window opens with firworks and installation with full disk access is comptete. You can do it retrospectively by going the tinstallation again, it won't d/l a new copy but does go through the drag me part again.

**Comment by cormiertyshawn895** [comment]
You need to drag the “drag me into here” pill into the list.
