### ISSUE TITLE
iTunes 10.7 doesn't work with library on external drive? Permission issues?

### ISSUE THREAD

**Issue by mills70** [cormiertyshawn895/Retroactive#179]
First of all thankyouthankyouthankyou for Retroactive, i was so sad when my old 2011 macbook finally gave up the ghost bc I loved itunes w/cover flow...just a sensible app, no muss, no fuss. When I saw Retroactive I didn't feel so bad moving on!

Installed on the new MacBook Pro (2.3ghz Intel core i9), running 11.1. Set up, everything looks good, but nothing plays. Do not get a progress bar. 

After some experimenting, mp3s in the home folder do play, those on the external drive (99.9% of my collection) do not. 

Dragging and dropping into iTunes get a spinning beach ball and "Attempting to copy to this disk failed. You do not have enough access privileges for this operation." (Privileges on the external are correct, however)

Yes, this sounds like a Mac issue and not a Retroactive issue. I ask bc I wonder if anybody out there has had this issue and solved it?

Thanks

**Comment by mills70** [comment]
Did a little more digging to see (in my limited knowledge) what might be happening. Here's the console log when I try to play an external drive file:

System Policy: iTunes(27923) deny(1) file-read-data /Volumes/Another Blue World/iTunes/iTunes Music/Coldcut/Sound Mirrors/01 True Skool (Spank Rock BBC SoundSystem Remix).aif

Failed to create LSApplicationRecord for file:///Applications/iTunes.app/Contents/MacOS/iTunes.app/ from file:///Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes: 'The operation couldn’t be completed. (OSStatus error -10819.)'

BackgroundSession <A3AAB9CE-7AF6-4EC7-8877-1DF3C16493BC> connection to background transfer daemon invalidated

"Cannot check access to a private account type: (null)"

[ERROR] we received an error <private>, retry in 60000ms (count:3926)...

Peer connection [pid=568] lacks APSConnectionInitiateEntitlement

Interrupted connection to service com.apple.apsd

System Policy: iTunes(27923) deny(1) file-read-data /Volumes/Another Blue World/iTunes/iTunes Music/Automatically Add to iTunes

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
