### ISSUE TITLE
PROBLEM: Using iTunes 12.9.5 with Serato, Rekordbox and Virtual DJ

### ISSUE THREAD

**Issue by tandyfied** [cormiertyshawn895/Retroactive#180]
I have installed a retroactive copy of iTunes on both my iMac and Macbook Pro with great success. Both pulled up my libraries and everything so far works seemlessly. However, I have encountered an issue where the DJ software I use to read the iTunes libraries on both machines only reads the new library created by Apple Music. Only the SDK is read by all the DJ software family in Big Sur and even exporting an XML file in Music renders it pretty useless when you can't even point the DJ apps to the newly created file in their respective settings. It seems that the only way round is to completely delete Apple Music and see if that triggers the DJ software to search for an XML file by default to load playists etc. Google searches have so far yielded nothing to help me overcome the problem. Any assistance on this would be greatly appreciated.

**Comment by zombiexpress** [comment]
I feel your pain. I'm trying to accomplish the exact same thing. For decades I've used iTunes to setup all my playlists as I can easily create backups of my event playlists on iPads in the event of a computer crash. VDJ was always great to use with iTunes, but now it only recognizes the crappy Apple Music app as "iTunes." Did you ever find a solution?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
