### ISSUE TITLE
Problem with Aperture not showing IPTC Core metadata

### ISSUE THREAD

**Issue by chultz** [cormiertyshawn895/Retroactive#181]
After clicking on the Info tab in Aperture 3.6, under the dropdown selection, IPTC Core and Custom Fields do not show. Also, when selecting Edit..., nothing happens. A Metadata Views window should appear.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
