### ISSUE TITLE
iPhoto Crashes on launch in Big Sur 11.1 under Rosetta

### ISSUE THREAD

**Issue by RyDawg96** [cormiertyshawn895/Retroactive#182]
The app was working before when I initially installed it but with some graphical bugs, but now the app crashes on launch and I cant get it to work at all,

**Comment by juancruz85** [comment]
Same here Im on Mac OS 13 I don't know why but someone else had a different problem on Mac OS Big Sur and someone commented that Big Sur broke retroactive

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
