### ISSUE TITLE
Retrospective not opening Aperture

### ISSUE THREAD

**Issue by mamabird3491** [cormiertyshawn895/Retroactive#184]
I downloaded Retrospective today, and after installing and entering my computer password, it told me I could start using Aperture.  However, Aperture will not launch.  I've tried this several times to no avail.

**Comment by GalaxyEmperor** [comment]
A little more infos could help, on my MBA M1 (MacBook Air) late 2020, it works fine. What is the output in the system log, and do you have a Crash Report?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
