### ISSUE TITLE
Final Cut Pro 7 - Codec Not Found Still Showing

### ISSUE THREAD

**Issue by Jman57** [cormiertyshawn895/Retroactive#185]
Hello

I updated my Mac to Mojave and used Retroactive to open FCP 7. I followed the directions on the recent read me post, but I continue to get the message that says "codec not found. You may be using a compression type without the corresponding hardware card." I can click through this and the program opens, but I do not have access to canvas, tool bench or timeline.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
