### ISSUE TITLE
Final cut pro 7 not run on mojave 10.14.6

### ISSUE THREAD

**Issue by ywsg** [cormiertyshawn895/Retroactive#186]
hi cormiertyshawn895,my computer has install retroactive 1.9,but the final cut pro 7 doesn't work。can you give me a advice salve this problem，thank you so much！

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
