### ISSUE TITLE
Aperture won't Import (Big Sur 11.2ß, MacBook Air M1) 

### ISSUE THREAD

**Issue by GalaxyEmperor** [cormiertyshawn895/Retroactive#188]
Hi, first I like to hug you guys (no kisses), this is an awesome project.

My feedback maybe helps others to make Aperture work.
I tried to import some Fotos from my Desktop, but in the Import section only files from the 'Pictures' folder show up.
No file and no folder from the Desktop, but I was able to drag my folder from the Desktop to the location section in Import (the one below the image preview) and the Fotos showed up. But when I tried to import, an error popped up: 'Import Items Completed With Errors'… 0 Items Imported…
So I tried to get them from the CF-Card, but with the same result.

After switching on my Brain, I opened SysPrefs - Security & Privacy - Privacy and selected 'Full Disk Access' clicked the Lock (bottom left) to authenticate and added 'Aperture'.

And voila… it works as expected.

![Full Disk Access 3](https://user-images.githubusercontent.com/62428938/104590678-f497a380-566b-11eb-8611-5d177190a4c7.jpg)

**Comment by visionsbydavid** [comment]
I was having the same issue as well. Thanks for your tip!
It works now.
However Aperture is getting very glitchy. 
It keeps crashing when I try to crop an image and then fix the horizon...

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
