### ISSUE TITLE
iTunes issue on MacBook Air M1

### ISSUE THREAD

**Issue by SwissmonBeat** [cormiertyshawn895/Retroactive#189]
First, thank you for your work Cormierty, it really helps keeping faith on Apple Product.

As other persons as the same problem, I wanna ask if someone know how to downgrade an iTunes Library.ilt

With the current Retroactive app, iTunes 12.6.5 is working fine on Big Sur on a M1 mac. However, I'm having issu importing my old playlist from iTunes 12.8 to work with the iTunes 12.6.5.

It's possible to import the .xml playlist but their is a problem with the importing date (to iTunes, every song are import from the day I import the .xml playlist)

So I'm trying to figure it out how to downgrade the iTunes library.ilt to see if I'm having import date problem.

If not, I'm waiting to see if their is a workaround to use iTunes 12.9 on Big Sur on a M1 mac.

Thx again,

Have a good day,

Swiss mon Beat

**Comment by MelloMikeUK** [comment]
Hi there.

I've just got a new MacBook Pro with the M1 chip but am completely failing to install iTunes onto it. Is there any chance you could please assist me with this? It would be much appreciated!

**Comment by SwissmonBeat** [comment]
On the new M1 mac you can only donwload iTunes 12.6 and older version. The iTunes 12.9 is not working right now because there is a signature issu. The OS won't start the app because it doesn't recognize it as a valid app. But unfortunatly I didn't find any workaround for now. It's all I can say :)

**Comment by MelloMikeUK** [comment]
Thanks for the quick reply! When using iTunes 12.6, I get this error message 

"iTunes cannot read the contents of the iPhone “*Mikes iPhone ”. Go to the Summary tab in iPhone preferences and click Restore to restore this iPhone to factory settings." 

Again any advice? I really need to be able to use iTunes.

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.
