### ISSUE TITLE
Aperture - crash after Retroactive completed successfully

### ISSUE THREAD

**Issue by jb59** [cormiertyshawn895/Retroactive#19]
This is a brilliant piece of software - worked like a dream on iPhoto, and I couldn't be happier. 
However, Aperture is still crashing with following crash report (Have uninstalled Aperture - cleaned with Clean My Mac X and reinstalled Aperture from my AppStore account) - any advice welcome!! 

rocess:               Aperture [1095]
Path:                  /Applications/Aperture.app/Contents/MacOS/Aperture
Identifier:            com.apple.Aperture3
Version:               3.6 (3.6)
Build Info:            Aperture-500021000000000~3
App Item ID:           408981426
App External ID:       731142774
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Aperture [1095]
User ID:               501

Date/Time:             2019-11-10 10:47:34.146 +0000
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Anonymous UUID:        D5BAF75C-871B-4B64-FC3F-9B87ECA34CBF

Time Awake Since Boot: 510 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer
  Referenced from: /Applications/Aperture.app/Contents/MacOS/Aperture
  Reason: no suitable image found.  Did find:
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: open() failed with errno=13
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: stat() failed with errno=1
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: open() failed with errno=13
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: stat() failed with errno=13

Binary Images:
       0x10e66c000 -        0x10eda4fff  com.apple.Aperture3 (3.6 - 3.6) <C083F141-A101-38B8-8132-6F4ACFA2BBA8> /Applications/Aperture.app/Contents/MacOS/Aperture
       0x10efd2000 -        0x10efdcff7  com.apple.PhotoFoundation (1.0 - 400.2) <F84CC426-F9FE-390B-9475-E61E3C62851E> /Applications/Aperture.app/Contents/Frameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation
       0x10f069000 -        0x10f5ebfff  com.apple.RedRock (1.9.4 - 500.16) <C725F461-291D-38D1-9CB2-5EA26B3F364B> /Applications/Aperture.app/Contents/Frameworks/RedRock.framework/Versions/A/RedRock
       0x10fbc4000 -        0x10fc31ff7  com.apple.iLifePageLayoutCore (1.0 - 500.5) <05BC76C2-9EC2-3EB7-B212-7DDD286B2871> /Applications/Aperture.app/Contents/Frameworks/iLifePageLayoutCore.framework/Versions/A/iLifePageLayoutCore
       0x10fce4000 -        0x10fce8fff  com.apple.iLifePhotoStreamConfiguration (3.4 - 2.5) <9C7AFABC-8D42-3A9D-A62E-A54730FB464D> /Applications/Aperture.app/Contents/Frameworks/iLifePhotoStreamConfiguration.framework/Versions/A/iLifePhotoStreamConfiguration
       0x10fcf9000 -        0x10fd23fff  com.apple.iLifeAssetManagement (2.7 - 400.7) <01F525E2-7103-38E9-865D-7828D20754EA> /Applications/Aperture.app/Contents/Frameworks/iLifeAssetManagement.framework/Versions/A/iLifeAssetManagement
       0x10fd60000 -        0x10fd6afff  com.apple.iphoto.AccountConfigurationPlugin (1.2 - 1.2) <867865E4-66F4-39AD-A5E9-96E53FBAA39F> /Applications/Aperture.app/Contents/Frameworks/AccountConfigurationPlugin.framework/Versions/A/AccountConfigurationPlugin
       0x10fd8b000 -        0x10fe15fff  com.apple.MobileMe (13 - 1.0.4) <65494CD8-55A0-30AC-A03A-7E68283A0719> /Applications/Aperture.app/Contents/Frameworks/MobileMe.framework/Versions/A/MobileMe
       0x10fe88000 -        0x10fe93ffb  com.apple.PluginManager (1.7.6 - 55) <83B61846-2D78-3EED-952B-4F6B22845540> /Library/Frameworks/PluginManager.framework/Versions/B/PluginManager
       0x10feab000 -        0x1100acfff  com.apple.prokit (8.0 - 5015) <4422712B-380A-395F-92C4-DEFB877AC650> /Applications/Aperture.app/Contents/Frameworks/ProKit.framework/Versions/A/ProKit
       0x110231000 -        0x110572ff7  com.apple.iLifeSlideshow (3.1.2 - 1152.19) <CC882774-0063-32EE-8F93-129BF88A66BC> /Applications/Aperture.app/Contents/Frameworks/iLifeSlideshow.framework/Versions/A/iLifeSlideshow
       0x110703000 -        0x110719ff7  com.apple.iLifeFaceRecognition (1.0 - 30.11) <846AEC01-11F8-336B-9954-EB14D3C8AAC0> /Applications/Aperture.app/Contents/Frameworks/iLifeFaceRecognition.framework/Versions/A/iLifeFaceRecognition
       0x110731000 -        0x11075fff7  com.apple.fayray.PrintServices (920131014 - 11.11) <EA8C7731-7DF7-35DD-A7FF-0FCFCE26C8BA> /Applications/Aperture.app/Contents/Frameworks/PrintServices.framework/Versions/A/PrintServices
       0x1107c1000 -        0x1107ecfff  com.apple.ProUtils (1.1 - 500.3) <1EE53B28-EF8D-3413-9DC1-C55B56CE4A41> /Applications/Aperture.app/Contents/Frameworks/ProUtils.framework/Versions/A/ProUtils
       0x11082a000 -        0x110a24ff7  com.apple.geode (1.5.3 - 500.9) <68B3122B-380E-38AC-ADF9-8571DE3F0EF6> /Applications/Aperture.app/Contents/Frameworks/Geode.framework/Versions/A/Geode
       0x110b9b000 -        0x110bfbfff  com.apple.proxtcore (1.4.1 - 500.2) <818709BB-209D-3B01-9701-FEC9B025C98F> /Applications/Aperture.app/Contents/Frameworks/ProXTCore.framework/Versions/A/ProXTCore
       0x110cb6000 -        0x110daafff  com.apple.iLifeSQLAccess (1.7.1 - 400.2) <25E1A248-33D9-337C-93E6-9A69678F6AAB> /Applications/Aperture.app/Contents/Frameworks/iLifeSQLAccess.framework/Versions/A/iLifeSQLAccess
       0x110e81000 -        0x110ea2ff7  com.apple.iPhoto.Tellus (1.3 - 400.2) <5F83E23D-3E07-3E81-B56C-9828690DAE41> /Applications/Aperture.app/Contents/Frameworks/Tellus.framework/Versions/A/Tellus
       0x110eda000 -        0x110efefff  com.apple.iPhoto.Tessera (1.1 - 400.2) <30BC8A34-B855-3CBE-BAB1-0E6F37B65F0F> /Applications/Aperture.app/Contents/Frameworks/Tessera.framework/Versions/A/Tessera
       0x119298000 -        0x119328b5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld
    0x7fff2eeb0000 -     0x7fff2f0a9ffd  com.apple.avfoundation (2.0 - 1730.15) <EA7413E2-C050-380B-A396-F622BFA73071> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff2f296000 -     0x7fff2f296fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <956D070C-B522-3A08-891A-CAD6BA4082D1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff305b2000 -     0x7fff306f4ff5  com.apple.AddressBook.framework (11.0 - 2421) <FB94811C-67C1-34BA-B64F-7041695D33E3> /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
    0x7fff306f5000 -     0x7fff314adffe  com.apple.AppKit (6.9 - 1894.10.126) <76EB4086-CA3D-3448-8CE0-9812F9A94F3A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff314fd000 -     0x7fff314fdfff  com.apple.ApplicationServices (48 - 50) <0748E453-524B-33BA-806B-22786DED2958> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3182f000 -     0x7fff3190fff2  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <CAE6B655-8D07-3040-811E-CE5DE42249AE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff31911000 -     0x7fff31911fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <FE7A9727-7F3F-3E0F-B827-DF421993ED12> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff32078000 -     0x7fff32078fff  com.apple.Carbon (160 - 162) <56A09CBE-D5EB-3918-B42B-B3ABFF52E1D1> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3255d000 -     0x7fff3255dfff  com.apple.Cocoa (6.11 - 23) <EB4AD4EA-3212-385A-876E-9F8B30F8CA56> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff32a40000 -     0x7fff32f4fffa  com.apple.audio.CoreAudio (5.0 - 5.0) <73C7F0DD-8919-3056-AB1F-67705F942A04> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff334c6000 -     0x7fff33945fe7  com.apple.CoreFoundation (6.9 - 1673.126) <15D61616-B29B-3BDB-8624-4B84A4956485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3432b000 -     0x7fff34393ff5  com.apple.corelocation (2388.0.21 - 2388.0.21) <D9BE9D62-C4E4-32AF-9E98-770AE8778A90> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff346ee000 -     0x7fff347c8ffc  com.apple.CoreMedia (1.0 - 2510.17.4.6) <A455F944-F862-3668-AA2C-008106F9814F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff348b3000 -     0x7fff348b3fff  com.apple.CoreServices (1069.11 - 1069.11) <C8F86BE7-AAED-30A6-BBC2-550446137E7C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff35851000 -     0x7fff35857ff7  com.apple.DiskArbitration (2.7 - 2.7) <A3D2B0A0-3C72-3893-87BF-D45FE398A905> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff35a2b000 -     0x7fff35a2dff8  com.apple.ExceptionHandling (1.5 - 13) <5A4331C9-AE65-3547-9DBF-1E4D51BBFAB2> /System/Library/Frameworks/ExceptionHandling.framework/Versions/A/ExceptionHandling
    0x7fff35b89000 -     0x7fff35f50ff4  com.apple.Foundation (6.9 - 1673.126) <470C2315-3047-39BB-BB6B-2C620087091C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff362c6000 -     0x7fff36369ffb  com.apple.framework.IOKit (2.0.2 - 1726.41.1) <FBB4A97B-D7CF-3B8C-932D-672343D63260> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff36399000 -     0x7fff363f1ff6  com.apple.ImageCaptureCore (1.0 - 1600.18) <E61ECB5C-38AC-3D4F-A770-A422260B3E77> /System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore
    0x7fff37ed5000 -     0x7fff380dfffa  com.apple.MapKit (1.0 - 2096.21.8.28.18) <A6D7699E-784C-3264-9E69-B6DC08BE1177> /System/Library/Frameworks/MapKit.framework/Versions/A/MapKit
    0x7fff3dd7d000 -     0x7fff3dd8cff7  com.apple.opengl (17.10.22 - 17.10.22) <0142B045-DCF8-3554-A7FB-48A173541E40> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff3df3b000 -     0x7fff3e02fff2  com.apple.PDFKit (1.0 - 825.10) <871F915A-FC4C-3681-86BE-4CB3FEB43321> /System/Library/Frameworks/PDFKit.framework/Versions/A/PDFKit
    0x7fff3e4de000 -     0x7fff3e509ff7  com.apple.QTKit (1.0 - 5) <4DF85D83-D9DF-3975-8967-8AD7625BD7A7> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff3ed45000 -     0x7fff3ed45fff  com.apple.quartzframework (1.5 - 23) <7BAF742D-822E-3047-BE57-9DD6EFCF8924> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff3ed46000 -     0x7fff3efc4ff0  com.apple.QuartzCore (1.11 - 815.19.4.2) <5F492A40-BBBC-3A31-83A8-32462A7B1FB4> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff3fb11000 -     0x7fff3fe57ff6  com.apple.security (7.0 - 59306.41.2) <FB3774D5-C940-35FB-960A-86253A01BDAE> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff40ccb000 -     0x7fff40d35ff7  com.apple.SystemConfiguration (1.19 - 1.19) <A52A533D-DA25-3607-A18E-CA7C539E1C52> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff44055000 -     0x7fff446f0ff2  com.apple.WebKit (15608 - 15608.3.10.1.4) <37C34BB7-F23E-3D1B-B36B-F5A28925E777> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff446f1000 -     0x7fff44731ffc  com.apple.iTunesLibrary (12.10.1 - 12.10.1) <ED25D98D-6976-3187-937F-2224DC49C6B6> /System/Library/Frameworks/iTunesLibrary.framework/Versions/A/iTunesLibrary
    0x7fff4486a000 -     0x7fff4497dffc  com.apple.AOSKit (1.07 - 276) <465E9B95-F38B-388A-BCE6-5A4E26ECC594> /System/Library/PrivateFrameworks/AOSKit.framework/Versions/A/AOSKit
    0x7fff4ca07000 -     0x7fff4ca1aff1  com.apple.CrashReporterSupport (10.13 - 15011) <E4E96CDA-DFC4-3096-BCFC-994DB61D3E4D> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff66dd8000 -     0x7fff66e4eff0  com.apple.iLifeMediaBrowser (2.14.1 - 785) <96BC227B-41F7-3BF8-A6E1-9F078277068F> /System/Library/PrivateFrameworks/iLifeMediaBrowser.framework/Versions/A/iLifeMediaBrowser
    0x7fff67825000 -     0x7fff67826ff3  libSystem.B.dylib (1281) <1DD1BCD2-2C85-3B81-8CAF-224FB042F441> /usr/lib/libSystem.B.dylib
    0x7fff69665000 -     0x7fff69696ff6  libobjc.A.dylib (781) <D866A31E-5CB1-3327-8D22-C4F83C9225D0> /usr/lib/libobjc.A.dylib
    0x7fff69aea000 -     0x7fff69b34ff7  libstdc++.6.dylib (104.1) <8D404CA3-0176-3BC6-88D4-C77A552FEC56> /usr/lib/libstdc++.6.dylib

**Comment by cormiertyshawn895** [comment]
Can you try the following: 
1. [Download the latest version of Retroactive (Version 1.2)](https://github.com/cormiertyshawn895/Retroactive/releases/download/1.2/Retroactive.1.2.zip), which should resolve the issue where Aperture and iPhoto may fail to launch (Error 13).
1. Launch Retroactive (Version 1.2), select Aperture, and choose "Modify Aperture again"
<img width="1123" alt="run_again" src="https://user-images.githubusercontent.com/57056759/67743375-af8e3f80-f9db-11e9-81f4-69e6f6bd15d8.png">

Please let me know if this fixes Aperture for you!

**Comment by jb59** [comment]
You are indeed a legend. iPhoto and Aperture running on Catalina 10.15.1
Please reply to the Donate message - I would like to!!!!!
