### ISSUE TITLE
What to expect in the near or far future ? + fix iTunes to Music migration

### ISSUE THREAD

**Issue by tdechangy** [cormiertyshawn895/Retroactive#191]
Retroactive SAVED MY LIFE after the update from iTunes to Music lost essential data !!!

Unfortunately, this is only a temporary solution since those apps won't be maintained anymore and issues will probably start rising sooner than we wish. So :
- can you tell **what are your expectations here if any** (duration of this app support and ability to hold its compatibility with OS versions) ?

more community driven:
- about iTunes more specifically I  didn't find a way to **import my tracks to Music with al my original data** like "date added" nor their "rating stars", while playlists are also missing, but hopefully the Retroactive app allows me to export them (but not smart rules for such playlists).
These data are vital in my listening workflow (rating in first place, then date added, then playlists bulk import with smart settings).
> I tried the classic way by opening a new Music library and selecting my last iTunes library.itl file to be loaded, but this led to the defined issue.  Even my artworks were missing, which is why the classic import from folder worked even better.
I wait for an answer from Apple and let you know if I have any viable solution.
Let me know (community too!) if you found some good tricks :-)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
