### ISSUE TITLE
Comment: the UX design is A+

### ISSUE THREAD

**Issue by rtcpersonal2020** [cormiertyshawn895/Retroactive#193]
this not an issue report, but Github doesn't have (AFAIK) an easy way to send some Kudos to the developers for making the user experience of installing and using this tool so freaking great.  It's as good or better thanApple at their best.

Virtual high-fives to all the devs on this project for making it easy to use and putting time into the user experience. 

I used it to get iTunes on big sur to manage my iPhone and it worked perfectly.

you guys rock!

**Comment by cormiertyshawn895** [comment]
Thank you for sharing your appreciation! ❤️
