### ISSUE TITLE
iTunes 12.8

### ISSUE THREAD

**Issue by SwissmonBeat** [cormiertyshawn895/Retroactive#194]
Heyo !

I know there are still some issues with the iTunes 12.9.5 with retroactive on M1 mac Big sur (I tried myself some codesign but nothing worked).

As always, I'm definitly enjoying the app!

However, may I ask you the possibility to upload the iTunes 12.8 on retroactive ? It would be a life saver because all my playlist are on the iTunes 12.8! I had lot of issue trying to port iTunes 12.9.5 on my new M1 mac on Big sur, however, maybe iTunes 12.8 would be the solution.

Thanks again for your work, I'm really looking forward for new update!

Take care,

Swiss mon Beat

**Comment by everybodies** [comment]
would also love 12.8.2 or 12.8.3 
but then again, it might be a ton of work to do it

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
