### ISSUE TITLE
Logic 9 on Mojave

### ISSUE THREAD

**Issue by dster415** [cormiertyshawn895/Retroactive#195]
I downloaded Logic 9.1.8 on Mac using Mojave. After running Retroactive I get message that I can use Logic 9 now but the green launch button doesn't work.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
