### ISSUE TITLE
M1 Big Sur - Cannot download from iTunes Store

### ISSUE THREAD

**Issue by brownieboy** [cormiertyshawn895/Retroactive#196]
Tried several versions of iTunes on my M1 Macbook Pro, but cannot properly access the iTunes store with any of them.   Different probs for different versions:

* iTunes 12.9.5.  Total non-starter.  It crashes immediately upon launch.  Others have reported this already
* iTunes 12.6.5.  I can launch and log into the iTunes Store.  I can browse the iTunes Store but only for Apple Music.   Switching to Podcasts gives a blank screen.  I cannot search the iTunes store either.  I get lots of "Item not available" error dialogs, and searching will result in blank screen.  No search results.
* iTunes 11.4.  I can browse and search the iTunes Store, including Podcasts, but I cannot log into the Store so cannot download anything.   Logging in requires 2FA and I don't think this version works with 2FA.   It never shows me the dialog into which I can enter the 6 digit 2FA code.   Instead, it keeps prompting me for my Apple password, which it tells me is wrong, even though it was good enough to trigger the 2FA code pop-up when I entered it previously.   Oh, and there's no way of turning off 2FA on Apple devices any more - not recent ones, anyway.
* iTunes 10.7.  Hangs upon creating a new library.  I suspect I'd run into same problem as 11.4 even if I could get past this step.

I even tried installing 11.4 over the top of 12.6.5, hoping that the former would pick up the latter's iTunes Store login, but it didn't.

Has anybody got further than this on M1?

**Comment by brownieboy** [comment]
Okay, the workaround for logging into iTunes 11.4, and for any other apps/devices that don't show the 2FA dialog, is to append the 6 digit 2FA code onto your password when asked for it the second time.

**Comment by iosbloomy** [comment]
![Screenshot 2021-03-18 at 09 42 08](https://user-images.githubusercontent.com/50141934/111605466-3d83e980-87ce-11eb-8733-6dd2f204419c.png)

Hi, I'm trying to run itunes so I can software that will help get out of an apple boot loop, the software works fine but is asking for itunes to be running in the background, which right now I can't do. 

Any advise?

Thanks SB

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
