### ISSUE TITLE
TuneSpan integration in iTunes does not work

### ISSUE THREAD

**Issue by pucicu** [cormiertyshawn895/Retroactive#197]
Hello,
I could successfully reinstall iTunes 12.9.5.5 on BigSur. However, the TuneSpan integration does not work. TuneSpan requires a “security settings/ automation” settings in the system settings, but this setting does not appear there. The developer of TuneSpan said that this problem might be solvable by Retroactive. Any idea what the reason could be and how to solve this? Thanks!
Best wishes!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
