### ISSUE TITLE
Cinema tool not working

### ISSUE THREAD

**Issue by samitjagnade** [cormiertyshawn895/Retroactive#198]
Thanks for sharing the Final Cut Pro 7 installation process on macOS Mojave. But in that, we are unable to play FCP MOV files from  Cinema Tool software. From this software, we can able to convert the file in different frame rates and play the files directly. 
So kindly help us to resolve this issue.

**Comment by samitjagnade** [comment]
> Thanks for sharing the Final Cut Pro 7 installation process on macOS Mojave. But in that, we are unable to play FCP MOV files from Cinema Tool software. From this software, we can able to convert the file in different frame rates and play the files directly.
> So kindly help us to resolve this issue.

Hi,
Could you please help me with this issue?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
