### ISSUE TITLE
retroactive no longer opens iphoto on my mac with Big Sur after previously working just fine

### ISSUE THREAD

**Issue by DeGusta1942** [cormiertyshawn895/Retroactive#199]
IPhoto will not open and crashes with every attempt.  I loved that Retroactive so easily enabled me to keep using iPhoto.

Having used the wonderful Retroactive, iPhoto worked great with Big Sur on my iMac until I recently tried to use it.  So I rebooted, ran Retroactive 1.9 several times, and got the same result.  It starts up briefly with the multicolored beach ball spinning and then crashes.  Previously, when iPhoto was working, it would start up, the beach ball would spin, but the “regular” cursor would show up and spin as well, and then iPhoto would open and work just fine. 

I am very frustrated and I appreciate any help you can provide.
Thank you.

**Comment by walterrowe** [comment]
Probably due to updates that break OpenCL as reported in another issue. It was only a matter of time before macOS would get an update that breaks Retroactive (possibly permanently).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
