### ISSUE TITLE
Aperture M1 Fresh OS/App Install Error

### ISSUE THREAD

**Issue by bleckett** [cormiertyshawn895/Retroactive#200]
Hi - not sure if you're aware fo this or not, but I was not successful in running Aperture.
Basically the setup is as follows...

New Mac mini M1
Installed Aperture 3 (from iTunes) - but did to try to open
Downloaded and ran Retroactive
After completion, said to open Aperture.
Closed App
When to small aperture test library
Double-click to open
Received error (see part f it below).

Not sure if it is a signature issue, missing/wrong location file error, or permissions error (ie, there was not warning about needed access to a folder). But thought I would post this to see if it would help.

Big Sur 11.2.1 (most recent update)
Mac mini (M1, 2020)
Memory 16GB
Aperture 3.6

Thank you.

```
Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/PluginManager.framework/Versions/B/PluginManager
  Referenced from: /Applications/Aperture.app/Contents/MacOS/Aperture
  Reason: no suitable image found.  Did find:
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager: code signature invalid for '/Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager'

	/Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager: code signature invalid for '/Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager'

	/Applications/Aperture.app/Contents/MacOS/../Frameworks/PluginManager.framework/Versions/B/PluginManager: stat() failed with errno=1
```

**Comment by cormiertyshawn895** [comment]
This be fixed in Retroactive 1.9 and later. Can you download [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases) and try again?
