### ISSUE TITLE
Movie Files not uploading to iPhoto anymore.

### ISSUE THREAD

**Issue by Gusman1966** [cormiertyshawn895/Retroactive#202]
Hi all
Can anyone help with new issue?
I got retroactive to be able to use iPhoto with Big Sur. At first all was good. I uploaded a folder of pics and movies to iPhoto and as explained in the instructions movies won't play. But the thumbnail was there and that is all I needed. All worked well as long as I didn't accidentally double click on a movie file as this caused it to crash. 
I manage to process two folders of pics and movies. Then recently I uploaded another folder and all the movie files won't upload at all, an error message appears saying 'The following file could not be imported. The file is in an unrecognised format.' 
It doesn't matter what type of movie file I try the same thing happens.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
