### ISSUE TITLE
No Refreshing of New Podcast Episodes in Retroactive iTunes 12.9.5.5 on Catalina

### ISSUE THREAD

**Issue by ThisGitHubUserName** [cormiertyshawn895/Retroactive#203]
I am delighted to have access to iTunes again, but whereas it has all of my episodes (either downloaded or listed as available) that were in the system prior to downloading and installing it, it isn't loading any new ones. That is, it's not just that they won't download, but that nothing even pops up in the file to let me download it if I wanted to.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
