### ISSUE TITLE
iWork '09

### ISSUE THREAD

**Issue by PeggyD1001** [cormiertyshawn895/Retroactive#204]
Is there any possibility of getting iWork '09 to run in Big Sur?

**Comment by TheOnlineUser** [comment]
@PeggyD1001  I second this request. I rely on iWork '09 extensively.

**Comment by cormiertyshawn895** [comment]
iWork’09 is 32-bit, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.
