### ISSUE TITLE
iTunes 10.7 on Big Sur 11.2.2 - D&D to Finder broken

### ISSUE THREAD

**Issue by autli** [cormiertyshawn895/Retroactive#205]
Drag and Drop from iTunes to Desktop or Finder was a very useful function I used for copying tracks. Now this don't works anymore. Now a prohibition sign appears on the mouse arrow. A conflict with access rights? Thanks.
(BTW: On Catalina D&D from iTunes still works!)
Edit: This issue doesn't affect iTunes 12.9.5 - but I need to work with **iTunes 10.7**! Any help?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
