### ISSUE TITLE
iTunes icon greyed out after opening 1.9 in Mohave-so can't load iTunes.

### ISSUE THREAD

**Issue by WilliamDu1** [cormiertyshawn895/Retroactive#207]
Unable to determine if I can reload iTunes after upgrading to Catalina.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
