### ISSUE TITLE
Aperture on Apple Silicon - Previews disappear

### ISSUE THREAD

**Issue by alasdairscott** [cormiertyshawn895/Retroactive#208]
Aperture works fine on Apple Silicon but we've noticed that the image previews immediately become "black" when they're scrolled off the screen and then don't refresh when scrolled back.

It's a large library - 120k images.  

Any ideas?

**Comment by cladi1961** [comment]
I have the same issue. Came after I updated to Catalina 10.15.7 on an iMac 2012. Trying to update the library, but no go.

**Comment by alasdairscott** [comment]
1. Open Aperture and export small selection of photos to a new Aperture Library.
2. Import this Aperture Library into Light Room Classic [using Aperture Importer PlugIn]

**Error: Failed to obtain Image Version Information from Aperture Library**

So, something going a bit odd here ...

**Comment by ih8quark** [comment]
I have read elsewhere that hitting the tab key instead of scrolling works. Im still dealing with unsupported file format after reprocessing many times!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
