### ISSUE TITLE
Add iTunes 12.4.3

### ISSUE THREAD

**Issue by marcusminus** [cormiertyshawn895/Retroactive#21]
This is the last version with color songs list.
![iTunes-12 4-830x554](https://user-images.githubusercontent.com/35492419/68658181-b9ec2580-0513-11ea-9feb-b2d9bb008d0a.png)

**Comment by Grafovich** [comment]
Yes, pleeease. I want it too. This is the last ver of iTunes that i love.

**Comment by cormiertyshawn895** [comment]
No doubt, iTunes 12.4.3 visually looks pretty cool.

Getting iTunes 12.4.3 to work is challenging. In particular, signing into iTunes accounts doesn't work quite right with iTunes 12.4.3 on macOS Catalina, but I will keep you posted if there's any development.

([The latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases) supports installing iTunes 11.4, which spots a similar album view with colored background.)

**Comment by ShikiSuen** [comment]
@cormiertyshawn895 
The background coloring of iTunes 11.4 is comparatively worse than iTunes 12.4.x regarding how to choose colors for backgrounds & foreground texts.

**Comment by YiNicer** [comment]
Yes,please.....  
This version of iTunes is the reason I use this software.
Waiting for your good news.
love you

**Comment by AegeanNet** [comment]
Would love 12.4.3.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
