### ISSUE TITLE
Getting 'This iPhone is in use by another user on this Mac' in iTunes 12.9.5.5

### ISSUE THREAD

**Issue by prolly51** [cormiertyshawn895/Retroactive#210]
I've used Retroactive 1.9 to install iTunes 12.9.5.5 on a new Mac mini running macOS Catalina. I have encountered the situation you mention under 'Syncing with a device': I launch iTunes and then connect my iPhone SE 2020. The iPhone and its playlists show up in iTunes and I get a notification in the upper right of the monitor that says this:

"iPhone in Use
This iPhone is in use by another user on
this Mac."

(My account is the only account on that Mac.)

I have removed the attached iPhone and run this command in Terminal:

killall AMPDevicesAgent

I plug the iPhone back in, and I get the same notification. Ideas?

Thank you!

**Comment by INCANDENZAS** [comment]
I was also encountering this issue, not sure what to do about it :/

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
