### ISSUE TITLE
Locked up on unlocking iTunes

### ISSUE THREAD

**Issue by cgillesb** [cormiertyshawn895/Retroactive#211]
I'm stuck on the full disk access screen, and I've done what was required. If I try to quit, I get the message that retroactive is still unlocking iTunes, and I'll get a corrupted file if I quit. I need to clear up some working memory for an afternoon class. HELP!
<img width="2048" alt="Screen Shot 2021-03-23 at 7 24 16 AM" src="https://user-images.githubusercontent.com/81245682/112162080-f2d8e780-8ba8-11eb-84fa-fff54e22b10c.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
