### ISSUE TITLE
Just bought M1 MacBook Air and downloaded/installed Retroactive 1.9, but iTunes does not run

### ISSUE THREAD

**Issue by hirokoby** [cormiertyshawn895/Retroactive#212]
I tried several times to install & reinstall on my M1 MacBook Air with new Big Sur OS but I cannot run iTunes.

I get the following error message and appreciate anyone who can help me resolve this issue as I hate the new Apple format of using different apps (Music, Podcast, TV) instead of iTunes, which handled all these under one app.

Thank you

-------------------------------------------

Process:               iTunes [11364]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        ??? [11361]
User ID:               501

Date/Time:             2021-03-24 16:52:50.309 +0900
OS Version:            macOS 11.2.2 (20D80)
Report Version:        12
Anonymous UUID:        9D2DBC1D-3142-D3FA-08A5-0FC78382562E

Sleep/Wake UUID:       A310A48E-6B01-4889-8B69-8868540F4708

Time Awake Since Boot: 22000 seconds
Time Since Wake:       7800 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000030ba40ab0   pc: 0x00007ffdffc4dc0c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 20401
    thread_create: 0
    thread_set_state: 0

Model: MacBookAir10,1, BootROM 6723.81.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Dec 31 2020 21:39:03 version 18.20.222.20.7.8.104 FWID 01-1b2645bc
Bluetooth: Version 8.0.3d9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: iPhone, Ethernet, en5
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: iPhone
USB Device: USB Storage
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by clayton-grey** [comment]
This is the same code signing error found here:

https://github.com/cormiertyshawn895/Retroactive/issues/187

Might want to delete this and add your voice there.

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.
