### ISSUE TITLE
Request: add QuickTime Pro 7 to the list

### ISSUE THREAD

**Issue by mizzenman** [cormiertyshawn895/Retroactive#213]
This is fabulous work.  The 1 remaining application in dire need of making an appearance is the old QuickTime Pro 7 app, EOL’d in Mojave.

...because there’s no other application that lets you cleanly slice and splice movie (h.264, etc) files up and re-save them again without having to re-encode them and lose more image quality.  Since Apple didn’t bother to include this in the new QT, we’re all now stuck saving gigantic files just for short clips or losing quality.  The other two alternatives on the market both have big crashy ui problemos.  Halp ussss, :)

**Comment by cormiertyshawn895** [comment]
QuickTime 7 is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.

With that said, you can install macOS Mojave or Windows 11 in a virtual machine with Parallels Desktop, VMware Fusion, Virtualbox, or UTM, and install QuickTime 7 there. You can also install QuickTime 7 with Crossover.

**Comment by mizzenman** [comment]
Ohhhh didn’t realize it was a 32bit thing. That makes sense.  Thanks for the reply though, and thank you so much for taking the time to make Retroactive!  Brilliant work, Pete

On Sep 1, 2022, at 11:56 PM, Tyshawn Cormier ***@***.***> wrote:

﻿

QuickTime 7 is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.

With that said, you can install macOS Mojave or Windows 11 in a virtual machine with Parallels Desktop, VMware Fusion, Virtualbox, or UTM, and install QuickTime 7 there. You can also install QuickTime 7 with Crossover.
