### ISSUE TITLE
iPhoto: PDF of books created with iPhoto cannot be odered via Mimeo because of Producer metadata

### ISSUE THREAD

**Issue by OmbraRD** [cormiertyshawn895/Retroactive#215]
When creating a book in iPhoto (right click on the book, save as PDF option) the generated PDF has the Producer field filled with the version of macOS being used. This PDF cannot be imported into the website https://import.mimeophotos.com/ for ordering spitting out a verification error as follows:

![image](https://user-images.githubusercontent.com/64612056/113620908-f0ef3980-9628-11eb-86aa-482098a2da7d.png)

If the field is replaced using a third party tool, it works flawlesly.

Here is an example of a working field:

`<pdf:Producer>Mac OS X 10.11.6 Quartz PDFContext</pdf:Producer>`

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
