### ISSUE TITLE
Logic Pro 9 under Mojave running in 32 bit  

### ISSUE THREAD

**Issue by cyberishh** [cormiertyshawn895/Retroactive#216]
would this somehow be doable? - Under Mojave I can't selecht the 32bit boot option to run Logic Pro 9. - would be a blast (from the past), thx for your efforts!!!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
