### ISSUE TITLE
Storage incongruancy when installing iTunes 12.9.5

### ISSUE THREAD

**Issue by INCANDENZAS** [cormiertyshawn895/Retroactive#221]
Hi there, 
I had been running iTunes 12.9.5 until recently when it seems to have caused my Mac Book Pro to crash, and when I restarted my laptop, the app wouldn't open. I deleted the app, then tried using Retroactive to re-install it like I had when I initially installed iTunes. However I'm encountering an issue when it continually says that my storage capacity is always within 1-4 GBs of 20GB, the requisite free space for installing iTunes 12.95, even though my computer says I have at least 40GBs of storage available. I was wondering if you had any idea how to remedy this issue. 
Thanks!
<img width="1010" alt="Screen Shot 2021-04-28 at 11 07 37 AM" src="https://user-images.githubusercontent.com/4999561/116451941-fdbf1180-a811-11eb-8375-57dc4913394f.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
