### ISSUE TITLE
Could this be used to run Preview 9 from High Sierra on Big Sur 

### ISSUE THREAD

**Issue by risner** [cormiertyshawn895/Retroactive#222]
I noticed you forked the GitHub of preview 9 binary and made it work again in Catalina. Could that work on Big Sur?

could it work with Rosetta on M1 macs?

**Comment by Baldhal** [comment]
Preview.app 9.0 doesn't work since Big Sur. I tried to fix it [here](https://github.com/cormiertyshawn895/Retroactive/issues/173) but I'm afraid Tyshawn Cormier is the only person skilled enough to fix it.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
