### ISSUE TITLE
iTunes does not see iPod shuffle nano

### ISSUE THREAD

**Issue by fabulousrice** [cormiertyshawn895/Retroactive#223]
Even after a couple of different installs of iTunes and restarting/unplugging/replugging.

**Comment by MacMuser** [comment]
I'm having the problem of my iPod not appearing in iTunes BUT I have solved the installation issue whyen you try to get full disk access. As you go through the process when installing iTunes/Retroactive it opens the SystemPreference Security and Privacy Full Disk Access window and this is where you get stopped. A little icon appears and says Drag Me or words to that effect. It means to actually drag the little icon to the window on the right. Retroactive will put up a screen with fireworks and you have it fully installed.

But I still can't get my old iPod to mount.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
