### ISSUE TITLE
Itunes to ipod Classic not transferring

### ISSUE THREAD

**Issue by PuncherD** [cormiertyshawn895/Retroactive#225]
Itunes does recognize my ipod classic, I can see the songs on the ipod, but I can't transfer anything to it.  Nothing happens...no error messages or attempt to sync.  I was able to import songs to itunes from computer or store cloud, but not even from ipod.  I just want to be able to put a few songs onto the ipod.  There is a a program called Waltr that works, but activation is $50, and it only does that one thing.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
