### ISSUE TITLE
Aperture Broken on Latest Catalina 

### ISSUE THREAD

**Issue by AlexMorello** [cormiertyshawn895/Retroactive#226]
Hey-up, folks! Been using a patched Aperture (Retroactive) for quite a while. Following the most recent update, it just won't work properly anymore, with the images either disappearing when double-clicked, or having coloured lines all over them. Anyone run into a similar issue?

**Comment by walterdavis** [comment]
Yup, there's an extensive thread about this problem here: https://github.com/cormiertyshawn895/Retroactive/issues/220

**Comment by AlexMorello** [comment]
> Yup, there's an extensive thread about this problem here: #220

Thanks!

**Comment by cormiertyshawn895** [comment]
This has been fixed in [Security Update 2022-005 Catalina](https://support.apple.com/kb/HT213343). 

If you are experiencing this issue, open System Preferences > Software Update > More Information..., and install the latest macOS Catalina security update.
