### ISSUE TITLE
iTunes playing wrong song

### ISSUE THREAD

**Issue by agusventu** [cormiertyshawn895/Retroactive#228]
This is my first time I am writing in an online community, so I hope I can express clearly my issue.

I installed iTunes from retroactive 1.9 and it lunches great!

I only have a small issue:
While working inside a playlist or the full "songs" library...
I select a track either with the arrows or by clicking on it and when I hit enter or click again to play... the selection jumps to another track (from the ones I have below) and starts playing that one instead.
I found that if I hit enter again, then it comes to play the desired track.

For instance in the attached picture, I hit enter on the second track and it started playing the 8th one.

<img width="631" alt="Screen Shot 2021-05-26 at 12 03 06 PM" src="https://user-images.githubusercontent.com/84859732/119683914-749ff800-be1a-11eb-8f1f-9726704ecb33.png">

Does anyone have this issue as well? any guess how could I solve it?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
