### ISSUE TITLE
add new music from CD to iTunes on Catalina

### ISSUE THREAD

**Issue by riahasselt** [cormiertyshawn895/Retroactive#23]
When I open iTunes and try to rip a new CD, the Catalina Music app opens itself and rips the CD.  The new songs can't be found in iTunes, I can only see them in the Music App.  When I open iTunes again and try 'Add to Library'  it starts to import in iTunes but then I get error code 54

**Comment by tghuguenin** [comment]
iTunes does not detect audio CD for me: Music app is not automatically executing when I insert CD. This is good and how I want my computer to run, whether it be Music or iTunes. CD mounts to computer no problem. I start iTunes, does not detect CD. I open the CD in Finder, select all music files, Open With>iTunes. iTunes will start but will not load the files.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
