### ISSUE TITLE
My "trash" folder can't be emptied!  

### ISSUE THREAD

**Issue by CubbyCam** [cormiertyshawn895/Retroactive#230]
Love "Retroactive" and it's the answer I've been waiting for so I finally was able to upgrade to the latest operating systems on my Mac.  I've been super happy using iPhoto again with one big problem.  Photos I delete go into the trash folder, but the trash folder can't be emptied... individual photos in the trash folder can't be deleted from there either.  HELP!  I'm rapidly filling up my hard drive with dross!  LOL.  Seriously though... it's the one remaining issue that's causing me no end of grief and concern.  Can you do anything to help?  

Cam McCubbin

**Comment by RedTartan04** [comment]
It works for me.
Did you try to select the trash and then choose the menu item iPhoto/empty thrash? Or use the keyboard shift-cmd-backspace?

**Comment by CubbyCam** [comment]
Thanks for the reply but in the interim, I’ve finally moved on to “Photos” and you know what? I’m lIving it. Lol
