### ISSUE TITLE
iTunes not able to read contents of iPhone 8

### ISSUE THREAD

**Issue by grokinhudsie** [cormiertyshawn895/Retroactive#231]
I just installed Retroactive and iTunes 12.6 because I want the ringtone support for my iPhone. But iTunes pops a window that says this: (see picture)Then it says I can restore the phone (factory reset) to try to fix the issue. No way I'm doing that. 

<img width="683" alt="Screen Shot 2021-06-22 at 6 03 23 PM" src="https://user-images.githubusercontent.com/86329392/123010535-69da7380-d384-11eb-9db9-8f1e159a4ab1.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
