### ISSUE TITLE
Itunes quit unexpectedly

### ISSUE THREAD

**Issue by Loisdcruz** [cormiertyshawn895/Retroactive#234]
I can't even open iTunes. it shows iTunes quit unexpectedly then codes. I don't know how this works. pls help

**Comment by GazzMat** [comment]
I'm having the same issue.

**Comment by PTechHD** [comment]
I posted this same issue a day before you did. did you happen to fix it on your machine?

**Comment by geekeasy** [comment]
Same problem too.  

M1 Macbook Air.

macOS 11.6

**Comment by clauditorium** [comment]
Same problem. M1 Mac Mini. I don't know how to read the problem report, but this line seemed relevant: "Termination Reason:    Namespace CODESIGNING, Code 0x1"

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.
