### ISSUE TITLE
Final Cut 7 on Catalina

### ISSUE THREAD

**Issue by ioluisv** [cormiertyshawn895/Retroactive#235]
Wondering if they'll be any support for Final Cut 7 on Catalina ? 

Thank you so much!  

Love what create and giving me some hope !

**Comment by lillycham** [comment]
As far as I understand, this isn't technically possible without virtualisation or similar, since Final Cut Pro 7 was a 32 bit application only.

**Comment by cormiertyshawn895** [comment]
Like @lillycat332 said, Final Cut Pro 7 is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.
