### ISSUE TITLE
iTunes does not open in the assigned Desktop.

### ISSUE THREAD

**Issue by don-911** [cormiertyshawn895/Retroactive#236]
iTunes 12.9.5 is assigned to open in space/desktop #7 on macOS 11.5 (I'm using 9 spaces in Mission Control). However, it does not and instead only opens in the currently active space. All other apps open in their assigned spaces. I suspect this is a bug and it would be great if it could be fixed. Thanks!

![Screen Shot 2021-07-31 at 10 15 48 AM](https://user-images.githubusercontent.com/71158735/127747715-dd492a94-b75a-4b32-a191-4b659a8b2e8e.png)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
