### ISSUE TITLE
iTunes can't play items in library

### ISSUE THREAD

**Issue by fergo79** [cormiertyshawn895/Retroactive#237]
I can't play any of the video items in my iTunes library - I think it may be because I'm unable to sign in to the store. Any suggestions? Music tracks will play...

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
