### ISSUE TITLE
iPhoto randomly quit @lauch on during use on bigger 11.5.1

### ISSUE THREAD

**Issue by Tetonne** [cormiertyshawn895/Retroactive#238]
/Applications/iPhoto.app/Contents/MacOS/iPhoto ; exit;
objc[1464]: **Class NSFlippableView is implemented in both /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (0x7fff80030000) and /Applications/iPhoto.app/Contents/Frameworks/AppKit.framework/Versions/C/AppKit (0x10e3991b8). One of the two will be used. Which one is undefined.**
objc[1464]: **Class NSToolbarClippedItemsIndicator is implemented in both /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (0x7fff80033b88) and /Applications/iPhoto.app/Contents/Frameworks/AppKit.framework/Versions/C/AppKit (0x10e399208). One of the two will be used. Which one is undefined.**
objc[1464]: **Class PFSandboxEnvironment is implemented in both /System/Library/PrivateFrameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x7fff8033c720) and /Applications/iPhoto.app/Contents/Frameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x10de61f88). One of the two will be used. Which one is undefined.**
objc[1464]: Class PFISO6709Parser is implemented in both /System/Library/PrivateFrameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x7fff81cc0bf0) and /Applications/iPhoto.app/Contents/Frameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x10de620a0). One of the two will be used. Which one is undefined.
objc[1464]: Class PFUtilities is implemented in both /System/Library/PrivateFrameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x7fff8033d5f8) and /Applications/iPhoto.app/Contents/Frameworks/PhotoFoundation.framework/Versions/A/PhotoFoundation (0x10de620c8). One of the two will be used. Which one is undefined.
2021-08-08 08:17:06.126 iPhoto[1464:18017] *** WARNING: Textured window <IWWindow: 0x7faf3c4a9ee0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
