### ISSUE TITLE
Retroactive Ver 1.9

### ISSUE THREAD

**Issue by BarryfWilliams** [cormiertyshawn895/Retroactive#239]
I have been using itunes thanks to retroactive i recently purchased a mac mini with a m1 chip unfortunately when i lauch itunes i get this error

rocess:               iTunes [94338]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        ??? [94333]
User ID:               501

Date/Time:             2021-08-16 11:56:03.765 +1000
OS Version:            macOS 11.5.1 (20G80)
Report Version:        12
Anonymous UUID:        EE018FB1-0A6A-2CD9-C642-83C284844953

**Comment by vglavina** [comment]
I, too, am hoping that Shawn will be able to create a version of Retroactive for my new M1 chip-enabled MacBook Pro! I'm almost regretting this purchase, if I can't get Shawn's Retroactive program! Any chance there will be a version of Retroactive for the new M1 chips??????

Thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
