### ISSUE TITLE
Aperture crashes when exiting full screen

### ISSUE THREAD

**Issue by suird** [cormiertyshawn895/Retroactive#24]
Exiting full screen while in Viewer causes Aperture to crash. I think this only happens after you view a photo that has been edited.

**Comment by yklose** [comment]
Same Problem, try exiting full screen mode with esc key. For me it worked even after a photo has been edited.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
