### ISSUE TITLE
Logic Pro 9 Catalina

### ISSUE THREAD

**Issue by St-Hk** [cormiertyshawn895/Retroactive#241]
Hello,
If i'm correct, your project enables to use Logic Pro 9 on Mojave and High Sierra only.
Is there a plan to make it work on Catalina too?
Thank you

**Comment by walterdavis** [comment]
Have a look in Finder / About this Mac / System Report (on the Software / Applications pane), and see if it is 32-bit or 64. If the former, then Mojave is as high as you can ever go with it, as that was the last Mac OS that would run 32-bit applications.

**Comment by St-Hk** [comment]
Hi walterdavis. It's a 64bit app (which has the option to be open in 32bit mode for those who need it). So technically it should work on Catalina. But even if it's 64bit I read we cant install it as they just dropped it (/ blocked it?) since they are now on Logic Pro 10 (X). I think it's just a matter of a few plist modifications etc... like Retroactive does.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
