### ISSUE TITLE
Cannot add new music to iTunes

### ISSUE THREAD

**Issue by thulelohe** [cormiertyshawn895/Retroactive#242]
![Screenshot 2021-09-15 at 18 55 39](https://user-images.githubusercontent.com/90785891/133467766-b2a27895-711e-44e4-84d0-e543446e4a03.png)

And I have to download new podcast episodes manually, although subscribtion is active.

**Comment by cormiertyshawn895** [comment]
If the open dialog doesn’t work, try to drag and drop your music files into iTunes.
