### ISSUE TITLE
Itunes 11.4 search and up next list edges can be fixed?

### ISSUE THREAD

**Issue by imloualvaro** [cormiertyshawn895/Retroactive#243]
Im running iTunes 11.4 and Big Sur 11.5.2. Outer edge transparency can be fixed somehow?

<img width="353" alt="Screen Shot 2021-09-18 at 12 26 56 AM" src="https://user-images.githubusercontent.com/17622363/133871075-e7962dd7-087d-4b12-ba0d-4e3d861e3cc3.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
