### ISSUE TITLE
Aperture on Big Sur 11.6

### ISSUE THREAD

**Issue by AlexMorello** [cormiertyshawn895/Retroactive#244]
Does anyone know if the app still works after the update?

**Comment by jb59** [comment]
Aperture still working for me on 11.6 (5k iMac late 2015) - same issues as on 11.5, namely image thumbnail refresh, loupe appears completely transparent (but still functions), occasional crash. Still very happy it works at all!

**Comment by vgritsenko** [comment]
Same here, Aperture is mostly working on 11.6. In addition to the above I saw an issue with `photostream-agent` repeatedly launching and crashing - fixed it as described here:

https://blog.reverycodes.com/archives/000057.html

**Comment by cormiertyshawn895** [comment]
Aperture works on macOS Big Sur 11.6.

**Comment by vgritsenko** [comment]
... and it still launches on macOS Monterey 12.5.1, too. 🎉
