### ISSUE TITLE
Retroactive to run Soundtrack Pro 3.01 on Mojave?!?

### ISSUE THREAD

**Issue by cyberishh** [cormiertyshawn895/Retroactive#245]
Hi there!

first of all thank you very much for sharing Retroactive to the people!
I  would like to run Soundtrack Pro 3.01 on Mojave. Can you make that possible ?

best regards
Raphael

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
