### ISSUE TITLE
Can't select 10.7?

### ISSUE THREAD

**Issue by Shad0wSeven** [cormiertyshawn895/Retroactive#246]
I was on Big Sur (I have a normal mouse) and I coulndn't find any way to select 10.7,

I can select 11.4 (can't scroll or see the version), but can't even see, scroll too in any way select version that's hidden on my screen. 

Am I dumb or is there a way to do this?

![image](https://user-images.githubusercontent.com/19739712/136147976-2163810f-b1bc-44fd-a803-7653a4b81a2d.png)

**Comment by Shad0wSeven** [comment]
I ended up just downloading the sourcecode and recompiling to always download 10.7, but im leaving this as an issue, since I could find no way to do it without that :(

**Comment by cormiertyshawn895** [comment]
With any third party mouse, you can hold down the shift key on your keyboard, then scroll vertically with the scroll wheel to simulate a horizontal swipe.
