### ISSUE TITLE
Does this work on an intel Mac with Monterey?

### ISSUE THREAD

**Issue by benmullyuk** [cormiertyshawn895/Retroactive#248]
Don't want to mess up my install, so was wondering if this is still being updated or works with Monterey on an Intel Mac?

**Comment by jb59** [comment]
Same question here! Now only have 1 Mac that's Monterey capable (2013 MacBook Air too old) so don't want to screw up my functioning Aperture, iPhoto and iTunes on iMac. Will give it a few days, if no-one else has tried it, I'll give it a go!!

**Comment by ehalp** [comment]
I just updated to Monterey, iTunes is still able to sync with my devices and it seems to work without any problems. I only have iTunes installed, so not sure about iPhoto or Aperture.

**Comment by benmullyuk** [comment]
OK took the plunge too after ehalp! Had an Intel Mac running Big Sur with iTunes already installed via Retroactive, upgraded to Monterey 12.0.1 no problem, iTunes still works. The only think I had to do was run the below command in Terminal to get my phone syncing with iTunes again - sudo killall AMPDevicesAgent

Still be interested to know if a clean install of Monterey works with Retroactive though!

**Comment by Andres-Brito** [comment]
> OK took the plunge too after ehalp! Had an Intel Mac running Big Sur with iTunes already installed via Retroactive, upgraded to Monterey 12.0.1 no problem, iTunes still works. The only think I had to do was run the below command in Terminal to get my phone syncing with iTunes again - sudo killall AMPDevicesAgent
> 
> Still be interested to know if a clean install of Monterey works with Retroactive though!

I support the suggestion! We need Retroactive 2.0 to run with Monterey because 10 times I pone iTunes to sync with my iPod Classic 120, 8 fails.

Anyway, I say again Retroactive is a jewel and I love it!

**Comment by Marekai** [comment]
Aperture works but it does not show RAW files at least for me and some other users.

**Comment by Yogavenger** [comment]
Aperture runs but no longer works with RAW files (as above). i.e. you can import files but they will not display.

**Comment by PeggyMargo** [comment]
> Aperture runs but no longer works with RAW files (as above). i.e. you can import files but they will not display.

To confirm:  My GitHub Aperture will work if I upgrade to Monterey?  Currently running Big Sur 11.4.  It currently works great.  Sometimes crashes, but overall I'm happy.  (I don't use RAW files.)

**Comment by PeggyMargo** [comment]
I'd like to buy a new iMac & give my current one to my daughter, but have been hesitant due to wanting Aperture. It's Jan 2022.  Thanks.

**Comment by hseverac** [comment]
Any update on Aperture and Raw files ?
There has been some reports that Aperture does not work anymore on Raw files under Monterey, but maybe it is because the raw files used are not supported by Apple ? Or because they are too recent. What about legacy raw files ?

**Comment by phriedrich** [comment]
@hseverac 

On Monterey also older (previously supported) RAW files won't work correctly anymore.
Previews/thumbnails are still there, but opening an image will often trash that and then it can't render a new preview.

**Comment by hseverac** [comment]
Oh, that's bad, thanks for the update.

**Comment by hseverac** [comment]
Just thinking...
If you set Aperture to "use JPG as original", I suppose that will let it preview the Jpg in case of a JPG+Raw pair , which may be a dirty hack for selecting purposes. Obviously not for editing.

**Comment by cormiertyshawn895** [comment]
As folks discussed above, Retroactive works on macOS Monterey, with the exception of working with RAW images in Aperture.

**Comment by roaster42** [comment]
Retroactive worked exactly as described by the creator.  Unzipped 2.0 and it loaded on my OSX 12.6.7 Monterey.  iTunes loaded and worked as it had previously and even had some 'clearer' tabs.  I organized my new music files as I wanted and even added a few new ringtones.  Very pleased and recommend the creator of the program.
