### ISSUE TITLE
iTunes 12.9.5 - cannot sync photos from iPhoto to iPhone/iPad

### ISSUE THREAD

**Issue by jb59** [cormiertyshawn895/Retroactive#25]
iTunes 12.9.5 sees iPhone, but in Photo syncing option "sync photos from" dropdown box, only Photos appears as an option. In Mojave, options were Photos, iPhoto or Aperture. Suspect this may be system level issue?

**Comment by slissone** [comment]
I had this problem. The solution is to quit iTunes, delete the "iPod Photo Cache" in your chosen photos folder. And the one inside your Photos Library folder. For the second one, you have to right-click on the Photos Library item and click "Show Package Contents". Inside is another "iPod Photo Cache" folder - delete that too. THEN open iTunes and deselect your photos folder in the dropdown at the top of the photos iPhone sync area, then reselect your photos folder. Wait a moment - it will then tell you how many photos are inside. Then sync.

If you have problems still, leave your iTunes open and delete just the "iPod Photo Cache" folder that iTunes will have created again, then try and sync. You will need to delete the main "iPod Photo Cache" in your photos folder every time you want to sync photos with iTunes, but this isn't a very common thing that you will need to do so it's not too much of a hassle. Don't worry about the one inside the Photos Library item after you've deleted it the first time, I don't think it reappears again for some reason.

**Comment by pizzaonmychest** [comment]
> I had this problem. The solution is to quit iTunes, delete the "iPod Photo Cache" in your chosen photos folder. And the one inside your Photos Library folder. For the second one, you have to right-click on the Photos Library item and click "Show Package Contents". Inside is another "iPod Photo Cache" folder - delete that too. THEN open iTunes and deselect your photos folder in the dropdown at the top of the photos iPhone sync area, then reselect your photos folder. Wait a moment - it will then tell you how many photos are inside. Then sync.
> 
> If you have problems still, leave your iTunes open and delete just the "iPod Photo Cache" folder that iTunes will have created again, then try and sync. You will need to delete the main "iPod Photo Cache" in your photos folder every time you want to sync photos with iTunes, but this isn't a very common thing that you will need to do so it's not too much of a hassle. Don't worry about the one inside the Photos Library item after you've deleted it the first time, I don't think it reappears again for some reason.

doesn't work.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
