### ISSUE TITLE
Big Sur 11.6.1 - Aperture, iPhoto and iTunes(12.9.5.5)

### ISSUE THREAD

**Issue by jb59** [cormiertyshawn895/Retroactive#250]
#Intel Macbook Air 2013 - just updated to Big Sur 11.6.1 - Aperture, iPhoto and iTunes still working as on 11.6 (similar issues - occasional crash in Aperture and iPhoto, thumbnail refresh and loupe issues in Aperture as before  - iPhoto and Aperture seem a little quicker, iTunes working with iCloud Music library - I don't sync iPad/iPhone via iTunes, so unable to comment on that functionality

**Comment by cormiertyshawn895** [comment]
Thank you for sharing your experience!
