### ISSUE TITLE
iPhoto on Monterey

### ISSUE THREAD

**Issue by doxxxob** [cormiertyshawn895/Retroactive#252]
iPhoto opens on Monterey 12.0.1 correct. But when I try to export or edit pictures iPhoto exits without any warning.

**Comment by outreachav** [comment]
Can't run iPhoto either on Monterey -- would love to be able to.  Any solution to this?

**Comment by cormiertyshawn895** [comment]
Thanks for your report! iPhoto should no longer quit unexpectedly on launch in [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0).
