### ISSUE TITLE
iTunes 10.4.1 – is it possible?

### ISSUE THREAD

**Issue by Snarkasana** [cormiertyshawn895/Retroactive#253]
I still use iTunes 10.4.1, since it is the last version where it's easy to access multiple artwork. Does anyone know if I could install 10.7 with Retroactive, and then swap some of the files within the app itself with the ones from 10.4.1?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
