### ISSUE TITLE
iTunes 12.6.5.3 — Shared library problem

### ISSUE THREAD

**Issue by thenurse** [cormiertyshawn895/Retroactive#254]
I successfully installed iTunes 12.6.5.3 on Big Sur with an M1 chip but now I encountered a problem. The main reason for wanting to use iTunes instead of Music is that I used to share my iTunes library between two computers with the handy Shared Libraries feature, copying a selection of music from my main library to iTunes on my second computer. My older computer is running iTunes 12.8.31 on High Sierra and I can select the library on my newer computer running Big Sur, but it doesn’t open the shared library, it just flashes for a second and closes immediately (the app itself doesn’t crash btw.) After a few tries it always shows this message “The shared library has too many users connected at this time. Please try again later after some user have disconnected.” Any ideas?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
