### ISSUE TITLE
iPhoto, Aperture and iTunes  - Monterey 12.01, Intel iMac 5k

### ISSUE THREAD

**Issue by jb59** [cormiertyshawn895/Retroactive#255]
Ok - hope this is helpful!

iMac 5k, late 2015 running 11.6.1

**STEP 1 - test on external SSD**
Installed Monterey 12.01 on external (bootable) SSD (previously formatted as bootable High Sierra drive, with Aperture installed)
Booted iMac to Monterey SSD.
Ran Retroactive - Aperture selected. (had to locate App, as Retroactive didn't automatically find it)
Aperture runs ok, with same issues as on Big Sur 11.6.1 - Thumbnail refresh, transparent loupe - note that I don't use RAW files, but import, export and edit functions all ok.
Copied iPhoto App from Big Sur HD (drag and drop)
Ran Retroactive - iPhoto selected ( again had to locate app)
iPhoto runs ok - import, export, edit functions all ok, occasional crash
Ran Retroactive - iTunes (12.9.5.5) selected - downloaded, installed, runs ok (Store ok, don't sync with it, so can't comment)
    
 **STEP 2 -  internal HD (Fusion drive)**
Installed Monterey via software update on internal drive, (previously Big Sur 11.6.1 with Aperture, iPhoto and iTunes 12.9.5.5 installed)
Aperture, iPhoto and iTunes all running ok, with same issues as on Big Sur 11.6.1 (did not run Retroactive again)

I'm happy, and again, as so many others have said, thanks Mr Cormier for your amazing app!!!!

**Comment by loosewire505** [comment]
Thank you for posting this @jb59 ! Will give this a try on a friend's machine who's not able to run iPhoto from a previously working Catalina/Retroactive setup. (they relented to the upgrade nags from Apple and upgraded I'm afraid)

**Comment by jb59** [comment]
Recent Monterey 12.1 update - iPhoto, Aperture and iTunes still functioning as above.

**Comment by ylluminate** [comment]
Has anyone reproduced this on Apple Silicon (M1+) via Rosetta 2?

It seems others are still having a crash with this: https://github.com/cormiertyshawn895/Retroactive/issues/149#issuecomment-802341821

**Comment by ylluminate** [comment]
I had an interesting experience here. I migrated an Intel Big Sur installation with iTunes 12.9.5.5 installed and enabled via Retroactive previously. Upon migration (Apple's `Migration Assistant.app`) I found that it STILL works on an Apple Silicon (M1 Max) MacBook Pro with macOS 12.1 (Monterey) fairly well. It doesn't seem to want to connect to iOS devices (with errors), but the old music library is intact and works quite well.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by ylluminate** [comment]
Swinsian 3 (Preview) has been really great as my migration option to keep EVERYTHING intact from iTunes: https://swinsian.com/sparkle_beta/sparklecast.xml

Thanks for keeping things going as long as you did Tyshawn.
