### ISSUE TITLE
iPhoto on Monterey doesn't work

### ISSUE THREAD

**Issue by doxxxob** [cormiertyshawn895/Retroactive#256]

**Comment by doxxxob** [comment]
Please help. It is possible to open iPhoto. But when you edit or export Pictures IPhoto crashes without any warning or so.

**Comment by juancruz85** [comment]
Same issue but I can't open iPhoto at all

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
