### ISSUE TITLE
iTunes 10.7(21) can't add new music to my iPod Classic 120 Gb

### ISSUE THREAD

**Issue by Andres-Brito** [cormiertyshawn895/Retroactive#257]
Running Monterey 12.0.1. It run perfectly until today.

Any suggestion, please? Thank you!

**Comment by don-911** [comment]
Did you solve this? I'm still on Big Sur and have been reluctant to upgrade to Monterey because of iTunes and iPod compatibility questions.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
