### ISSUE TITLE
iPhoto crop option box blank and ejecting camera box option blank

### ISSUE THREAD

**Issue by RonDuprey** [cormiertyshawn895/Retroactive#258]
Trying to get iPhoto to work properly. iPhoto keeps crashing when I select the crop option (gives me a blank option box and then crashes (see screen shot photo). I am also getting a blank option  box when I try to eject my camera. Any help would be great.
<img width="1900" alt="Screen Shot 2021-11-23 at 6 01 46 PM" src="https://user-images.githubusercontent.com/94938461/143144184-b0ee3943-e790-4613-a7fc-661f2f446a97.png">

**Comment by RedTartan04** [comment]
Yes. Unfortunately that's still the case with Retroactive 2.0 :-(
It seems to affect most pop-up menus, e.g. right mouse button on albums.
Where possible I use the menu bar but cropping isn't there.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
