### ISSUE TITLE
iPhoto photobook export crashes

### ISSUE THREAD

**Issue by eniseg1** [cormiertyshawn895/Retroactive#259]
On my M1 Mac mini, the following procedure leads to a crash every time:
- open photobook
- right-click to bring up the "export to PDF" menu
- menu is blank, cannot click on anything
- iPhoto crashes

Thank you so much for making Retroactive! :)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
