### ISSUE TITLE
cannot access hard rive

### ISSUE THREAD

**Issue by iylaA** [cormiertyshawn895/Retroactive#26]
if the phone connects to iTunes, drive cannot be written to, quitting does not work, I need to restart

MacBook Pro 2017
Catalina
iTunes library is on an external drive

**Comment by cormiertyshawn895** [comment]
If iTunes is unable to play media located on an external storage media or network drive:
- Re-install iTunes [using the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/).
- After re-installing iTunes, Retroactive will ask you about iPod syncing. Click "Enable Full Disk Access", and follow on-screen instructions provided by Retroactive. **Enabling Full Disk Access will fix both iPod syncing and music playback on external drives or shared volumes**.

![7a](https://user-images.githubusercontent.com/57056759/75648829-2182c980-5c06-11ea-8ee7-7a8a0eacfd2f.jpg)
