### ISSUE TITLE
Enable full disk access - stuck in loop

### ISSUE THREAD

**Issue by feduo666** [cormiertyshawn895/Retroactive#261]
I click to enable full disk access (I am trying to install itunes), I follow the instructions to unlock the padlock, then it says to drag the app into the list.

Except, the app is already there?? I tried removing it, so I can drag it into the list again. When I do that, it says "Retroactive will not have full disk access until it is quit."

If I click later, nothing happens and I cannot move on to the next step.
If I click quit and reopen, then I get a pop up that says "Unable to quit Retroactive. Retroactive is unlocking iTunes, Quitting will result in a corrupted copy of iTunes"

I don't know how I am supposed to proceed from here.

**Comment by CledsonInoue** [comment]
I'm having the same issue, but for me, I can quit and reopen without warnings.
But the loop continues and I still can't connect iPod Photo with Full Disk Access.
I'm running Big Sur 11.6.3

**Comment by MikeHalesNZ** [comment]
Same here, running 12.2

**Comment by MacMuser** [comment]
It's not Drag the App into the list but drag the icon with the arrow saying drag me, into the list. You'll then get a screen with fireworksaand installation is complete

**Comment by cormiertyshawn895** [comment]
Like @MacMuser shared, you need to drag the bubble that says “drag me into the list” into the list.
