### ISSUE TITLE
This is a "thank you" issue

### ISSUE THREAD

**Issue by jwr** [cormiertyshawn895/Retroactive#264]
Just wanted to leave a "thank you" note. I just used Retroactive to run Aperture on macOS Monterey and it helped me tremendously. Thanks to Retroactive I don't have to boot up an old laptop with an older macOS version and I can still have access to my photo archives.

I'm still looking for a long-term solution and a way to migrate my archives (this is not easy, because version stacks are used to group two sides of a scanned photo, for example). I got terribly burned by Apple dropping Aperture, and I'm thinking about writing my own software for long-term image archive storage.

So, no problems to report — things work as I expected, and I just wanted to thank you for the tremendous effort you made to publish this piece of software!

**Comment by cormiertyshawn895** [comment]
Thank you for the kind words! I’m glad to have helped.
