### ISSUE TITLE
Unable to downgrade and run iTunes 10.7

### ISSUE THREAD

**Issue by Storm0fWar** [cormiertyshawn895/Retroactive#265]
Hello

I previously installed iTunes 10.7 using the Retroactive app ver 10.9 and then I later downloaded iTunes 11.4 using the same app. Turns out I didn't like the layout of 11.4 and want to downgrade to 10.7 but whenever I do that I'm unable to open the app. I'm running Mac os Big sur 11.2
![Screenshot 2022-01-24 at 12 28 10 PM](https://user-images.githubusercontent.com/98322940/150782934-59d5fb66-7ee3-43ef-8485-8f9583757532.png)

**Comment by cormiertyshawn895** [comment]
Can you delete the broken iTunes app, then try to download iTunes 10.7 again with Retroactive?
