### ISSUE TITLE
No playlists came over from old iTunes

### ISSUE THREAD

**Issue by ainmgh** [cormiertyshawn895/Retroactive#266]
When I went from Mojave (iTunes 12.9.5.5) to Monterey (Music app), no playlists came over from iTunes.
The new Music app has none of my old iTunes playlists.
So I installed Retro with iTunes.
But now the Retro iTunes also has none of my old iTunes playlists.
What can I do here?
I have a full backup of my old Mojave on an external drive. I started it as a test, and can see my old iTunes and all the playlists.
Thanks.
Mac

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
