### ISSUE TITLE
Thank you and question

### ISSUE THREAD

**Issue by lf111** [cormiertyshawn895/Retroactive#267]
Thank you very much for retroactive!!! I can use Final cut 7 on Mojave with high end gpu.
Please, could you enter in contact with me? It's because I'd like to use also Dvd studio pro in Mojave, which belong to the Global "final cut studio" as Final cut pro 7.
I can contribute. Thanks very much
lf111@free.fr
Laurent / Paris

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
