### ISSUE TITLE
M1 running 12.1 iTunes keeps crashing with error - will it work? 

### ISSUE THREAD

**Issue by k9malinda** [cormiertyshawn895/Retroactive#268]
updated to new M1 / 12.1 iTunes crashing - any update?  Pop up: An unknown Error occurred (-42408).

**Comment by holtkamp** [comment]
The old iTunes 11.4 works for me on a Mac Mini M1 running on macOS 12.2.1, allowing me to listen to an iTunes library shared on the network on an old Mac...

**Comment by Chase0ut** [comment]
I was about to comment the same thing; I've been trying to get 12.9.5 to work on my M1 because restoring through Finder is less successful (and sometimes doesn't work at all) when compared to using iTunes on my 2017 macbook.

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes. Like @holtkamp suggested, Family Sharing works with iTunes 11.4.

**Comment by ylluminate** [comment]
@cormiertyshawn895 this error above - that doesn't seem to really affect anything in the way of meaningful functionality - is still haunting us. I'm curious, does the 2.0 release do anything to perhaps resolve this? Referring specifically to:
![error](https://p153.p0.n0.cdn.getcloudapp.com/items/8Lu1drE6/f54035b2-d9c1-4bd8-a6bc-8c07c9a32ecc.png?v=f1d60ee95c1d1e3a90c563fa9961320a)

@k9malinda please note, the error you have been seeing does NOT stop iTunes from functioning on Apple Silicon. It's just an annoyance...

**Comment by k9malinda** [comment]
I PHOTO OPENS AND WORKS!!!!!!!! 

THANK YOU THANK  YOU THANK YOU X100000000!!!!  do y’all accept donations? Anything for your hard work?

malinda :)

**Comment by k9malinda** [comment]
iTunes 12.9.5.5 

“An unknown error occurred (-42408) 
I have done the disable and restarted 
I have installed earlier versions

same error 

It also said couldn’t read my iPad, restore to factory settings

Advice? 

malinda julien

**Comment by ylluminate** [comment]
So yes, I also tried to reinstall iTunes Version 12.9.5.5 with Retroactive 2.0 and found that the same error still occurs as above and the same as @k9malinda is seeing. It still works fine - iTunes works even with that dialogue box / error appearing as per how it has worked fine for the last couple years now.

@k9malinda just live with it and click `OK` when it pops up - you'll still be fine. I'm enjoying listening to my music with iTunes 12.9.5.5 on macOS 12.5.1 currently on an M1 Max system.

**Comment by k9malinda** [comment]
okay I’ll try it thanks!
mj

**Comment by k9malinda** [comment]
I am trying to sync from my M1 to my iPad Pro (photos) but it says “cannot be synced. An unknown error occurred (-42408) (this is what I need iTunes for)
If I click “OK” and try to sync again, it does the same thing. 

both M1 and iPad are up to date

thoughts?

malinda

**Comment by ylluminate** [comment]
Hmm... I do not use iTunes for sync'ing anymore. I only use it to listen to and manage music on my macOS computers. Now that you mention it, I just don't use any Apple programs to manage music on my devices anymore. I use [iMazing](https://imazing.com/) and [WALTR Pro](https://softorino.com/waltr/). I just don't like Apple's methodology for managing audiobooks and music on my iOS devices any longer. We have about 12 (I think that's the last count) iOS devices now that we manage and most are between 2-10 years old.
