### ISSUE TITLE
Adding artwork to iTunes files. 

### ISSUE THREAD

**Issue by dcorkran63** [cormiertyshawn895/Retroactive#269]
I have just built a new late 2012 iMac system for my home office and installed iTunes. Everything is working except adding photos to the files. If the wrong photo is downloaded from apple it will not delete and I can not add photos. I've used retroactive to install iTunes on 2 2012 i7 Mac minis with no issues. Just wondering if anyone else is having this problem.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
