### ISSUE TITLE
DVD creator

### ISSUE THREAD

**Issue by pepsinet** [cormiertyshawn895/Retroactive#271]
Is it possible to add the Apple DVD creator app. There is no analog from other developers (near the same level). Thanks

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
