### ISSUE TITLE
Will 12.10.6 Itunes ever be possible in Retroactive?  (Iphone Sync ability) 

### ISSUE THREAD

**Issue by Siminaha** [cormiertyshawn895/Retroactive#272]
I realized that it would be very practical if i could load music on from itunes to my iphone directly. 

I see now that i need to remember what i want to load to the iphone and then turn off itunes , start Music and then search and load to iphone, which can become a bit chaotic if its more that 1-2 albums-names  (remembering them and too many steps) 

Is there any chance there will be 12.10.6 one day or am i missing something as in its not technically possible for some reason?

**Comment by cormiertyshawn895** [comment]
iTunes 12.10.6 is Windows-only and was never released for Mac. If you need to use iTunes 12.10.6, you can install Windows 11 with Parallels Desktop and use the Windows version of iTunes there.
