### ISSUE TITLE
Return To Music

### ISSUE THREAD

**Issue by LexVAPin** [cormiertyshawn895/Retroactive#274]
I found out that iTunes does not do what I want it to do for me.  So I want to return to Music in Big Sur.  After throwing out iTunes, Music does not finish loading.  All I get is a "Loading Music Library" notice.

I tried restoring an earlier Music library via TimeMachine and that did not work.

**Comment by LexVAPin** [comment]
I booted into Recovery and did a disk repair.  I am back to using the Apple Music.

I think I am going to copy the Music data folder, then delete all my own music within the app Music (but not delete the files) in order to create a second Library.   Then reverse that to get back to my own music.  Not exactly simple.

**Comment by cormiertyshawn895** [comment]
Automatic migration from iTunes to Music should work. If it doesn’t, re-importing all music into a Music library should do the trick.
