### ISSUE TITLE
iTunes Music Library is not up to date

### ISSUE THREAD

**Issue by glindw** [cormiertyshawn895/Retroactive#275]
I am currently installed Retroactive 1.9 on my macOS Monterey to use iTunes 12.9.5.5.  I have enabled full disk access and it loads up fine but one thing I have discovered that my iTunes Music Library isn’t up to date compared my library from my library on from my Apple Music App.

In my settings, my iTunes media folder location are pretty much the same with the following

iTunes - /users/myname/music/itunes/itunes music

Music - /macintosh HD/users/myname/music/itunes/itunes music

How can I update my music library in my iTunes to match with my music library thats in my Music app?

**Comment by cormiertyshawn895** [comment]
iTunes and Music have different library format, and libraries cannot be shared between them. To keep the same songs in both apps, you need to import them separately into each app.
