### ISSUE TITLE
Unsupported Image Format

### ISSUE THREAD

**Issue by hagbard231** [cormiertyshawn895/Retroactive#276]
I see "Unsupported Image Format" in Aperture on all my RAW files - even after i reprocessed all my images as you suggested.
Do I have to re-install some RAW Image processor again?

Aperture 3.6 under Mac OS 12.2.1 with Retroactive 1.9

**Comment by lucamolteni** [comment]
Same here, what's the reprocess trick you're referring to?

**Comment by hagbard231** [comment]
The one mentioned in the app:
![Screenshot 2022-02-14 at 19 19 28](https://user-images.githubusercontent.com/60688871/153923089-5af8b594-8361-43a2-bf18-86c20209bd50.jpg)
:
I did this several times - but with no avail.

**Comment by lucamolteni** [comment]
I'm getting this error message

<img width="234" alt="Screenshot 2022-02-14 at 22 10 59" src="https://user-images.githubusercontent.com/454752/153947097-3ceb821d-0592-4c65-9951-988ffbd9fc2b.png">

And the image is still unavailable, both RAWs (Fujifilm) and JPEGs

**Comment by hagbard231** [comment]
Same here (that's just from one album) And my images are unavailable as well. Even if I run the process several times.
![Screenshot 2022-02-15 at 09 12 46](https://user-images.githubusercontent.com/60688871/154020347-83ebff8b-f3a9-4310-b668-9dea38c8aa73.jpg)

The images that were reprocessed are the jpgs & TIFFs in the album. The Images that "don't need reprocessing" are Nikon RAW files that have been reprocessed before - but I still can't see them. "Unsupported Image Format"

**Comment by hagbard231** [comment]
The images that were reprocessed are the jpgs & TIFFs in the album. The Images that "don't need reprocessing" are Nikon RAW files that have been reprocessed before - but I still can't see them. "Unsupported Image Format"

**Comment by estyseesghosts** [comment]
Getting the same problems with sony ARWs and canon cr2s, even if I try converting to DNG first (M1 Macbook Pro, 12.3)

**Comment by Tim089** [comment]
Same issue on my M2/Monterey Airbook. Had all RAW/JPG originals outside the aperture library on my NAS and worked with references only on my old iMac. Now I can import new files which show up alright in the unlocked Aperture app, however, all previously imported pictures are not accessible. The link to the originals via "show original in finder" works.
Any ideas?

**Comment by TheGeekPharaoh** [comment]
Can confirm the issue still exists on macOS Sonoma on my mac mini (Intel).  I'm getting Unsupported Image Format when trying to view DNG images.  Aperture 3.6

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
