### ISSUE TITLE
How do I stop my Mac from opening links in iTunes with the Podcast app, rather than the iTunes app?

### ISSUE THREAD

**Issue by sebge-1** [cormiertyshawn895/Retroactive#277]
Example: I see this podcast in my iTunes (on Big Sur): https://podcasts.apple.com/gb/podcast/a-history-of-the-world-in-100-objects/id351096296 and when I click on it, the Podcast app automatically opens it (which I don't want as I like iTunes better for various reasons).

Is there a way I can configure these types of links to be opened with iTunes? I looked in Preferences but haven't seen anything relevant.

Thanks in advance!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
