### ISSUE TITLE
iTunes Will Not Play Songs-

### ISSUE THREAD

**Issue by gothgirl71** [cormiertyshawn895/Retroactive#282]
Hello-

We downloaded the most recent Retroactive 1.9 and got it working.  The only issue so far we have encountered is getting it to play music in the iTunes application itself.  We are using this iTunes application to manage our huge library we have on our classic iPod.  Previously before upgrading to Catalina, we were able to listen to our iPod music through iTunes, but now are unable to do that.  Is there a fix for this? 

And A HUGE THANK YOU for putting together this program!  Apple Music is completely USELESS for managing large amounts of music.

Cheers,
Misha

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
