### ISSUE TITLE
Error when trying to subscribe to podcast: We could not complete your iTunes request

### ISSUE THREAD

**Issue by sebge-1** [cormiertyshawn895/Retroactive#283]
When trying to subscribe to podcasts on iTunes, I'm getting the error below:
```

We could not complete your iTunes request. An unknown error occurred (-3000).
There was an error in the iTunes store. Please try again later.
```

Anyone know how I can fix this? Thanks!

**Comment by Woolwit** [comment]
I've been using an app called Poddr, that uses the iTunes API to search for podcasts (usually that I know I'm wanting to subscribe to). Once I have found the podcast I'm looking for and it's loaded into the Poddr window, I'll have access to the RSS feed url (look for the little curvy RSS icon). Click on that to show the feed URL. Copy that and then in iTunes... File > Subscribe to Podcast > Paste url. That's working for me with iTunes 11.4 on Monterey.
https://sn8z.github.io/Poddr/

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
