### ISSUE TITLE
itunes 12.0.1?

### ISSUE THREAD

**Issue by ghost** [cormiertyshawn895/Retroactive#284]
is there any way to install itunes 12.0.1? i have the dmg

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
