### ISSUE TITLE
iPhoto not opening at all

### ISSUE THREAD

**Issue by juancruz85** [cormiertyshawn895/Retroactive#285]
iPhoto just won't open at all I even tried rosetta 2. Im on Mac OS 13.0. Anyone have a fix for this

**Comment by juancruz85** [comment]
Here is the error Im getting
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iPhoto [2146]
Path:                  /Applications/iPhoto.app/Contents/MacOS/iPhoto
Identifier:            com.apple.iPhoto9
Version:               9.6.1 (910.42)
Build Info:            iPhotoProject-910042000000000~1
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-07-07 16:11:58.8767 -0700
OS Version:            macOS 13.0 (22A5286j)
Report Version:        12
Anonymous UUID:        F3EC687C-3AE4-AF81-E9C1-8EC30F466BCB

Sleep/Wake UUID:       A3510B91-6B59-44C4-94F2-27204BBC2D23

Time Awake Since Boot: 2900 seconds
Time Since Wake:       1845 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.6/Python
Referenced from: <3384A4B7-A008-3001-A109-BC2EE2DE5B9A> /Applications/iPhoto.app/Contents/MacOS/iPhoto
Reason: tried: '/System/Library/Frameworks/Python.framework/Versions/2.6/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/Python.framework/Versions/2.6/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/2.6/Python' (no such file, not in dyld cache), '/Library/Frameworks/Python.framework/Versions/2.6/Python' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x103c90954 ???
1   <translation info unavailable>	       0x103d0f5d4 ???
2   dyld                          	       0x20326b6a7 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x20326b6d9 abort_with_payload + 9
4   dyld                          	       0x2031f4764 dyld4::halt(char const*) + 375
5   dyld                          	       0x2031f1465 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
6   dyld                          	       0x2031f008c start + 2204

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffc70a90 0x7ff7ffc6c000 + 19088
1   runtime                       	    0x7ff7ffc7c868 0x7ff7ffc6c000 + 67688
2   runtime                       	    0x7ff7ffc7e1e8 0x7ff7ffc6c000 + 74216


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x0000000309a849e0   x3: 0x0000000000000083
    x4: 0x0000000309a845e0   x5: 0x0000000000000000   x6: 0x2f6d65747379532f   x7: 0x000000207262694c
    x8: 0x0000000309a845e0   x9: 0x0000000000000000  x10: 0x0000000000000083  x11: 0x0000000309a845e0
   x12: 0x0000000000000083  x13: 0x0000000309a849e0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010bcf5b80  x19: 0x0000000103c86000
   x20: 0x00000000000007ff  x21: 0x000000010bcfafa0  x22: 0xffffffffffffffff  x23: 0x0000000103c90928
   x24: 0x000000020326b6a7  x25: 0x0000000103c901f4  x26: 0x0000000103d0d568  x27: 0x0000000000000000
   x28: 0x000000020325257a   fp: 0x000000002c000000   lr: 0x0000000103d0f5d4
    sp: 0x000000010bcf5b80   pc: 0x0000000103c90954 cpsr: 0x80001000
   far: 0x0000000103d0f000  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2031ea000 -        0x20327dfff dyld (*) <8732cea0-08e8-3f1a-a12a-7899baf429ed> /usr/lib/dyld
    0x7ff7ffc6c000 -     0x7ff7ffc9bfff runtime (*) <3a874a67-b072-31ad-b0ee-2dc3c5f8f722> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=9260K resident=0K(0%) swapped_out_or_unallocated=9260K(100%)
Writable regions: Total=156.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    888K      219 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.2M        6 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__DATA                            1672K        7 
__DATA_CONST                        32K        1 
__DATA_DIRTY                        16K        1 
__LINKEDIT                         652K        7

**Comment by cormiertyshawn895** [comment]
Thanks for your report! This is fixed in [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0).
