### ISSUE TITLE
How can FCPX10.14.6 run on OCLP Big Sur?

### ISSUE THREAD

**Issue by ilovefifa** [cormiertyshawn895/Retroactive#286]
i have installed WebDriver for my GTX1050 After OCLP0.4.7 pacthed the Big Sur.i found the Final Cut Pro 10.14.6 version can running on a OCLP MacOS only
How can install FCPX10.14.6 on a OCLP Big Sur?

**Comment by cormiertyshawn895** [comment]
This sounds like an issue with OpenCore Legacy Patcher, which isn’t related to Retroactive.

I recommend joining the [OpenCore Patcher Paradise Discord Server](https://discord.gg/rqdPgH8xSN) and ask for support there instead.
