### ISSUE TITLE
iTunes full disk access on Ventura

### ISSUE THREAD

**Issue by motumotumotu** [cormiertyshawn895/Retroactive#288]
When I try to install iTunes on Ventura, clicking the "Enable Full Disk Access" opens the correct security pane, but the "Drag this" item does not appear like on previous OSes. Do anyone know how to grant full disk access as a workaround?

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) fixes the UI issue and lets you enable Full Disk Access.
