### ISSUE TITLE
I was just wondering. Will you still support this application for macos ventura?

### ISSUE THREAD

**Issue by dmuiX** [cormiertyshawn895/Retroactive#289]
Thanks a lot for this application. I am still using iTunes from time to time. Really love its design. Way better than music. 
I am just wondering: Last release was 2020. We have now 2022. Just curious: Do you still actively develope this application and release a new if some things are not working?

**Comment by cormiertyshawn895** [comment]
[Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) provides preliminary support for macOS Ventura. However some features such as iPhone and iPod syncing don’t work on Mac computers with Apple Silicon.
