### ISSUE TITLE
Retroactive Aperture - Catalina

### ISSUE THREAD

**Issue by Steigmeier** [cormiertyshawn895/Retroactive#290]
I have applied Retroactive Aperture 3.6 on mac OS Catalina and it seemed to work.  However, only the miniatures are showing, while the larger pictures (viewers) are disappearing after s hort second.  This appears to be a bug. 
How is this to be cured?
With this the Aperture app is useless!  It needs to be repaired by the IT editor asap. 
But please let the repair advise to be simple ans understandeble, I am a beginner.  

Please convey this to Tyshawn Cormier, please.  Best would be for me a contact email address to Tyshawn Cormier. 
Thank you.

Edgar Steigmeier

steigmeier.edgar@gmx.ch

**Comment by walterdavis** [comment]
No matter how shiny the packaging, this is open-source software, which you are free to download, fork, fix, etc. The original creator did a great job, but is in no way beholden to you or anyone to keep fixing it as Apple further breaks their own ecosystem. I think it is and was amazing, but I have had to move on, and you may want to consider the same choice.

Walter

**Comment by georgrehm** [comment]
I have the same issue. Has anyone been able to solve it?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
