### ISSUE TITLE
Download of iTunes 12.9.5 doesn't complete

### ISSUE THREAD

**Issue by uh50** [cormiertyshawn895/Retroactive#292]
I'm using Retroactive 1.9 on MacOS 12.5.1. Our internet service is from Hughesnet Satellite over their Wireless modem and typically have download speeds of 21 - 32 Mbps at my location. I've tried using Retroactive to download iTunes several times, but it never completes and I receive a dialog box telling me the download has stopped. 

I have two questions:

Can I download iTunes from another source and let Retroactive enable it for use on MacOS 12.5.1?
Is there a feature I'm not finding for continuing a download that has stopped?

TIA

uh50

**Comment by cormiertyshawn895** [comment]
Apple doesn’t provide a standalone installer for iTunes 12.9.5, so Retroactive downloads the full macOS Mojave installer to a temporary directory, then extracts and installs iTunes.

If you’re on a metered connection, try downloading iTunes 12.6.5, which is a much smaller and quicker download.

**Comment by uh50** [comment]
Thanks for the information, wish there were some choices for internet service here in rural America.
