### ISSUE TITLE
can't drag the drag me into the list to allow full disk access

### ISSUE THREAD

**Issue by psxpetey** [cormiertyshawn895/Retroactive#293]
is there a way around this? I tried dragging and it just stays there not adding to the list

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
