### ISSUE TITLE
iTunes  11.4 won't authenticate

### ISSUE THREAD

**Issue by psxpetey** [cormiertyshawn895/Retroactive#294]
strange it won't authenticate now just tells you to download new iTunes

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
