### ISSUE TITLE
Aperture Applescript

### ISSUE THREAD

**Issue by waldemarhorwat** [cormiertyshawn895/Retroactive#296]
I'm running into an authorization issue with invoking Applescripts in unlocked Aperture in Monterey.

After unlocking Aperture, it runs, and I can use Script Editor to run scripts on it such as

```
tell application "Aperture"
	get folder "Pictures"
end tell
```

but any attempt to run the scripts from Terminal results in an authorization error:

```
osascript -e 'tell application "Aperture"' -e 'get folder "Pictures"' -e "end tell"
```

results in:

```
32:49: execution error: Not authorized to send Apple events to Aperture. (-1743)
```

If I try to send events from command line scripts to other apps, Terminal will ask for authorization to send events to them and I can grant it. However, Terminal never asks for authorization to send AppleEvents to the unlocked Aperture, it just always fails the osascript request. I tried all of the `tccutil` tricks to reset the authorization to no avail. I can't get an Aperture checkbox to appear under Terminal in System Preferences:Security & Privacy:Automation.

`codesign` reports that it thinks the unlocked Aperture did not get signed:

```
codesign -d /Applications/Aperture.app
/Applications/Aperture.app: code object is not signed at all
```

Is that expected?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
