### ISSUE TITLE
error 42408 iTunes 12.6.5 on M1

### ISSUE THREAD

**Issue by k9malinda** [cormiertyshawn895/Retroactive#297]
I need iTunes 12.6.5 to sync photos from M1 Mac / Monterrey to iPad.  keep getting this error -42408.  When ignored, and I plug in device wired, I get "Tunes cannot read the contents of the iPad”. Go to the Summary tab in iPad preferences and click Restore to restore this iPhone to factory settings."

I can not upgrade to 12.9.5 because it doesn't handle photos.  

Advice.  (I have uninstalled and reinstalled several times, and have the latest Retroactive.

**Comment by Lazeerider** [comment]
me too! error 42408 on M2 proc! : /

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
