### ISSUE TITLE
mac book pro 15-inch,2019

### ISSUE THREAD

**Issue by Plane7766** [cormiertyshawn895/Retroactive#298]
macOS Catalina 10.15.1(of products)

can i use final cut pro 7 on this computer？

ID from China

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
