### ISSUE TITLE
Aperture Support ongoing

### ISSUE THREAD

**Issue by BobShawAU** [cormiertyshawn895/Retroactive#299]
Hi,
I really appreciate what to have done with Retroactive.
Have you considered taking over and supporting Apple Aperture directly?
There are many photographers that regard it as far superior to anything else on the market.
Lightroom is clunky and lacks basic features like crop dimensions.
Raw Power is great as far as it goes but is not integrated with the database and creates sidecar files.
Photos app is just useless for any professional work.
Apple may be prepared to sell or licence Aperture and it could monetise very well.
Bob

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
