### ISSUE TITLE
Aperture Luminar plugin

### ISSUE THREAD

**Issue by frankdelaet** [cormiertyshawn895/Retroactive#3]
First up: THANKS for this app, like many people, I have been waiting to install 10.15 because of the Aperture problem.
I didn't have the Luminar 3 plugin for Aperture installed on the volume on which I'm testing 10.15, but I was able to get it working again by copying the plugin from this location
/Library/Application Support/MacPhun Software/Luminar3/Plug-Ins/Luminar3Plugin.ApertureEdit
to here
/Library/Application\ Support/Aperture/Plug-Ins/Luminar3Plugin.ApertureEdit
For some reason just creating a symlink didn't work

**Comment by frankdelaet** [comment]
I should have added that the option to install the plugin from within Luminar 3 was not available in 10.15 after running the Retroactive app (I updated a copy of my 10.14 installation that didn't have the Luminar plugin installed).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
