### ISSUE TITLE
iTunes 12.9.5 HDCP error when trying to play purchased video content

### ISSUE THREAD

**Issue by g165** [cormiertyshawn895/Retroactive#30]
I am unable to play any purchased video content in iTunes on my computer. I get an error every time I click play saying that it won't play on my display due to HDCP not being supported. If I download the video and navigate to the video file in Finder, the video will play fine on the Apple TV app or Quicktime, so this is specific to this version of iTunes.

**Comment by cormiertyshawn895** [comment]
This is a known limitation right now. You can play them in the TV app instead.

**Comment by fergo79** [comment]
Experiencing this issue in iTunes 11.4 as well on Sonoma 14.4.  Any chance this will be addressed?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
