### ISSUE TITLE
M1 Mac iTunes Download Fails

### ISSUE THREAD

**Issue by eea3** [cormiertyshawn895/Retroactive#300]
I tried to download any version of iTunes and get an error in retroactive 2.0 :

Unable to download iTunes

The network connection was lost

Network seems to work ok!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
