### ISSUE TITLE
Itunes 12.9.5 on M1 Pro and Monterey 12.6: Application does not start / not responding 

### ISSUE THREAD

**Issue by CarlosDiSarli** [cormiertyshawn895/Retroactive#301]
Systemconfiguration: MacBook Pro (16-inch, 2021) with Apple Silicon M1 Pro, Monterey 12.6

I used retroactive 2.0 and have disabled System integrity protection as advised in the instructions.

After starting Itunes 12.9.5 Application is not responding.

Attached is the crash log file
[CrashLog_Itunes12.9.5_m1_pro_retrocative2.0.pdf](https://github.com/cormiertyshawn895/Retroactive/files/9618899/CrashLog_Itunes12.9.5_m1_pro_retrocative2.0.pdf)

Thanks a million in advance for any help.  If I get Itunes running, that would be a life safer for me and my music collection.

**Comment by simcc** [comment]
I managed to get 12.8.3.1 working on m1 with scripts from this thread: https://forums.macrumors.com/threads/itunes-12-6-5-3-on-apple-silicon.2354390/

works without disabling SIP

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
