### ISSUE TITLE
Can't sync anything with iTunes 12.6.5

### ISSUE THREAD

**Issue by pizzaonmychest** [cormiertyshawn895/Retroactive#302]
Hi, whenever I try to sync anything I get error -42408.
It also says a lot that there is a problem with the device I am syncing and that it needs to eb restored. Is there any fix to this?

**Comment by malevajeee** [comment]
Same problem here. I can't sync my iTunes playlists on my phone, either using finder or iTunes.
Heeelp please!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
