### ISSUE TITLE
itunes won't let me sign in

### ISSUE THREAD

**Issue by junespoon** [cormiertyshawn895/Retroactive#303]
i just installed itunes but when i try to sign into my account, these two errors pop up
<img width="478" alt="Screen Shot 2022-09-28 at 4 17 03 PM" src="https://user-images.githubusercontent.com/102754407/192880239-cf234daf-a800-4f3e-877a-d9f781888ba1.png">
<img width="476" alt="Screen Shot 2022-09-28 at 4 16 11 PM" src="https://user-images.githubusercontent.com/102754407/192880240-bc7a32dd-cdb0-4f72-ac23-60a66046f037.png">

**Comment by junespoon** [comment]
now, right when i launch itunes this error comes up as well
<img width="479" alt="Screen Shot 2022-09-28 at 4 42 12 PM" src="https://user-images.githubusercontent.com/102754407/192884678-ea872adb-3d30-417b-b4e7-4a728d421c69.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
