### ISSUE TITLE
iTunes 12.9.5: An unknown error occurred (-42408). [Retroactive 2.0, Monterey 12.6 (M1)]

### ISSUE THREAD

**Issue by simcc** [cormiertyshawn895/Retroactive#304]
Hi, I just installed 12.9.5 on Monterey 12.6 (M1) and keep getting this error every time I open iTunes...(I did `csrutil disable` and `sudo spctl --master-disable` etc. as per instructions)...also tried trashing preferences and changing various preferences (like disabling everything)...no dice...any ideas why I might be getting this? Using latest Retroactive as of today...

Also seems to be losing preferences...one thing is I haven't signed into iTunes with it yet (I don't need to or want it for that, but should I try that?)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by DistroHopper39B** [comment]
Now that retroactive is active again, can this be reopened? this issue is still happening to me on Sequoia on an M2 MBA.
