### ISSUE TITLE
iTunes 12.9.5: is there any alternative to disabling SIP? Reason being, it breaks all your iOS apps: they won't open. [Retroactive 2.0, Monterey 12.6 (M1)]

### ISSUE THREAD

**Issue by simcc** [cormiertyshawn895/Retroactive#305]
Just noticed this myself. You have to re-enable it for them to work again, and that breaks iTunes 12.9.5 again :(

Also see here: https://forums.macrumors.com/threads/if-you-disable-sip-all-you-ios-apps-will-stop-working-on-your-m1.2269661/

**Comment by simcc** [comment]
I managed to get 12.8.3.1 working with scripts from this thread: https://forums.macrumors.com/threads/itunes-12-6-5-3-on-apple-silicon.2354390/ ...works without disabling SIP

Didn't work for my use though as my ITL is 12.9.5 (from Mojave)...really wanted all the data preserved.

**Comment by simcc** [comment]
so I got it working, what you need to do is forget Retroactive, get a copy of iTunes 12.9.5.5 from Mojave, zip it, move it over to new Mac, and unzip/put it in  ~/tmp ( ~/tmp/iTunes.app) and then run these commands:

xcode-select --install

plutil -replace CFBundleGetInfoString -string 'iTunes 13.9.5.5' ~/tmp/iTunes.app/Contents/Info.plist
plutil -replace CFBundleShortVersionString -string 13.9.5 ~/tmp/iTunes.app/Contents/Info.plist
plutil -replace CFBundleVersion -string 13.9.5 ~/tmp/iTunes.app/Contents/Info.plist
ditto -c -k --sequesterRsrc --keepParent ~/tmp/iTunes.app ~/Desktop/iTunes12.9.5.5_Patched.zip
ditto ~/tmp/iTunes.app /Applications/iTunes.app

install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib

sudo codesign -fs - --deep /Applications/iTunes.app

paste them in as 4 chunks above...no need to do each individually.

Working Ventura on M1

From here: https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-15?post=32010794#post-32010794

**Comment by SunnyFloppyDiskStudios** [comment]
If you are on macOS Sonoma, Sequoia then you need to add `sudo` before every command. Also `xcode-select --install` typically happens automatically in system settings.

**Comment by simcc** [comment]
> If you are on macOS Sonoma, Sequoia 

Oh so it still works, is everything working OK? I'm still on Ventura, but that would be great to know

**Comment by Likegrubhub** [comment]
> so I got it working, what you need to do is forget Retroactive, get a copy of iTunes 12.9.5.5 from Mojave, zip it, move it over to new Mac, and unzip/put it in ~/tmp ( ~/tmp/iTunes.app) and then run these commands:
> 
> xcode-select --install
> 
> plutil -replace CFBundleGetInfoString -string 'iTunes 13.9.5.5' ~/tmp/iTunes.app/Contents/Info.plist plutil -replace CFBundleShortVersionString -string 13.9.5 ~/tmp/iTunes.app/Contents/Info.plist plutil -replace CFBundleVersion -string 13.9.5 ~/tmp/iTunes.app/Contents/Info.plist ditto -c -k --sequesterRsrc --keepParent ~/tmp/iTunes.app ~/Desktop/iTunes12.9.5.5_Patched.zip ditto ~/tmp/iTunes.app /Applications/iTunes.app
> 
> install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes install_name_tool -change @executable_path/../Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes install_name_tool -change @executable_path/../Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib
> 
> sudo codesign -fs - --deep /Applications/iTunes.app
> 
> paste them in as 4 chunks above...no need to do each individually.
> 
> Working Ventura on M1
> 
> From here: https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-15?post=32010794#post-32010794

Hey im on macOS ventura as well. How do you get  iTunes 12.9.5.5 from Mojave?

Also just curious, if I use retroactive and disable SIP to install. Does re-enabling SIP prevent itunes from being used?

**Comment by SunnyFloppyDiskStudios** [comment]
@simcc it works okay-ish, the UI for "Apple Music" is broken and syncing with an iPod crashes iTunes.

@Likegrubhub this guide is for _without_ retroactive, enabling SIP with the retroactive version will break the application. You need a seperate Mac with Mojave, copy the app from the Applications folder into a zip and airdrop it over to your mac.

**Comment by Likegrubhub** [comment]
> @simcc it works okay-ish, the UI for "Apple Music" is broken and syncing with an iPod crashes iTunes.
> 
> @Likegrubhub this guide is for _without_ retroactive, enabling SIP with the retroactive version will break the application. You need a seperate Mac with Mojave, copy the app from the Applications folder into a zip and airdrop it over to your mac.

Thanks for the response!

Ok I see. If I dont have a 2nd mac with mojave, is there any other way to get 12.9.5.5.

Would this work to get mojave somehow?I had an older mac a year ago on  intel chip macOS Monterey that i used retroactive with to get itunes. I think it might be 12.9.5. Back then on monterey, I didnt even need to do SIP thing. I still have that monterey on time machine. Can I retrieve the itunes from the monterey time machine?

Also side question--Does disabling SIP make you more vulnerable to malware viruses trojans, etc? What other risks does it pose? Im asking as someone who is a laymen to computers.

**Comment by SunnyFloppyDiskStudios** [comment]
@Likegrubhub emulation maybe? I found that downloading it online led to corruption and issues so I'm guessing thats why we need a second Mac.

You only need to disable SIP with an Apple Silicon machine. Your Intel Mac didn't need to disable it because Intel SIP is different to AS SIP.

Also yes SIP will reduce the "integrity" of your computer. Apple strictly recommends having it left off temporarily [source](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)

**Comment by Likegrubhub** [comment]
> @Likegrubhub emulation maybe? I found that downloading it online led to corruption and issues so I'm guessing thats why we need a second Mac.
> 
> You only need to disable SIP with an Apple Silicon machine. Your Intel Mac didn't need to disable it because Intel SIP is different to AS SIP.
> 
> Also yes SIP will reduce the "integrity" of your computer. Apple strictly recommends having it left off temporarily [source](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)

Hey as a computer laymen, i had a few questions. 

Do I need to be on an admin account to do this? I am trying it on a non-admin user account just to test how it goes.

Do i put create a new folder called tmp in my home folder?

It made me download Xcode. Im assuming this is a program, but I dont see it in my list of apps? 

It also put a itunes 12.9.5.5.zip  on my desktop. Is this right?

**Comment by SunnyFloppyDiskStudios** [comment]
> > @Likegrubhub emulation maybe? I found that downloading it online led to corruption and issues so I'm guessing thats why we need a second Mac.
> > You only need to disable SIP with an Apple Silicon machine. Your Intel Mac didn't need to disable it because Intel SIP is different to AS SIP.
> > Also yes SIP will reduce the "integrity" of your computer. Apple strictly recommends having it left off temporarily [source](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)
> 
> Hey as a computer laymen, i had a few questions.
> 
> Do I need to be on an admin account to do this? I am trying it on a non-admin user account just to test how it goes.
> 
> Do i put create a new folder called tmp in my home folder?
> 
> It made me download Xcode. Im assuming this is a program, but I dont see it in my list of apps?
> 
> It also put a itunes 12.9.5.5.zip on my desktop. Is this right?

I think you need an admin account however you really just need access to recovery mode and the terminal within.

Yes you create a new folder for tmp unless you change the command to point elsewhere.

you didn’t download Xcode, instead it’s a terminal add on which supports Xcode and adds other things which are required for this.

You put the app itself into the tmp folder or you can point it to the desktop but it must be .app not compressed as .zip

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
