### ISSUE TITLE
iTunes 10.7 and 11.4 crashes on a daily basis on Monterey 12.6

### ISSUE THREAD

**Issue by MaxTanner724** [cormiertyshawn895/Retroactive#306]
I installed iTunes on my M2 MacBook Air and it literally crashes whenever I do anything or not. I almost corrupted my iPod 5.5 when I tried to sync songs on iTunes. I'm running Monterey 12.6.

**Comment by Woolwit** [comment]
I'm running iTunes 11.4 on Monterey 12.5.1 with no issues. M1 Mac Mini. I'm getting nagged to update to 12.6 but don't want to risk messing up my iTunes. 
If anyone else already running 12.5 can report on results of updating to 12.6 that would be great.

**Comment by Woolwit** [comment]
Bit the bullet and updated. All well... Mac Monterey 12.6 on Mac M1 mini running iTunes 11.4 64bit. Thanks Again Tyshawn Cormier!!

**Comment by MaxTanner724** [comment]
just updated to the public release of Ventura 13.0, Let's see if it fixed the fricking crashing issue.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
