### ISSUE TITLE
FCP7 issues since updating to High Sierra/Mojave and applying Retroactive 

### ISSUE THREAD

**Issue by peacockharris** [cormiertyshawn895/Retroactive#307]
2 issues have been introduced for me:

1. Pinch to zoom on the trackpad (in my case a Magic Trackpad 2) no longer works. As I use it all the time, this is making the software virtually unusable. Other gestures e.g scrubbing through the timeline, still work fine.
EDIT: I should mention, the keyboard shortcut for zooming in (CMD +) still works, so the functionality isn't gone, just the trackpad being able to enact it.

2. Certain projects won't open at all anymore. They simply hang at a certain percentage when opening the project. I have no idea what it is about these particular projects that's causing the issue. I can confirm they aren't corrupt and open fine on an older Mac.

EDIT: I've now fixed issue 2. It turned out it was a plugin causing the problem (Magic Bullet: Colorista), though I'm really gutted about that as I used it quite often!

When it comes to the trackpad issue, I've already trashed preferences and tried basically everything to fix it.

**Comment by peacockharris** [comment]
Just adding a comment, as this issue is soul-destroying, and essentially means my new Mac Mini (bought specifically as a replacement for my video editing Mac) is an expensive paperweight.

Pinch to zoom works everywhere else except in FCP7. It's the only trackpad gesture within Final Cut that's been affected (e.g scrubbing through the timeline with 2 fingers still works fine). This baffles me. Why would just this one gesture be broken and not the others?

I know this isn't going to be a priority fix, but it's a key piece of functionality within Final Cut. I'm finding it hard to understand why I've not heard anyone else mention this issue.

**Comment by peacockharris** [comment]
As far as a fix goes for the pinch-to-zoom issue, I've yet to find one, or even find other people experiencing this issue. But for the sake of any future people stumbling across this, I've found a workaround that performs adequately for my purposes.

There's an app called 'BetterTouchTool' that lets you bind simulated keypresses to specific trackpad gestures. You can also set it to only exhibit this behaviour in a particular app. So I've set pinch to zoom (both in and out actions) to the respective FCP7 keyboard shortcuts (cmd - & cmd +). After playing around with the sensitivity a bit, I've got a decent facsimile of how the native zoom behaved.

BetterTouchTool is paid software, but there's a legacy version available with a free license if you're willing to dig around for it.

**Comment by peacockharris** [comment]
Leaving another comment, because I'm still hoping for a fix for this.

While my workaround of using BetterTouchTool works, it's not perfect, as it doesn't understand context.

What I mean by this is that the stock Pinch to Zoom back in Sierra knew what you wanted to zoom in on, depending on what your mouse was hovering over. Whereas with BetterTouchTool, you have to click on the specific item (canvas/viewer/timeline) before zooming on it. So even if you're hovering over the canvas, if the last thing you did was interact with the timeline, pinching will zoom in on the timeline instead. 

I still can't get used to this, and I can't understand why no one else is talking about this lack of functionality, which without me finding this 3rd party app, would be even less functional.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
