### ISSUE TITLE
iTunes not storing book files in Album subfolders

### ISSUE THREAD

**Issue by simonsoho** [cormiertyshawn895/Retroactive#308]
<img width="483" alt="Screenshot 2022-10-16 at 17 50 00" src="https://user-images.githubusercontent.com/57946324/196048058-d04b3d29-eb54-4625-9cb8-bf9a35a9e120.png">

iTunes used to store my audiobook files in artist / title folders, now it just stuff it into an artist  folder.   Any ideas why this might be happening

I only use iTunes for managing my audiobook/plays. but I have dragged a few music tracks and they still go into artist / album subfolder 

<img width="978" alt="Screenshot 2022-10-16 at 18 03 15" src="https://user-images.githubusercontent.com/57946324/196048417-ebfc25e8-2153-46a2-949d-a3fd94792b43.png">

I've installed iTunes 12.6.5.3 and running on an M1 MacBook Pro with the latest OS  but I tried other version and on previous versions of the Mac OS over the last year or so

I also installed retroactive v2 and reinstalled iTunes but same behaviour happens

**Comment by tbaer1** [comment]
For audio books, iTunes never saved the albums in subfolders.

With music files, however, for 20 years they have always been neatly stored in artist/album folders.

**Comment by simonsoho** [comment]
its odd you say that because I have one pre iTunes death copy of my library and everything is in sub folders . when I reinstalled iTunes and copied it over to my my current  mac's much larger internal ssd the copy of the library moved everything into artist folders.   I don't remember having manually created all the subfolders and manually unblocking the keep organised thing. I might have to resurrect an old Mac and experiment

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
