### ISSUE TITLE
iTunes 12.9.5: Library libgnsdk_dsp.3.06.1.dylib not found

### ISSUE THREAD

**Issue by bsdooby** [cormiertyshawn895/Retroactive#309]
I get the following error (using Retroactive 2.0 on an inplaced upgraded Catalina [dosdude1] -> Monterey [OpenCore-patcher] macOS installation [MacBook Pro 17", late 20111):

`
Process:               iTunes [13459]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [13456]
User ID:               501

Date/Time:             2022-10-21 05:13:08.5683 +0200
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        63F7733C-CCC6-9938-D368-D2D2B916846B

Time Awake Since Boot: 32000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib'
Referenced from: '/Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes'
Reason: tried: '' (no such file), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)`

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
