### ISSUE TITLE
Aperture RAW Unsupported Image Format - Still with 2.0, M1, Monterey

### ISSUE THREAD

**Issue by SwissMannJ** [cormiertyshawn895/Retroactive#311]
I've followed instructions thoroughly.  I cannot get my RAW photos to work in Aperture.

MacBook Pro 14"
M1 Pro Chip
Monterey 12.6
Aperture 3.6
Retroactive 2.0
Canon 70d
Nikon D700
Nikon D70

Steps taken
Right click Open Retroactive
Click Aperture Unlock
Link to App Store
Download from my past purchase Aperture 3.6
Authenticate Aperture in Retroactive
Launch Aperture while holding down Option key
Create a new library to test
Import RAW files from Desktop from Canon 70d and Nikon D700 and Nikon D70 - one from each so 3 total
Photos Menu Reprocess Original keep "All Photos" and "Reprocess existing images" selected
Repeat - Photos Menu Reprocess Original Keep "All Photos" and "Reprocess existing images" selected
Repeat again for good measure

Bonus Steps after this didn't work
Given Aperture Full Disk Access in Privacy under System preferences
Changed Aperture and Aperture Library Privileges so that everyone can Read and Write
Photos - Generate thumbnail, Delete preview, Update Preview

Each time it says that "3 images were reprocessed"
No thumbnail, no preview, no image
I can export the originals and use them in different apps though.

Hope this helps.

Thank you.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
