### ISSUE TITLE
iTunes crashes with libgnsdk_dsp.3.06.1.dylib error on Ventura 13.0, OpenCore Legacy Patcher

### ISSUE THREAD

**Issue by WhitetailAni** [cormiertyshawn895/Retroactive#312]
Attempting to install iTunes via Retroactive (1.9 or 2.0) causes iTunes to crash with the error:

`dyld[13771]: Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
  Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
/Applications/iTunes.app/Contents/MacOS/iTunes: line 15: 13771 Abort trap: 6           "$iTunes_BIN"
`

iTunes worked on Monterey; I'm assuming it's an issue with OCLP for Ventura being an alpha but figured I'd ask here just in case. Any advice is appreciated, thanks!

**Comment by tbaer1** [comment]
Here the same problem since update yesterday on MacBook Air 2020

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
