### ISSUE TITLE
iPod shuffle doesn't show up in iTunes 12.9.5.5

### ISSUE THREAD

**Issue by count0x30** [cormiertyshawn895/Retroactive#313]
I'm on a 2019 Intel MacBook Pro and just upgraded to Ventura.  Used Retroactive 2.0 to reinstall iTunes 12.9.5.5, followed the prompt to enable full disk access, and killed AMPDevicesAgent.  My 4th gen shuffle is not showing up in iTunes, but it does in Finder.  The shuffle would show up and sync correctly from Catalina to Monterey.  

However, my iPhone and a 7th gen iPod nano do connect without trouble.  Hope it's not end of the line for the shuffle, thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
