### ISSUE TITLE
Retro on Ventura gets this error every time. Even after 'csrutil disable'???

### ISSUE THREAD

**Issue by nikbex-sno** [cormiertyshawn895/Retroactive#314]
Translated Report (Full Report Below)
-------------------------------------

Process:               iTunes [979]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [976]
User ID:               502

Date/Time:             2022-10-27 15:34:16.7519 +0100
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        7B8DB681-53B5-3489-6FBA-1F748E440B4A

Time Awake Since Boot: 290 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80993c83a __abort_with_payload + 10
1   dyld                          	    0x7ff8099559c7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff8099559f9 abort_with_payload + 9
3   dyld                          	    0x7ff8098dd1e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff8098da660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff8098d9281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bea673c8  rdx: 0x00007ff7bea67830
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bea67410  rsp: 0x00007ff7bea673c8
   r8: 0x00007ff7bea67430   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7bea67830  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80993c83a  rfl: 0x0000000000000246  cr2: 0x0000000103661000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
    0x7ff8098d3000 -     0x7ff809967547 dyld (*) <0f050705-2258-3d40-b7bc-f3b35a44bbea> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=211.8M resident=0K(0%) swapped_out_or_unallocated=211.8M(100%)
Writable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            3487K        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       182.1M        2 
__TEXT                            29.8M        2 
dyld private memory                512K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            279.7M       16 

-----------
Full Report
-----------

{"app_name":"iTunes","timestamp":"2022-10-27 15:34:16.00 +0100","app_version":"12.9.5","slice_uuid":"91006ee5-c8c4-3a53-b7f7-69a3b2fd991a","build_version":"12.9.5","platform":1,"bundleID":"com.apple.iTunes","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0 (22A380)","roots_installed":0,"name":"iTunes","incident_id":"511F0F82-8590-4108-90F3-C6BA3CD74AFA"}
{
  "uptime" : 290,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,4",
  "coalitionID" : 939,
  "osVersion" : {
    "train" : "macOS 13.0",
    "build" : "22A380",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-27 15:34:16.7519 +0100",
  "incident" : "511F0F82-8590-4108-90F3-C6BA3CD74AFA",
  "pid" : 979,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-10-27 15:34:16.7178 +0100",
  "procStartAbsTime" : 297094055912,
  "procExitAbsTime" : 297127790846,
  "procName" : "iTunes",
  "procPath" : "\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes",
  "bundleInfo" : {"CFBundleShortVersionString":"12.9.5","CFBundleVersion":"12.9.5","CFBundleIdentifier":"com.apple.iTunes"},
  "buildInfo" : {"ProjectName":"iTunes","SourceVersion":"1200012009005005","BuildVersion":"9"},
  "storeInfo" : {"deviceIdentifierForVendor":"4CE9BF22-3207-5F12-B650-69CB8746876D","thirdParty":true},
  "parentProc" : "Exited process",
  "parentPid" : 976,
  "coalitionName" : "com.launcher.iTunes",
  "crashReporterKey" : "7B8DB681-53B5-3489-6FBA-1F748E440B4A",
  "responsiblePid" : 976,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib","Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> \/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes","Reason: tried: '\/System\/Volumes\/Preboot\/Cryptexes\/OS@executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib' (no such file), '\/usr\/lib\/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10258,"threadState":{"r13":{"value":140702032230448},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140702032229424},"cr2":{"value":4351987712},"rdx":{"value":140702032230448},"r10":{"value":150},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703289296954,"matchesCrashFrame":1},"rbp":{"value":140702032229392},"rsp":{"value":140702032229320},"r12":{"value":150},"rcx":{"value":140702032229320},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":432186,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":534983,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":535033,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":0},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703288864768,
    "size" : 607560,
    "uuid" : "0f050705-2258-3d40-b7bc-f3b35a44bbea",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703288258560,
  "size" : 21474836480,
  "uuid" : "3e6c1144-e4b6-381c-92d1-0a3396dd3bb0"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=211.8M resident=0K(0%) swapped_out_or_unallocated=211.8M(100%)\nWritable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                            3487K        3 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       182.1M        2 \n__TEXT                            29.8M        2 \ndyld private memory                512K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            279.7M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {
        "PROACTIVE_MAIL_INTELLIGENCE_SALIENCY" : "63582cdd892de80b72cc9bde"
      },
      "deploymentId" : 240000001
    },
    {
      "rolloutId" : "61fd92db295c182621ececc3",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "634d529fb3714d3622fc75aa"
      },
      "deploymentId" : 240000201
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro11,4, BootROM 476.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Display: Color LCD, 2880 x 1800 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1764)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB30Bus
USB Device: ASMT1051
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
