### ISSUE TITLE
Aperture on Catalina - no photos can be seen also after reprocessings

### ISSUE THREAD

**Issue by JoostMu** [cormiertyshawn895/Retroactive#315]
Hi, I went from 10.13 to 10.15.7 Catalina and used retroactive to get Aperture working again, however, no photos can be seen, only the small previews, if they remain, I tried reprocessing a number of times, see attached screen. It seems photos cannot be viewed
(also, the title show "unboxed")
<img width="1552" alt="Schermafbeelding 2022-10-27 om 21 12 50" src="https://user-images.githubusercontent.com/116840381/198378302-fd6d25e6-5d97-47f0-8009-35a389a3738b.png">

**Comment by georgrehm** [comment]
I just unlocked Aperture, also on Catalina (running on an 2013 iMac), and I experience the same issue. Have you been able to solve it?

**Comment by JoostMu** [comment]
Hi Georg,No I couldn’t solve it and still working at getting my Aperture library good again and to get it migrated into a photo library, without returning to my previous OS etc. I hope I got this done and then I am aiming at working with raw powerIt could be so nice if the aperture library was in good shape….Hartelijke groet,JoostOp 7 jan. 2023 om 13:28 heeft Georg Rehm ***@***.***> het volgende geschreven:﻿
I just unlocked Aperture, also on Catalina (running on an 2013 iMac), and I experience the same issue. Have you been able to solve it?

**Comment by Chris4tytwo** [comment]
Hi everyone

I have the exact same issue and it seems to behave exactly the same same name ("Aperture unboxed") same broken previews if I try to rebuild it...

the image appears quickly then disapears... I can see the pictures in the overview (many small thumbnails) or in the thumbnail strip...but not on the top window interface or in full screen mode...


any explanation or solution for this?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
