### ISSUE TITLE
iTunes repeatedly Unexpectedly Quitting

### ISSUE THREAD

**Issue by jjl1118** [cormiertyshawn895/Retroactive#316]
New guy here and not tech savvy.  I just downloaded Ventura on my Mac and the latest iTunes update from here.  Repeatedly getting an iTunes unexpectedly quit message.  Help please

**Comment by jjl1118** [comment]
I should add this happens after I've explored iTunes preferences once I OK or Cancel regardless of whether a change was made.

**Comment by jjl1118** [comment]
Got the quitting to stop by downloading the latest version.  Now can't get the media location to change to my external hard drive.  This is under the advanced preferences.  Any help would be great.  Thanks.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
