### ISSUE TITLE
Again Problems with IPhoto

### ISSUE THREAD

**Issue by doxxxob** [cormiertyshawn895/Retroactive#317]
After the solution to the problem I faced a year ago I could work fine with IPhoto. Thanks for this again. 
Since one week there are other problems without any changes in mac os versions etc. 
I cannot export fotos, edit them etc. IPhoto  immediately crashes.

The crash report:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iPhoto [22928]
Path:                  /Applications/iPhoto.app/Contents/MacOS/iPhoto
Identifier:            com.apple.iPhoto9
Version:               9.6.1 (910.42)
Build Info:            iPhotoProject-910042000000000~1
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-10-28 10:45:49.1417 +0200
OS Version:            macOS 12.6.1 (21G217)
Report Version:        12
Anonymous UUID:        1C4A9779-A0B3-E6CB-15D4-5F6339729F43

Time Awake Since Boot: 5200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       UNKNOWN_0xD at 0x0000000000000000
Exception Codes:       0x000000000000000d, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [22928]

VM Region Info: 0 is not in any region.  Bytes before following region: 4366467072
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104430000-104b8c000    [ 7536K] r-x/rwx SM=COW  .../MacOS/iPhoto
......
and so on

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
