### ISSUE TITLE
iTunes doesn't work after a 13.0 Ventura installation

### ISSUE THREAD

**Issue by djbobbyd** [cormiertyshawn895/Retroactive#318]
I have successfully installed on Macbook pro 13" early- 2015, but after that iTunes doesn't work. I tried to install it again with Retroactive 2.0, but it gives an error...

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iTunes [1540]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [1537]
User ID:               501

Date/Time:             2022-10-29 13:11:26.3424 +0300
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        68DF8199-9FCC-CE98-A1A8-4B111D556464

Sleep/Wake UUID:       236741A3-1FEA-4E61-8181-AADD8A93B1F9

Time Awake Since Boot: 7400 seconds
Time Since Wake:       7242 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff809f9e83a __abort_with_payload + 10
1   dyld                          	    0x7ff809fb79c7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff809fb79f9 abort_with_payload + 9
3   dyld                          	    0x7ff809f3f1e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff809f3c660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff809f3b281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b89fd3d8  rdx: 0x00007ff7b89fd840
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b89fd420  rsp: 0x00007ff7b89fd3d8
   r8: 0x00007ff7b89fd440   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7b89fd840  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff809f9e83a  rfl: 0x0000000000000246  cr2: 0x00000001096cb000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
    0x7ff809f35000 -     0x7ff809fc9547 dyld (*) <0f050705-2258-3d40-b7bc-f3b35a44bbea> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=211.8M resident=0K(0%) swapped_out_or_unallocated=211.8M(100%)
Writable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            3487K        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       182.1M        2 
__TEXT                            29.8M        2 
dyld private memory                512K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            279.7M       16

**Comment by djbobbyd** [comment]
I used before with Monterey 12.6.1 he worked

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
