### ISSUE TITLE
Media Folder In iTunes Won't Change

### ISSUE THREAD

**Issue by jjl1118** [cormiertyshawn895/Retroactive#319]
I go into preferences and then advanced and click on change media folder location.  I change it to an external hard drive which contains all my audio and then click open.  While it changes on the screen it does not change when I go to play.  Still stays in the default location.   Any help is greatly appreciated as I can't listen to any of my music.  Thanks!
Jeff

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
