### ISSUE TITLE
Adjustments and Presets (imported prior to OS Upgrade) all missing. 

### ISSUE THREAD

**Issue by Jamesr365** [cormiertyshawn895/Retroactive#32]
I noticed under the Adjustments Tab there is absolutely nothing just the shortcut for Quick Brushes although there is nothing. Also,  all my downloaded and installed presets are gone. Can this be resolved?

**Comment by cormiertyshawn895** [comment]
This should've been fixed since Retroactive 1.1. 

Can you [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/), and try to unlock Aperture in Retroactive again?

**Comment by Jamesr365** [comment]
> This should've been fixed since Retroactive 1.1.
> 
> Can you [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/), and try to unlock Aperture in Retroactive again?

Any chance you could stop it crashing when editing and importing?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
