### ISSUE TITLE
Quicktime Player 7 Pro

### ISSUE THREAD

**Issue by sergiopop75** [cormiertyshawn895/Retroactive#321]
Is it possible to include Quicktime player 7 Pro?

**Comment by juniorcaesar** [comment]
I'm still looking for an alternative to QTP7, it would be so awesome if Retroactive supports it in the future.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
