### ISSUE TITLE
I would like to know if there are any plans to update Final Cut Pro 7 to be usable on mac os 10.15

### ISSUE THREAD

**Issue by creator8178** [cormiertyshawn895/Retroactive#322]
I would like to know if there are any plans to update Final Cut Pro 7 to be usable on mac os 10.15. If not, I wonder why

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
