### ISSUE TITLE
iTunes cannot sync iPhone, even after complete reinstallation

### ISSUE THREAD

**Issue by Scalanji** [cormiertyshawn895/Retroactive#323]
no matter how often I install iTunes, I always get "iTunes cannot read the contents of the device. Go to the Summary tab in device preferences and click Restore this device to factory settings"

**Comment by rlsn0w** [comment]
Same issue here -- using Retroactive 2.0 and iTunes 12.9.5.5 on MacOS Ventura 13.0 on an M1 Max 2021 Macbook Pro, following all steps. Have tried multiple re-installs and multiple phones and get the same error message with each phone.  

Also receiving error -42408 each time iTunes starts up.

**Comment by samuelevalperta** [comment]
Same for me.

> Same issue here -- using Retroactive 2.0 and iTunes 12.9.5.5 on MacOS Ventura 13.0 on an M1 Max 2021 Macbook Pro, following all steps. Have tried multiple re-installs and multiple phones and get the same error message with each phone.
> 
> Also receiving error -42408 each time iTunes starts up.

**Comment by CyrusNemani** [comment]
same for me. 

My intel macbook pro running Monterey has been working no problem, but I bought a new MacbookAir with an M1 running Ventura and kept getting this error message. I thought Ventura was the issue, so i downgraded to Monterey. Both don't work on the M1. 

I also receive the 42408 error message. Playback functions seem to work fine, but the sync problem is a real hassle.

**Comment by dhnyny** [comment]
Same here with 15" MacBook Air (M2). Sigh.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
