### ISSUE TITLE
with iTunes open, dropdown menus on top of monitor (of any app) don't work

### ISSUE THREAD

**Issue by Scalanji** [cormiertyshawn895/Retroactive#324]
drop down menus of any app are dead on the monitor the iTunes window is shown. on a second monitor drop down monitors of other apps work - but (obviously) not iTunes

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
