### ISSUE TITLE
iTunes no longer works at all.

### ISSUE THREAD

**Issue by RadioDarrenFM** [cormiertyshawn895/Retroactive#325]
Last week it was fine, this week it doesn't want to know. Updated to Retroactive 2.0, but still nothing.

Here are the logs. Is anything obvious to anyone else?

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iTunes [1507]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [1504]
User ID:               501

Date/Time:             2022-11-11 09:10:59.9544 +0000
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        0162A448-3750-9C8E-0742-394255F632C9

Time Awake Since Boot: 2200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib'
Referenced from: '/Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes'
Reason: tried: '' (no such file), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x113c8898e __abort_with_payload + 10
1   dyld                          	       0x113c9ea72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x113c9eaa4 abort_with_payload + 9
3   dyld                          	       0x113c4c699 dyld4::halt(char const*) + 615
4   dyld                          	       0x113c485b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x113c474e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bbe034b8  rdx: 0x00007ff7bbe03920
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bbe03500  rsp: 0x00007ff7bbe034b8
   r8: 0x00007ff7bbe03520   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7bbe03920  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x0000000113c8898e  rfl: 0x0000000000000246  cr2: 0x0000000113c4eda4
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x113c42000 -        0x113cadfff dyld (*) <f71fb3ca-5fcc-3577-9457-b047888a46d1> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=30.5M resident=0K(0%) swapped_out_or_unallocated=30.5M(100%)
Writable regions: Total=9720K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9720K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                            3492K        3 
__DATA_CONST                        80K        1 
__LINKEDIT                         948K        3 
__TEXT                            29.6M        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             99.0M       15 

-----------
Full Report
-----------

{"app_name":"iTunes","timestamp":"2022-11-11 09:10:59.00 +0000","app_version":"12.9.5","slice_uuid":"91006ee5-c8c4-3a53-b7f7-69a3b2fd991a","build_version":"12.9.5","platform":1,"bundleID":"com.apple.iTunes","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.5.1 (21G83)","incident_id":"0AE3A045-A24A-4B3F-9E10-3E926EF39EE9","name":"iTunes"}
{
  "uptime" : 2200,
  "procLaunch" : "2022-11-11 09:10:59.9491 +0000",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro11,5",
  "procStartAbsTime" : 2263487991309,
  "coalitionID" : 736,
  "osVersion" : {
    "train" : "macOS 12.5.1",
    "build" : "21G83",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-11 09:10:59.9544 +0000",
  "incident" : "0AE3A045-A24A-4B3F-9E10-3E926EF39EE9",
  "bug_type" : "309",
  "pid" : 1507,
  "procExitAbsTime" : 2263492992604,
  "cpuType" : "X86-64",
  "procName" : "iTunes",
  "procPath" : "\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes",
  "bundleInfo" : {"CFBundleShortVersionString":"12.9.5","CFBundleVersion":"12.9.5","CFBundleIdentifier":"com.apple.iTunes"},
  "buildInfo" : {"ProjectName":"iTunes","SourceVersion":"1200012009005005","BuildVersion":"9"},
  "storeInfo" : {"deviceIdentifierForVendor":"11220321-D99D-5DD5-8B84-5477C63D142B","thirdParty":true},
  "parentProc" : "Exited process",
  "parentPid" : 1504,
  "coalitionName" : "com.launcher.iTunes",
  "crashReporterKey" : "0162A448-3750-9C8E-0742-394255F632C9",
  "responsiblePid" : 1504,
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib'","Referenced from: '\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes'","Reason: tried: '' (no such file), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":32156,"threadState":{"r13":{"value":140701985683744},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701985682720},"cr2":{"value":4626640292},"rdx":{"value":140701985683744},"r10":{"value":150},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4626876814,"matchesCrashFrame":1},"rbp":{"value":140701985682688},"rsp":{"value":140701985682616},"r12":{"value":150},"rcx":{"value":140701985682616},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4626587648,
    "size" : 442368,
    "uuid" : "f71fb3ca-5fcc-3577-9457-b047888a46d1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703511310336,
  "size" : 19331678208,
  "uuid" : "4d3a144c-02bb-31f1-bca9-83a5cb058c59"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=30.5M resident=0K(0%) swapped_out_or_unallocated=30.5M(100%)\nWritable regions: Total=9720K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9720K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                            3492K        3 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         948K        3 \n__TEXT                            29.6M        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             99.0M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "620aec83b02b354d3afd2f50"
      },
      "deploymentId" : 240000143
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000529
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro11,5, BootROM 430.140.3.0.0, 4 processors, Quad-Core Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2 GB
Display: Color LCD, 2880 x 1800 Retina, MirrorOff, Online
Display: PHL 246V5, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB30Bus
USB Device: hub_device
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
USB Device: hub_device
USB Device: USB Audio CODEC
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by RadioDarrenFM** [comment]
I take it there'll be no answers to this then? I can't even sync my iPods with Music/Finder now. Everything is broken.

**Comment by MalboneStreet** [comment]
Same here.  Unfortunately I don't have an answer. A week ago I could sync my classic iPods through Finder, and today they either never get to the Sync button, or hang after the Sync button is clicked.  Running Catalina 10.15.7, by the way.  Tried running maintenance scripts via Onyx, tried rebooting, changing to Disk Mode, etc.  I think the next step is to see if the iPod can be restored and reloaded.  After that -- maybe try switching my Music setup to a Windows machine (!)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
