### ISSUE TITLE
"Unable to write to library 'Aperture Library'"

### ISSUE THREAD

**Issue by thisplantguy** [cormiertyshawn895/Retroactive#326]
![Screenshot 2022-11-14 at 9 02 37 AM](https://user-images.githubusercontent.com/51683498/201721550-1a6bff34-9f17-46f1-a29f-4201464d3f45.png)

Since upgrading to Ventura, every time I try to open up one of my Aperture libraries, I get this message.  I have multiple older Aperture libraries, mostly on external hard drives.  I have made sure my permissions are set to read and write for the libraries; nevertheless, I'm still getting this error.  Does anyone know a good fix for this?

**Comment by ih8quark** [comment]
Make sure you have granted Aperture full disk access in Preferences > Security & Privacy > Full disk access.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
