### ISSUE TITLE
How to Install iTunes 11 (and 10) on Mojave

### ISSUE THREAD

**Issue by ljmac** [cormiertyshawn895/Retroactive#327]
When I first saw this software I was excited by the possibility of installing iTunes 11 on my Mojave Macs, but it seems this can only be done on Catalina. However, if it is possible on Catalina, then surely it must be possible on Mojave too, right? If so, can you tell me how to do this myself, or add this functionality to Retroactive? I am happy if it still has to use the 'guts' of 12.9 - I just want the iTunes 11 UI and library format (for compatibility with my older Macs).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
