### ISSUE TITLE
Ipod won't sync or pop up on ITUNES

### ISSUE THREAD

**Issue by ThaCRAIGGLEZ** [cormiertyshawn895/Retroactive#328]
Is it just me or has anyone's ipod not been able to sync on itunes at all since updating to MacOs Ventura? It worked find when I had MacOs Monterey.

**Comment by CyrusNemani** [comment]
I have a similar problem. I can sync on my intel Macbook Pro running monterey, but not my M1 running ventura. I thought Ventura might be the issue, so i downgraded my M1 to Monterey. I'm getting "cannot read contents of iphone" error message along with a prompt to factory reset the device. Factory reset doesn't help either.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
