### ISSUE TITLE
iTunes not seeing iDevices

### ISSUE THREAD

**Issue by Rysiek13** [cormiertyshawn895/Retroactive#33]
MacOS 10.15.2 Beta (19C46a), iTunes 12.9.5.5 and Retroactive 1.2 and iOS 13.3:

Neither iPhone nor iPad are recognized by iTunes in order to sync them. This is true regardless of using USB or Wi-Fi connection. The Mac is seeing the devices, as they are listed in Finder sidebar without issues.

Is Finder "highjacking" the devices before iTunes can connected to them? Any workaround?

**Comment by Rysiek13** [comment]
Forgot to note: it all worked fine with earlier versions of Catalina.

**Comment by jakes2311** [comment]
I have the same issue, unfortunately. 

Also on MacOS 10.15.2, iTunes 12.9.5.5 and iOS 13.3

**Comment by jakes2311** [comment]
Nevermind, it seems like restarting my computer fixed the issue.

**Comment by Rysiek13** [comment]
Not here - still not seeing devices.

**Comment by cormiertyshawn895** [comment]
If you see "The device is in use by another user on this computer", or nothing happens at all when you plug your device into iTunes:
<img width="602" alt="in-use" src="https://user-images.githubusercontent.com/57056759/75617416-aa6d0880-5b13-11ea-9023-622193684295.png">
- Open Terminal from Spotlight.
- Enter `killall AMPDevicesAgent` and press return.
- While iTunes is open, unplug and plug your iPod nano back in.

**Comment by Rysiek13** [comment]
Thanks. After running the Terminal command my iPad appeared (connected over Wi-Fi), but iPhone Pro 11 did not, even when connected over USB. Running the command again returned No other devices belonging to me.

**Comment by Rysiek13** [comment]
Update: Re-launching iTunes helped! It now shows both devices.

CT, you might want to add that to your instructions.

Thanks again.

**Comment by cormiertyshawn895** [comment]
Added to instructions.
