### ISSUE TITLE
iTunes does not install 

### ISSUE THREAD

**Issue by geolaw** [cormiertyshawn895/Retroactive#330]
mac mini late 2014 - so intel based. 3 GHz Dual-Core Intel Core i7

macOS Monterey 12.6.1

video of the problem I am having
https://www.youtube.com/watch?v=m40wmII7fto

After I click on iTunes to install, it gives me the "what option do you miss the most" - the only option there that does anything is "app store" which will open a pop up video and then macos app store to install Apple configurator.

Also, if I start the app from iterm2 - here is what gets dropped out to the terminal.
glaw@Mac-mini Retroactive 2.0 % ./Retroactive\ \(right\ click\ to\ open\).app/Contents/MacOS/Retroactive
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

Downloaded dictionary Optional(["iTunes129DownloadIdentifier": 061-26589, "iTunes129ExpectedName": InstallESDDmg.pkg, "WikiPage": https://github.com/cormiertyshawn895/Retroactive/wiki, "NewVersionChangelog": • Resolves a problem where iPhoto quits unexpectedly on macOS Monterey 12.3 or later
• Fixes an issue where Full Disk Access cannot be enabled for iTunes on macOS Ventura
• Adds instructions to use iTunes 12.9.5 on Mac computers with Apple Silicon
, "LogicDVDCN": https://www.baidu.com/s?wd=Logic%20Pro%209, "LatestZIP": https://github.com/cormiertyshawn895/Retroactive/releases/download/2.0/Retroactive.2.0.zip, "MainStageUpdate": https://support.apple.com/kb/dl1393, "iTunes114URL": https://secure-appldnld.apple.com/iTunes11/031-06978.20140909.HuRRe/iTunes11.4.dmg, "NewVersionVisibleTitle": Retroactive 2.0 (Build 87) improves compatibility with macOS Ventura and macOS Monterey., "iWork09Update": https://support.apple.com/kb/DL1563, "Xcode114URL": https://developer.apple.com/download/more/?=xcode%2011, "FCPDVDCN": https://www.baidu.com/s?wd=Final%20Cut%20Pro%207, "iTunes129Dive": https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-4?post=27843550#post-27843550, "IssuesPage": https://github.com/cormiertyshawn895/Retroactive/issues?q=, "iTunes126Dive": https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-4?post=27807492#post-27807492, "LatestBuildNumber": 87, "iWork09DVDCN": https://www.baidu.com/s?wd=iWork%2009%20Mac, "NewVersionChangelogzhHans": • 解决了 iPhoto 在 macOS Monterey 12.3 或更高版本中意外退出的问题
• 修复了无法在 macOS Ventura 中为 iTunes 添加完全磁盘访问权限的问题
• 新增了在搭载 Apple 芯片的 Mac 电脑上使用 iTunes 12.9.5 的指导步骤
, "SupportPathURL": https://raw.githubusercontent.com/cormiertyshawn895/Retroactive/master/Retroactive/Support/SupportPath.plist, "iTunes114Dive": https://osxdaily.com/2014/10/26/downgrades-itunes-12/, "iTunes107URL": http://appldnld.apple.com/iTunes10/041-7195.20120912.d3uzQ/iTunes10.7.dmg, "FCPDVD": https://www.ebay.com/sch/i.html?_nkw=Final+Cut+Pro+7, "iTunes129URL": http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallESDDmg.pkg, "NewVersionVisibleTitlezhHans": 新版本解印 2.0 (版本号 87) 改善了与 macOS Ventura 和 macOS Monterey 的兼容性, "ApertureDive": https://medium.com/@cormiertyshawn895/deep-dive-how-does-retroactive-work-95fe0e5ea49e, "iPhotoDive": https://medium.com/@cormiertyshawn895/deep-dive-how-does-retroactive-work-95fe0e5ea49e, "ReleasePage": https://github.com/cormiertyshawn895/Retroactive/releases, "LogicDVD": https://www.ebay.com/sch/i.html?_nkw=Logic+Pro+9, "iTunes107Dive": https://forums.macrumors.com/threads/how-to-safely-re-install-itunes-10-7-in-mavericks.1667115/, "NewIssuePage": https://github.com/cormiertyshawn895/Retroactive/issues/new, "iTunes126URL": https://secure-appldnld.apple.com/itunes12/091-87821-20180912-69177170-B085-11E8-B6AB-C1D03409AD2A/iTunes12.6.5.dmg, "LogicUpdate": https://support.apple.com/kb/dl1601, "iTunes129CatalogURL": https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz, "iWork09DVD": https://archive.org/download/691-6324-A2ZiWork_09_v9.0._Install_DVD_DVD/691-6324-A%2C2Z%2CiWork%20%2709%20v9.0.%20Install%20DVD%20%28DVD%29.iso, "NewVersionChangelogzhHant": • 解決了 iPhoto 在 macOS Monterey 12.3 或更高版本中意外退出的問題
• 修復了無法在 macOS Ventura 中為 iTunes 添加完全磁盤訪問權限的問題
• 新增了在搭載 Apple 芯片的 Mac 電腦上使用 iTunes 12.9.5 的指導步驟
, "ConfiguratorURL": macappstore://apps.apple.com/app/apple-configurator-2/id1037126344, "SourcePage": https://github.com/cormiertyshawn895/Retroactive, "NewVersionVisibleTitlezhHant": 新版本解印 2.0 (版本號 87) 改善了與 macOS Ventura 和 macOS Monterey 的兼容性, "FCPUpdate": https://download.info.apple.com/Mac_OS_X/061-8474.20100915.wtoKR/ProApplicationsUpdate2010-02.dmg])
87, 87
Downloaded dictionary Optional(["NewVersionChangelog": • Resolves a problem where iPhoto quits unexpectedly on macOS Monterey 12.3 or later
• Fixes an issue where Full Disk Access cannot be enabled for iTunes on macOS Ventura
• Adds instructions to use iTunes 12.9.5 on Mac computers with Apple Silicon
, "iTunes129ExpectedName": InstallESDDmg.pkg, "LogicDVD": https://www.ebay.com/sch/i.html?_nkw=Logic+Pro+9, "iWork09Update": https://support.apple.com/kb/DL1563, "iTunes114Dive": https://osxdaily.com/2014/10/26/downgrades-itunes-12/, "iPhotoDive": https://medium.com/@cormiertyshawn895/deep-dive-how-does-retroactive-work-95fe0e5ea49e, "NewVersionChangelogzhHant": • 解決了 iPhoto 在 macOS Monterey 12.3 或更高版本中意外退出的問題
• 修復了無法在 macOS Ventura 中為 iTunes 添加完全磁盤訪問權限的問題
• 新增了在搭載 Apple 芯片的 Mac 電腦上使用 iTunes 12.9.5 的指導步驟
, "MainStageUpdate": https://support.apple.com/kb/dl1393, "NewVersionVisibleTitlezhHans": 新版本解印 2.0 (版本号 87) 改善了与 macOS Ventura 和 macOS Monterey 的兼容性, "iWork09DVD": https://archive.org/download/691-6324-A2ZiWork_09_v9.0._Install_DVD_DVD/691-6324-A%2C2Z%2CiWork%20%2709%20v9.0.%20Install%20DVD%20%28DVD%29.iso, "iTunes126URL": https://secure-appldnld.apple.com/itunes12/091-87821-20180912-69177170-B085-11E8-B6AB-C1D03409AD2A/iTunes12.6.5.dmg, "iWork09DVDCN": https://www.baidu.com/s?wd=iWork%2009%20Mac, "FCPDVDCN": https://www.baidu.com/s?wd=Final%20Cut%20Pro%207, "SourcePage": https://github.com/cormiertyshawn895/Retroactive, "IssuesPage": https://github.com/cormiertyshawn895/Retroactive/issues?q=, "LatestBuildNumber": 87, "iTunes114URL": https://secure-appldnld.apple.com/iTunes11/031-06978.20140909.HuRRe/iTunes11.4.dmg, "SupportPathURL": https://raw.githubusercontent.com/cormiertyshawn895/Retroactive/master/Retroactive/Support/SupportPath.plist, "FCPUpdate": https://download.info.apple.com/Mac_OS_X/061-8474.20100915.wtoKR/ProApplicationsUpdate2010-02.dmg, "NewVersionVisibleTitlezhHant": 新版本解印 2.0 (版本號 87) 改善了與 macOS Ventura 和 macOS Monterey 的兼容性, "NewVersionVisibleTitle": Retroactive 2.0 (Build 87) improves compatibility with macOS Ventura and macOS Monterey., "iTunes129DownloadIdentifier": 061-26589, "LogicDVDCN": https://www.baidu.com/s?wd=Logic%20Pro%209, "NewVersionChangelogzhHans": • 解决了 iPhoto 在 macOS Monterey 12.3 或更高版本中意外退出的问题
• 修复了无法在 macOS Ventura 中为 iTunes 添加完全磁盘访问权限的问题
• 新增了在搭载 Apple 芯片的 Mac 电脑上使用 iTunes 12.9.5 的指导步骤
, "LatestZIP": https://github.com/cormiertyshawn895/Retroactive/releases/download/2.0/Retroactive.2.0.zip, "iTunes129Dive": https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-4?post=27843550#post-27843550, "FCPDVD": https://www.ebay.com/sch/i.html?_nkw=Final+Cut+Pro+7, "ConfiguratorURL": macappstore://apps.apple.com/app/apple-configurator-2/id1037126344, "iTunes129URL": http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallESDDmg.pkg, "NewIssuePage": https://github.com/cormiertyshawn895/Retroactive/issues/new, "ApertureDive": https://medium.com/@cormiertyshawn895/deep-dive-how-does-retroactive-work-95fe0e5ea49e, "iTunes107Dive": https://forums.macrumors.com/threads/how-to-safely-re-install-itunes-10-7-in-mavericks.1667115/, "iTunes126Dive": https://forums.macrumors.com/threads/itunes-12-6-5-3-on-macos-catalina-10-15.2184518/page-4?post=27807492#post-27807492, "Xcode114URL": https://developer.apple.com/download/more/?=xcode%2011, "WikiPage": https://github.com/cormiertyshawn895/Retroactive/wiki, "LogicUpdate": https://support.apple.com/kb/dl1601, "iTunes129CatalogURL": https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz, "iTunes107URL": http://appldnld.apple.com/iTunes10/041-7195.20120912.d3uzQ/iTunes10.7.dmg, "ReleasePage": https://github.com/cormiertyshawn895/Retroactive/releases])
87, 87
Found updated iTunes package: http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallESDDmg.pkg
Clicked on Optional(Retroactive.AppType.itunes)
Made throwaway bundle, /tmp/retroactive/2FBF9A36-8FDC-4878-9D94-BA1559285E47.app/Contents

<< at this point it is at the "what do you miss most" - repeats these next 4 lines whenever I click on 'continue'>>

query all installed apps
query = Optional(<NSMetadataQuery: 0x600000e04d00>)
pred = kMDItemContentTypeTree == "com.apple.application-bundle" AND kMDItemCFBundleIdentifier CONTAINS[c] "com.launcher.iTunes"
query all installed apps
query = Optional(<NSMetadataQuery: 0x600000e05280>)
pred = kMDItemContentTypeTree == "com.apple.application-bundle" AND kMDItemCFBundleIdentifier CONTAINS[c] "com.launcher.iTunes"
query all installed apps
query = Optional(<NSMetadataQuery: 0x600000e04d00>)
pred = kMDItemContentTypeTree == "com.apple.application-bundle" AND kMDItemCFBundleIdentifier CONTAINS[c] "com.launcher.iTunes"

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
