### ISSUE TITLE
No icon for iPhone on iTunes 12.9.5

### ISSUE THREAD

**Issue by Meroniice** [cormiertyshawn895/Retroactive#331]
Since updating to macOS Catalina and installing iTunes 12.9.5, the application does not seem to recognize my iPhone, meaning that there is not the usual icon in the top left corner next to the arrows and dropdown menu nor a separate section on the side list. I've reinstalled iTunes, granted it Full Disk Access, and used the `killall AMPDevicesAgent` command multiple times without success. Additionally, Finder is always the first one to notice my iPhone (obviously) and is repeatedly asking me that "A software update is required to connect to iPhone", which I am not going to do from iOS 14.3 due to various reasons.

Any thoughts or opinions on what's the next step I should take?

**Comment by JNGLHAUS** [comment]
I think this has to do with the current iOS you are on, I noticed that my iPhone on 15.7.8 stopped showing in iTunes but a backup I have on 12.5.7 still reads fine - I guess Apple just figured no one is using iTunes anymore so dropped the ability to sync on newer OS builds. You should be able to still get the iPhone to show in Finder without downloading the software update, then (sad face) use the Music app to sync music moving forward.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
