### ISSUE TITLE
iTunes 10 & 11 crashing on Ventura

### ISSUE THREAD

**Issue by Bye-Ya** [cormiertyshawn895/Retroactive#332]
Hello, iTunes 10 & 11 crashes on Ventura upon changing preferences, and also sometimes when connecting iPods. Previously, iTunes 11 was working with Monterey.

**Comment by jdp5555** [comment]
Seeing this also (with iTunes 10.7) - was working fine with Monterey.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
