### ISSUE TITLE
Logic Pro - Waveburner

### ISSUE THREAD

**Issue by mikeuwins** [cormiertyshawn895/Retroactive#333]
Would it be possible to unlock other packages in Logic Studio?  It would be amazing if Waveburner could be unlocked for Mojave.

**Comment by almeidamiguel79** [comment]
YES! Please make this available!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
