### ISSUE TITLE
iTunes 11 - Downgrade 12 to 11 but preserve library (mostly playcounts, lyrics)

### ISSUE THREAD

**Issue by wongjustin99** [cormiertyshawn895/Retroactive#334]
Is there a way to downgrade my itunes library file? 

I get a prompt to create a new one on launch, but I would much prefer to just downgrade my existing one, migrate the play counts/lyrics, and continue on.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
