### ISSUE TITLE
Aperture crashes in toolbar edit mode

### ISSUE THREAD

**Issue by foxnoodles** [cormiertyshawn895/Retroactive#335]
Just right click on top toolbar and go to customize. Scroll through the icons. App will crash. 

Ventura 13.0.1

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
