### ISSUE TITLE
iTunes (any version) doesn't work despite appearing to successfully install - Intel Mac, Monterey 12.6.1.

### ISSUE THREAD

**Issue by TheOnlineUser** [cormiertyshawn895/Retroactive#336]
Installation completes but clicking "Launch iTunes" does nothing. Launching manually from the Applications folder brings up an error that says "The application "iTunes" can't be opened."

Intel Mac. Monterey 12.6.1.

**Comment by ghost** [comment]
same issue with me when i updated from monterey to ventura it will just say itunes quit and not open up at all so idk if this app still works anymore it was nice to have legacy itunes on the newer mac os though

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
