### ISSUE TITLE
iTunes (version 12.9.5 & 12.6.5) doesn't work despite appearing to successfully install - Intel Mac, Monterey 12.6.1

### ISSUE THREAD

**Issue by n0yes** [cormiertyshawn895/Retroactive#337]
First I installed the older 11.4 version of iTunes successfully.

Then I tried to to instal both newer versions available, 12.9.5 & 12.6.5. The install seems successful but when I click to open the app it says "iTunes quit unexpectedly".

**Comment by dhannymaister** [comment]
The same happens to me (Intel, Ventura 13.1)

**Comment by ghost** [comment]
same as well on ventura does not work for me

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
