### ISSUE TITLE
Logic 9 support - Retroactive 2.0

### ISSUE THREAD

**Issue by cyberishh** [cormiertyshawn895/Retroactive#338]
Hi!
first of all thank you for your work. 
Did you change the Logic 9 support for Mojave in Retroactive 2.0 to get rid of its "experimental" status?
In 1.9. I coudn't load any Logic 9 file saved through "Retroactive" to load into a "normal" Logic 9 on an older system. 
It loaded fine into  Logic X indeed.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
