### ISSUE TITLE
DNG files showing as "Unsupported Image Format"

### ISSUE THREAD

**Issue by piggystardust** [cormiertyshawn895/Retroactive#339]
I've converted my CR2 files to DNGs that should be compatible with Camera Raw 2.4 and later (I think the highest Aperture ever went was Camera Raw 6.2?) so they should absolutely work. Has anyone had success with getting it to display raw/dng files correctly?

**Comment by minaindrek** [comment]
You mean in Monterey? In Big Sur it works fine, as I remember. Nikon raw, I mean...

**Comment by piggystardust** [comment]
Actually, in Ventura. The camera I shoot with primarily isn't supported by Aperture, so I converted some of the .cr2 (Canon raw format) files to DNG in Lightroom. There's a compatibility setting that lets you create DNGs that are compatible with Camera RAW back to 2.4, but Aperture still can't read them. I've reprocessed them multiple times and I still get the "Unsupported Image Format" message.

**Comment by minaindrek** [comment]
My camera is supported, but I get 'unsupported image format' in Monterey, no matter how many times I reprocess them. In Big Sur reprocessing works, and images show up.

**Comment by g7uvw** [comment]
I'm also getting unsupported image format with Nikon RAW files (D7000 camera) in Monterey. A preview shows in the film strip on the bottom of the screen, but going to a full view of the image causes the unsupported format message.

**Comment by piggystardust** [comment]
That's exactly how it's happening for me, too. The thumbnails are fine, but when I try to open it full size, I get the Unsupported format message on both the full image and the preview.

**Comment by nolap-bl** [comment]
I have the same problem with any kind of raw files (Canon, Fujifilm, Leica). I had it under Catalina and still have it under Monterey. Previews are correctly displayed but selecting any preview image from the film strip is always displaying a black image with the "Unsupported image format message" and is... removing the preview, replacing it with a black image. The only way if found to keep my preview files is to disconnect every external disk where the raw images are located. So I can at least browse and display the previews...

**Comment by stolendata** [comment]
I have the same problem on Monterey when trying to import new RAW .NEF files from my Nikon D5100. Aperture could read and process them fine back on Mojave and Catalina, but now it seems it cannot access macOS' RAW profiles to interpret the files. They do load in Preview and Photos, however.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
