### ISSUE TITLE
iTunes 12.9.5.5 - Cannot play music stored on shared volume 

### ISSUE THREAD

**Issue by safetyABJ** [cormiertyshawn895/Retroactive#34]
Playing music stored on a shared volume, which is how I managed my library on pre-Catalina OS's, results in a spinning wheel of death and a force quit is required. Sometimes the spinning wheel stops and iTunes become responsive again but the track does not play. My iTunes library folder is still kept on the local drive, just the music media is store on a shared volume. 

'Song Info' and 'Show in Finder' function normally so iTunes is referencing the files correctly. 

Music.app will play music stored on a shared volume.

Catalina 10.15.1

**UPDATE
This issue happen when using an existing iTunes library. If I add new tracks to the library or create a new one then music stored on a shared volume will play correctly.

**UPDATE 2
OK, after adding new tracks to the library, the existing tracks are now playing correctly. It seems updating the library fixed whatever was at issue.

**Comment by cormiertyshawn895** [comment]
If iTunes is unable to play media located on an external storage media or network drive:
- Re-install iTunes [using the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/).
- After re-installing iTunes, Retroactive will ask you about iPod syncing. Click "Enable Full Disk Access", and follow on-screen instructions provided by Retroactive. **Enabling Full Disk Access will fix both iPod syncing and music playback on external drives or shared volumes**.

![7a](https://user-images.githubusercontent.com/57056759/75648829-2182c980-5c06-11ea-8ee7-7a8a0eacfd2f.jpg)
