### ISSUE TITLE
All iTunes crash in macosVentura

### ISSUE THREAD

**Issue by RacsoLeinad** [cormiertyshawn895/Retroactive#341]
I tried to download every single iTunes but they all crash when i try to open them after a succesful installation :( I really need iTunes the Music app is absolutely bad and works so damn slow I'm pretty sure on purpose to force you to use their streaming service.
Please can someone help me with this issue?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
