### ISSUE TITLE
iTunes fails to launch and gives error code -42408 in MacOS 13.1

### ISSUE THREAD

**Issue by nic-rad** [cormiertyshawn895/Retroactive#342]
<img width="477" alt="Screenshot 2023-01-12 at 11 46 40 AM" src="https://user-images.githubusercontent.com/122566274/212165997-d2d4df57-b9b4-4674-99ae-2f788f1c5a18.png">

After updating to MacOS 13.1 on a MacBook Pro with M1 Pro chip, iTunes crashes on launch and gives the above error code. 

Troubleshooting steps I've already taken:
- Power cycled Macbook
- Uninstalled iTunes and reinstalled from Retroactive
- Uninstalled Retroactive and reinstalled from github
- Disabled Gatekeeper and uninstalled/reinstalled again

**Comment by herbievine** [comment]
My iTunes works and am able to play songs in my Library, but once I plug in my iPod it crashes immediately... 

<img width="513" alt="Screenshot 2023-01-24 at 20 07 41" src="https://user-images.githubusercontent.com/41120535/214385580-e17263ce-9739-41e7-8ad3-37ffd72f821b.png">

Env:
 - Running classic iTunes
 - Fresh install of Ventura 13.2 (22D49)
 - Apple M1
 
 Same as above for troubleshoot steps...

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
