### ISSUE TITLE
Cannot launch iTunes 12.9.5 via Retrospective 2.0 on Big Sur 11.7.2

### ISSUE THREAD

**Issue by h8zgray** [cormiertyshawn895/Retroactive#343]
Good evening, following the seemingly successful installation of iTunes 12.9.5 via Retrospective 2.0 and then 1.9, the iTunes app would not launch and generated the following report, running Big Sur 11.7.2 on Mac Pro 5,1 through OpenCore Legacy Patcher, any assistance would be most appreciated, thank you in advance. :

Process:               iTunes [5573]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        ??? [5570]
User ID:               501

Date/Time:             2023-01-17 18:14:47.777 -0500
OS Version:            macOS 11.7.2 (20G1020)
Report Version:        12
Anonymous UUID:        1BE42248-DA78-41A8-B0D2-5082882C5050

Sleep/Wake UUID:       9B66EC33-DCA6-42AA-88C0-C81D342C2646

Time Awake Since Boot: 8600 seconds
Time Since Wake:       3400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries, ignoring DYLD_* env vars
@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib

Dyld Error Message:
  dyld: Using shared cache: 65C1D716-2D5B-3211-901B-C837A3BF1722
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
  Referenced from: /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
  Reason: unsafe use of @executable_path in /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes with restricted binary (Codesign main executable with Library Validation to allow @ paths)

Binary Images:
       0x1073a6000 -        0x1090d0fff  com.apple.iTunes (12.9.5 - 12.9.5) <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
       0x118a4f000 -        0x118aeafff  dyld (852.2) <E2635A72-BF2F-330E-9CA6-4A65733FF15D> /usr/lib/dyld
    0x7fff20dbf000 -     0x7fff20e3cfff  com.apple.SystemConfiguration (1.20 - 1.20) <D59BEA1F-BD5D-383A-8977-64F5B72F16C4> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff210ab000 -     0x7fff21409fff  com.apple.Foundation (6.9 - 1778.105) <554959E4-F9FB-3F67-8CC6-196159ED6CC1> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21a81000 -     0x7fff22112fff  com.apple.audio.CoreAudio (5.0 - 5.0) <A5ED9C97-E177-388F-AED8-D760C6963377> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff22113000 -     0x7fff2246afff  com.apple.security (7.0 - 59754.141.1.7.1) <BE535B6D-0189-3EBE-A68C-7F3634BD8C89> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff22a3b000 -     0x7fff22ae9fff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <A395F442-1253-3CA9-953F-7A235EEB7F67> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff24b1f000 -     0x7fff24e84fff  com.apple.SkyLight (1.600.0 - 588.10) <78FFC855-8FB8-300B-878C-174F019DBA94> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff25e79000 -     0x7fff26027fff  libsqlite3.dylib (321.3) <2F64DF10-A0EF-3D85-83B8-A4AD38A2069A> /usr/lib/libsqlite3.dylib
    0x7fff26028000 -     0x7fff260a4fff  com.apple.Accounts (113 - 113) <1021C0F9-F834-33DB-A66D-EE4391C58740> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff264b1000 -     0x7fff264b7fff  com.apple.DiskArbitration (2.7 - 2.7) <21325211-A5F7-3AB9-BDFE-6B6DC06E587E> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff26e24000 -     0x7fff27101fff  com.apple.QuartzCore (1.11 - 927.24) <A1FBBC37-D008-34E6-B034-6AF1856C8E2A> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff27144000 -     0x7fff27284fff  com.apple.coreui (2.1 - 692.1) <AEA9DF7F-4E7E-3D39-9DBF-55276520B97C> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff27285000 -     0x7fff27370fff  com.apple.ViewBridge (553.1 - 553.1) <AC1840D6-7482-385E-ABDF-5BE8DC38C612> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff2755e000 -     0x7fff27585fff  com.apple.aps.framework (4.0 - 4.0) <AB586FD6-9C10-323B-A585-DCB42153B8E2> /System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService
    0x7fff28683000 -     0x7fff2876dfff  com.apple.CoreMedia (1.0 - 2780.10.4.1.1) <237F9A0B-FE1F-3E4D-BE4D-8E27989EA845> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff29b65000 -     0x7fff29d66fff  com.apple.CoreUtils (6.6 - 660.37) <7612F523-6889-3A99-B54E-E6E1953FC7AC> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff2a414000 -     0x7fff2a543fff  com.apple.AuthKit (1.0 - 1) <C678E6CB-DAE9-3AD0-9AA2-9D192426C184> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff2b14c000 -     0x7fff2b15ffff  com.apple.CrashReporterSupport (10.13 - 15053.1) <146251D8-7623-3944-86B2-36EE47BD982E> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff2ce74000 -     0x7fff2cfa8fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <99F6F2D8-189D-398C-A38C-B6B49F66A6E8> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2db43000 -     0x7fff2dc0afff  com.apple.SoftwareUpdate.framework (6 - 1418.140.14) <504E1428-F122-37D1-8AEB-2793A59159E9> /System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/SoftwareUpdate
    0x7fff300e2000 -     0x7fff30107fff  com.apple.GLKit (124 - 124) <6C0F67C0-2417-36AA-9638-B06CDDB6AF63> /System/Library/Frameworks/GLKit.framework/Versions/A/GLKit
    0x7fff301a0000 -     0x7fff301a0fff  com.apple.CoreServices (1122.45 - 1122.45) <F58134D0-6EDB-351B-9F5B-4337456D02B1> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3035c000 -     0x7fff3035cfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <AD3EDAFF-40D8-31B0-85F6-F3772B784D87> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff3039d000 -     0x7fff303a8fff  com.apple.MediaAccessibility (1.0 - 130) <92C16B96-57FF-3C72-8532-A1D01DAB02F6> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff30a42000 -     0x7fff30b76fff  com.apple.contacts (1.0 - 3497.6) <4C0A7F42-6148-3A6C-BD64-E70F02757BE7> /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
    0x7fff30c2e000 -     0x7fff30cd6fff  com.apple.DiscRecording (9.0.3 - 9030.4.5) <2EB0A304-1C88-350B-BDFA-B9F73767D44C> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff31a52000 -     0x7fff31a97fff  com.apple.CryptoTokenKit (1.0 - 1) <91ED10F4-1CCE-322B-B4DF-95310078D8A8> /System/Library/Frameworks/CryptoTokenKit.framework/Versions/A/CryptoTokenKit
    0x7fff31a98000 -     0x7fff31aaefff  com.apple.LocalAuthentication (1.0 - 827.140.1) <1DD09173-CEE5-3014-B9D3-CE7B455A46B4> /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication
    0x7fff31add000 -     0x7fff31b50fff  com.apple.avfoundationcf (2.0 - 430.4.1) <91503D08-0929-3ED2-A3CB-42B11A759985> /System/Library/PrivateFrameworks/AVFoundationCF.framework/Versions/A/AVFoundationCF
    0x7fff3353d000 -     0x7fff3357cfff  com.apple.AppleIDSSOAuthentication (1.0 - 1) <F13FBCB8-FF0E-3F73-AEC0-3B85AFABC192> /System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/Versions/A/AppleIDSSOAuthentication
    0x7fff335d5000 -     0x7fff33668fff  com.apple.AuthKitUI (1.0 - 1) <8B2C17A8-D463-36CD-9B96-1FA810A5AB1C> /System/Library/PrivateFrameworks/AuthKitUI.framework/Versions/A/AuthKitUI
    0x7fff33743000 -     0x7fff33743fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <1A2C9DDE-749F-3134-9F0A-2BC6C4E08AC0> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff34194000 -     0x7fff34226fff  com.apple.framework.ConfigurationProfiles (13.3 - 1360) <5046265D-AFDE-3349-AA4C-42F02D8EBB31> /System/Library/PrivateFrameworks/ConfigurationProfiles.framework/Versions/A/ConfigurationProfiles
    0x7fff343d2000 -     0x7fff34426fff  com.apple.AOSAccounts (1.3.1 - 167) <44286EC2-4735-33E5-B4AB-EEDC6AA7CFDD> /System/Library/PrivateFrameworks/AOSAccounts.framework/Versions/A/AOSAccounts
    0x7fff35173000 -     0x7fff35176fff  com.apple.Cocoa (6.11 - 23) <327C9AC4-58C4-374F-9ADA-D2E7781BE7CD> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff351c0000 -     0x7fff355b4fff  com.apple.AppleMediaServices (1.0 - 1) <C100D8AD-4FF1-383A-B5A1-9143599C3A19> /System/Library/PrivateFrameworks/AppleMediaServices.framework/Versions/A/AppleMediaServices
    0x7fff355ec000 -     0x7fff35a64fff  com.apple.MediaRemote (1.0 - 1) <E8E4CE32-CEAA-3CE0-BA8E-A8BA6D27C220> /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
    0x7fff36647000 -     0x7fff37837fff  com.apple.JavaScriptCore (16611 - 16611.3.10.1.16) <1BFD0E80-A547-3B0B-8F7B-813D4AE888E2> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff38dfe000 -     0x7fff38e77fff  com.apple.CoreRecognition (1.3 - 157) <E53CFEE0-2037-3ABE-8C5D-49EC8CA64282> /System/Library/PrivateFrameworks/CoreRecognition.framework/Versions/A/CoreRecognition
    0x7fff3c209000 -     0x7fff3c9e8fff  com.apple.WebKit (16611 - 16611.3.10.1.16) <0DEBC559-21C8-395D-9FE7-7BA46096B54D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff3cb9f000 -     0x7fff3cba2fff  com.apple.Carbon (160 - 164) <773D71A4-48F0-3692-9C77-E855373EEAF2> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3cc9b000 -     0x7fff3cc9bfff  com.apple.avfoundation (2.0 - 2020.10) <2C4E94A8-C729-35ED-9FAA-BF8CA015BF97> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3cc9c000 -     0x7fff3cdb6fff  com.apple.AVKit (1.1 - 732.4.8) <CFCF856D-9DE6-3F4A-9DB8-DC890BC787D4> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3d674000 -     0x7fff3d6b1fff  com.apple.BiometricKit (1.0 - 233.140.1) <17B0F365-8172-32E4-BAD5-7E78C25E696D> /System/Library/PrivateFrameworks/BiometricKit.framework/Versions/A/BiometricKit
    0x7fff3d951000 -     0x7fff3dbacfff  com.apple.imageKit (3.0 - 1100) <43D614A4-5690-3BAB-9D3D-4DB9A88B8F6A> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
    0x7fff3dce5000 -     0x7fff3dd07fff  com.apple.OnBoardingKit (1.0 - 1) <EF0DDA02-6871-3FF3-A4C8-2C7DBF7C0207> /System/Library/PrivateFrameworks/OnBoardingKit.framework/Versions/A/OnBoardingKit
    0x7fff3fc8a000 -     0x7fff3fce1fff  com.apple.CommerceKit (1.2.0 - 711.6.2) <DC99A07D-2AF7-348E-91BC-A3B042A16A1A> /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/CommerceKit
    0x7fff40cff000 -     0x7fff40d56fff  com.apple.StoreFoundation (1.0 - 711.6.2) <4966D4D3-63B8-36F2-BF7A-7D26768127B8> /System/Library/PrivateFrameworks/StoreFoundation.framework/Versions/A/StoreFoundation
    0x7fff4104d000 -     0x7fff41050fff  com.apple.quartzframework (1.5 - 25) <2310DC09-18DF-3798-BCAC-3CD8E085BE00> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff4a58f000 -     0x7fff4a595fff  com.apple.PIP (1.0 - 109) <112EF194-F08C-3F22-82D4-E16AB6171B76> /System/Library/PrivateFrameworks/PIP.framework/Versions/A/PIP
    0x7fff4aff1000 -     0x7fff4aff8fff  com.apple.iPod (1.7 - 25) <54421D0E-5156-33B5-BC24-FD499AFC2216> /System/Library/PrivateFrameworks/iPod.framework/Versions/A/iPod
    0x7fff6bb1f000 -     0x7fff6bb2efff  com.apple.opengl (18.5.9 - 18.5.9) <610E765C-8C0D-3422-AD6E-636D3EBD2AD0> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6e28c000 -     0x7fff6e293fff  com.apple.agl (3.3.4 - AGL-3.3.3) <BE049FFB-FE46-3811-9A6C-688FA6BBC557> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff75770000 -     0x7fff757d4fff  com.apple.iTunes.iPodUpdater (306 - 306) <8DDC558F-BE0E-312B-BB55-9771036B5C7E> /System/Library/PrivateFrameworks/iPodUpdater.framework/Versions/A/iPodUpdater

Model: MacPro5,1, BootROM 9999.999.999.999.999, 12 processors, 6-Core Intel Xeon, 3.46 GHz, 64 GB, SMC 9.9999
Graphics: AMD Radeon RX 580, AMD Radeon RX 580, spdisplays_pcie_device, 8 GB
Memory Module: DIMM 1, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 2, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 3, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 4, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 5, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 6, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 7, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
Memory Module: DIMM 8, 8 GB, DDR3, 1333 MHz, 0x80CE, 0x4D33393342314B37304348442D5948392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x14A), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 18 devices, 1 incoming serial ports
Network Service: Ethernet 2, Ethernet, en1
PCI Card: AMD Radeon RX 580, sppci_displaycontroller, Slot-1
PCI Card: pci1002,aaf0, sppci_audiodevice, Slot-1
PCI Card: PXS3, sppci_usbxhci, Slot-3
PCI Card: pci1179,11a, sppci_nvme, Slot-2@15,0,0
PCI Card: pci144d,a808, sppci_nvme, Slot-2@16,0,0
PCI Card: pci1b73,1100, sppci_usbxhci, Slot-4@6,0,0
PCI Card: pci1b73,1100, sppci_usbxhci, Slot-4@8,0,0
PCI Card: pci1b73,1100, sppci_usbxhci, Slot-4@7,0,0
PCI Card: pci1b73,1100, sppci_usbxhci, Slot-4@9,0,0
Serial ATA Device: HL-DT-ST BD-RE  WH16NS40
Serial ATA Device: HL-DT-ST BD-RE  WH16NS40
Serial ATA Device: ST8000VN0022-2EL112, 8 TB
Serial ATA Device: WDC WD20EZRX-00D8PB0, 2 TB
Serial ATA Device: Crucial_CT1024MX200SSD1, 1 TB
USB Device: USB 3.0 Bus
USB Device: USB 3.0 Bus
USB Device: Hub
USB Device: DELL PROFESSIONAL SOUND BAR AE515
USB Device: Apple Cinema HD Display
USB Device: USB 3.0 Bus
USB Device: USB 3.0 Bus
USB Device: USB2.0 HUB
USB Device: Brio 500
USB Device: OMNIKEY 3x21 Smart Card Reader
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB3.0 Card Reader
USB Device: USB 2.0 Bus
USB Device: USB2.0 Hub
USB Device: Matias Keyboard
USB Device: USB 2.0 Bus
USB Device: USB Bus
USB Device: USB Bus
USB Device: Kensington Expert Mouse
USB Device: USB Bus
USB Device: USB Bus
USB Device: Bluetooth USB Host Controller
USB Device: USB Bus
USB Device: USB Bus
FireWire Device: built-in_hub, Up to 800 Mb/sec
FireWire Device: iSight, Apple Computer, Inc., Up to 200 Mb/sec
FireWire Device: unknown_device, Unknown
Thunderbolt Bus:

**Comment by masak2009** [comment]
Same issue on Catalina 10.15.7 with same iTunes 12.9.5:
```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries, ignoring DYLD_* env vars
@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
  Referenced from: /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
  Reason: unsafe use of @executable_path in /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes with restricted binary (Codesign main executable with Library Validation to allow @ paths)

Binary Images:
       0x1066ee000 -        0x108418fe7  com.apple.iTunes (12.9.5 - 12.9.5) <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
       0x116176000 -        0x116208267  dyld (750.7) <9F48F7F8-94D0-3793-99B7-DDEF657EF956> /usr/lib/dyld
    0x7fff28b66000 -     0x7fff28b6affb  com.apple.agl (3.3.3 - AGL-3.3.3) <D5670F33-361F-3971-9382-290BB12EA788> /System/Library/Frameworks/AGL.framework/Versions/A/AGL

```

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
