### ISSUE TITLE
iTunes crash on every startup

### ISSUE THREAD

**Issue by nikbex-sno** [cormiertyshawn895/Retroactive#344]
This is happening everytime I start iTunes

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iTunes [7306]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [7303]
User ID:               501

Date/Time:             2023-02-01 12:18:04.7278 +0000
OS Version:            macOS 13.2 (22D49)
Report Version:        12
Anonymous UUID:        00588830-4C5F-A187-E21E-7BB71B0C3C0F

Sleep/Wake UUID:       8BBF9EE4-E58C-4ECF-8E79-F748F5830183

Time Awake Since Boot: 6700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff818cccb4a __abort_with_payload + 10
1   dyld                          	    0x7ff818ce5d07 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff818ce5d39 abort_with_payload + 9
3   dyld                          	    0x7ff818c6d1e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff818c6a660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff818c69281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bb1933c8  rdx: 0x00007ff7bb193830
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bb193410  rsp: 0x00007ff7bb1933c8
   r8: 0x00007ff7bb193430   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7bb193830  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff818cccb4a  rfl: 0x0000000000000246  cr2: 0x0000000106f35000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
    0x7ff818c63000 -     0x7ff818cf7caf dyld (*) <270c4224-a38f-3a22-9ba9-95968f487738> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=212.3M resident=0K(0%) swapped_out_or_unallocated=212.3M(100%)
Writable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            3487K        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       182.6M        2 
__TEXT                            29.8M        2 
dyld private memory                512K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            280.2M       16 

-----------
Full Report
-----------

{"app_name":"iTunes","timestamp":"2023-02-01 12:18:04.00 +0000","app_version":"12.9.5","slice_uuid":"91006ee5-c8c4-3a53-b7f7-69a3b2fd991a","build_version":"12.9.5","platform":1,"bundleID":"com.apple.iTunes","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2 (22D49)","roots_installed":0,"name":"iTunes","incident_id":"DA1D2CAE-8A12-4651-B27D-AB352D8439AD"}
{
  "uptime" : 6700,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iMac14,1",
  "coalitionID" : 8653,
  "osVersion" : {
    "train" : "macOS 13.2",
    "build" : "22D49",
    "releaseType" : "User"
  },
  "captureTime" : "2023-02-01 12:18:04.7278 +0000",
  "incident" : "DA1D2CAE-8A12-4651-B27D-AB352D8439AD",
  "pid" : 7306,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-02-01 12:18:04.7180 +0000",
  "procStartAbsTime" : 6767483215955,
  "procExitAbsTime" : 6767492881574,
  "procName" : "iTunes",
  "procPath" : "\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes",
  "bundleInfo" : {"CFBundleShortVersionString":"12.9.5","CFBundleVersion":"12.9.5","CFBundleIdentifier":"com.apple.iTunes"},
  "buildInfo" : {"ProjectName":"iTunes","SourceVersion":"1200012009005005","BuildVersion":"9"},
  "storeInfo" : {"deviceIdentifierForVendor":"C83C096E-6190-50EC-835B-3B59532F1856","thirdParty":true},
  "parentProc" : "Exited process",
  "parentPid" : 7303,
  "coalitionName" : "com.launcher.iTunes",
  "crashReporterKey" : "00588830-4C5F-A187-E21E-7BB71B0C3C0F",
  "responsiblePid" : 7303,
  "sleepWakeUUID" : "8BBF9EE4-E58C-4ECF-8E79-F748F5830183",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib","Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> \/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes","Reason: tried: '\/System\/Volumes\/Preboot\/Cryptexes\/OS@executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib' (no such file), '\/usr\/lib\/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":94459,"threadState":{"r13":{"value":140701972641840},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701972640816},"cr2":{"value":4411576320},"rdx":{"value":140701972641840},"r10":{"value":150},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703544691530,"matchesCrashFrame":1},"rbp":{"value":140701972640784},"rsp":{"value":140701972640712},"r12":{"value":150},"rcx":{"value":140701972640712},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":432970,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":0},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703544258560,
    "size" : 609456,
    "uuid" : "270c4224-a38f-3a22-9ba9-95968f487738",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703543652352,
  "size" : 21474836480,
  "uuid" : "61138b36-7859-3add-9c47-7e7cd2a358d0"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=212.3M resident=0K(0%) swapped_out_or_unallocated=212.3M(100%)\nWritable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                            3487K        3 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       182.6M        2 \n__TEXT                            29.8M        2 \ndyld private memory                512K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            280.2M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000247
    },
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "63c7a8807b814a4e084bc5d3",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000602
    }
  ],
  "experiments" : [

  ]
}
}

Model: iMac14,1, BootROM 433.140.2.0.0, 4 processors, Quad-Core Intel Core i5, 2.7 GHz, 16 GB, SMC 2.14f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Display: iMac, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142314737334442302D594B302020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142314737334442302D594B302020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x111), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1766)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@195,0,0
Serial ATA Device: ST1000LM048-2E7172, 1 TB
USB Device: USB30Bus
USB Device: AS2115
USB Device: USB3.0 Hub
USB Device: ASMT1051
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB2.0 Hub
FireWire Device: Rugged FW/USB, LaCie, 800mbit_speed
Thunderbolt Bus: iMac, Apple Inc., 23.10
Thunderbolt Device: Thunderbolt to FireWire Adapter, Apple Inc., 1, 5.6

**Comment by nikbex-sno** [comment]
VENTURA 13.2

**Comment by anthonymvillar** [comment]
Same thing's happening to me, running os: Ventura 13.2 on my MacBook Air 2017

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
