### ISSUE TITLE
FCP 7.0.3 Mojave: Canvas and Viewer window to dark

### ISSUE THREAD

**Issue by Techy2023** [cormiertyshawn895/Retroactive#345]
On both Mac's with Mojave the same issue. The video apears to dark on the Viewer and Canvas window! The darker the picture is, the worse the effect happen. Very bright pictures seams almost to be ok. But the darker parts of a picture are to dark. Very weird effect. This also applies to additionally added elements such as graphics, text or video transitions. The video files are still ok, and also rendering and file export works fine, but the two windows has this permanent issue. I have two MacMinis (late '12) with Mojave. Same problem on both mac's. Have also tried different monitors (all full HD) but it didn't help. Is there a solution for that? Thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
