### ISSUE TITLE
Enable hot keys when Retroactive is running?

### ISSUE THREAD

**Issue by Veronykah** [cormiertyshawn895/Retroactive#346]
Installed with no issues - how do I enable to music hot keys to work with retroactive?
The play/forward/back keys (f7/f8/f9) keep opening music not sure if its possible to use them if Retroactive iTunes is open as the preferred app.

**Comment by daeongithub** [comment]
Would also love to figure out how to do this, as I use iTunes only now and don't really use the Music app anymore unless I have to buy something from the iTunes store.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
