### ISSUE TITLE
FCP7 error: out of memory

### ISSUE THREAD

**Issue by mattsupersad** [cormiertyshawn895/Retroactive#347]
Hi Tyshawn,

Thanks so much for Retroactive - I've now updated my old OS to Mojave 10.14.6, have installed Retroactive 2, and have been able to open up old FCP7 projects. However, whenever I try to open a sequence (the app opens with only the Browser visible), I get the same error message every time:
"Error: out of memory"

Do you know if there's any fix for this? I'd really like to be able to edit my old projects. 

My spec:
Mac Pro (Early 2009)
3.2 GHz Quad-Core Intel Xeon
32 GB 1333 MHz DDR3
AMD Radeon HD 7950 3 GB (new/refurbished graphics card recently installed)

I'd be so grateful if you could help. 
Thanks,
Matt

**Comment by mattsupersad** [comment]
Hello again,
I've just been able to get my old projects working! I reactivated FCP7 from within Retroactive, which I'd done previously, and reinstalled pro video formats 2.2.4 (again, done previously), and for some reason it's now working!

Best,
Matt

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
