### ISSUE TITLE
Aperture “Unsupported Image Format”

### ISSUE THREAD

**Issue by R-S-T** [cormiertyshawn895/Retroactive#348]
All my photos show as “Unsupported Image Format”. Reprocessing the photo does not change that. Tried that even more than 2 times, still shows as unsupported. 
This is all Nikon D500 RAW images. I am running OS 13.2.1

Any suggestions?

**Comment by ih8quark** [comment]
Having the same issue on Canon 5Ds images in Monterey 12.6.8

**Comment by shep713** [comment]
Me too. I have Olympus RAW .ORF pictures. The image shows for 1/2 second then becomes "unsupported image format".
Reprocessing the photos does not fix this. Only occurs with RAW images.
I'm using Ventura 13.5.1 and Retroactive 2.0.
Thanks for all your work to make Retroactive work again on Aperture. I hope you can fix this issue too!  :-)

jpegs show up just fine, but most of my pics are RAW.

**Comment by R-S-T** [comment]
Has anyone tested the new release 2.1 with Aperture on 13.6.6 M1/2/3 machines and can confirm the "unsupported image format" problem is solved?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
