### ISSUE TITLE
Migrate Podcasts files back to iTunes Location

### ISSUE THREAD

**Issue by kun44l** [cormiertyshawn895/Retroactive#349]
Hello all,

Firstly, Thank you for providing this wonderful app !!

I upgraded to Catalina and my concern for using iTunes on a NAS location was resolved with retroactive.
However, after I setup iTunes for my music, I stupidly opened the Podcasts app (just to see the features).
The Podcasts app then moved some of my podcast files to /Users/<USER>/Library/Group Containers/243LU875E5.groups.com.apple.podcasts/Library/Cache

Is there any way to migrate these files back to /<iTunes-root-folder>/Podcasts

Thanks.

**Comment by kun44l** [comment]
After a bit of digging around, I found that there a sqlite db file which contains the the mapping from the podcast file named in a UUID format to the name of the podcast and other details. This is in the "ZMTEPISODE" table in the database.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
