### ISSUE TITLE
iPod classic user issue

### ISSUE THREAD

**Issue by sztenni** [cormiertyshawn895/Retroactive#35]
When I connect the iPod classic to iTunes, an alert says that the iPod is already used by another user and can't be connected. How can I solve this?

**Comment by dirtlwyr** [comment]
iTunes downloaded fine (thanks!), but once installed it will not allow my iPod classic to sync.  Multiple error messages.  This significant lack of functionality should be clear on your front page to warn potential users before they spend the time and effort to install a less than full-functioning iTunes product.  No offense - I understand this is a open, collaborative effort.

**Comment by cormiertyshawn895** [comment]
### If you see "The iPod is in use by another user on this computer", or nothing happens at all when you plug your iPod into iTunes:
<img width="602" alt="in-use" src="https://user-images.githubusercontent.com/57056759/75617416-aa6d0880-5b13-11ea-9023-622193684295.png">

- Disconnect the device from your Mac, but keep iTunes open.
- Click on the Spotlight icon (magnifying glass) on the menu bar.
- Type "Terminal" and press return to open the Terminal app.
- Enter `killall AMPDevicesAgent` in the Terminal window, and press return.
- Connect the Apple device back to your Mac.

---
### If you see "iTunes cannot read the contents of the iPod. Go to the Summary tab in iPod preferences and click Restore to restore this iPod to factory settings":
<img width="602" alt="cannot-read" src="https://user-images.githubusercontent.com/57056759/75617419-ae008f80-5b13-11ea-85e7-17ffb4bc907a.png">

- Re-install iTunes [using the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/).
- After re-installing iTunes, Retroactive will ask you about iPod syncing. Click "Enable Full Disk Access", and follow on-screen instructions provided by Retroactive.

![7a](https://user-images.githubusercontent.com/57056759/75648829-2182c980-5c06-11ea-8ee7-7a8a0eacfd2f.jpg)

---
### If you try to enable VoiceOver for iPod shuffle, but see "iTunes was unable to install the VoiceOver Kit. An unknown error occurred (1701)":

- [Directly download the VoiceOver 1.4.2 installer here](https://swdist.apple.com/content/downloads/29/37/041-91732-A_LSWLP6NLRV/bk8l36k29x8d146doiwcvuv8qemu3mzxwk/VoiceOver.pkg).
- Install the downloaded VoiceOver.pkg.
- Quit and re-open iTunes.

**Comment by dirtlwyr** [comment]
Thanks so much!  Everything works.

**Comment by Schachte** [comment]
hey @cormiertyshawn895 . Unfortunately, using the latest version and running is stilling resulting in:

> If you see "iTunes cannot read the contents of the iPod. Go to the Summary tab in iPod preferences and click Restore to restore this iPod to factory settings"

I'm on an M1 Macbook Pro. Any ideas? I've tried all versions of iTunes.

**Comment by caphesuagey** [comment]
My iPod Classic doesn't show up in iTunes (the dark version), it simply doesn't appear anywhere except in Finder. While the iPod is connected and iTunes is open, I'm unable to disconnect it from Finder until I close iTunes. What should I do? 

I use macOS Ventura beta...7
