### ISSUE TITLE
iphoto library manager do not recognize iphoto version

### ISSUE THREAD

**Issue by simontroadec** [cormiertyshawn895/Retroactive#350]
hi,

I use iphoto library manager 4.2.7 to manage iphoto library. I used retroactive 2.O to install iphoto 9.6.1 on an apple macbook air M1 (2020) with monterey. Iphoto run well and open all my iphoto libraries. But if i tried to copy events or photos (or open iphoto) with iphotolibrary manager an error occurs : The library “Bibliothèque iphoto” is of a newer version (9.6.1) than the installed version of iPhoto ((null)).

Is their any tips to change the version read by iphotolibrarymanager or somethings else ?

Thanks.

**Comment by ManfredKohl** [comment]
same for me, iphotolibrary manager 4.2.7 on Mac OS X Catalina gives: The version of library “Merged Library” (9.6.1)  is different from the installed version of iPhoto ((null)).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
