### ISSUE TITLE
Sign into iCloud Photos

### ISSUE THREAD

**Issue by markd1970** [cormiertyshawn895/Retroactive#351]
the Aperture app. Go to Aperture settings. My Photo Streams.  Sign into iCloud Photos , click on continue and nothing.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
