### ISSUE TITLE
iTunes still crashing on startup Ventura.

### ISSUE THREAD

**Issue by nikbex-sno** [cormiertyshawn895/Retroactive#352]
Crash part report:
Machine: MacBook Pro 2015 OCLP install.
This is the only app that won't work, iPhoto no problem.
Thanks

Process:               iTunes [76231]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [76228]
User ID:               502

Date/Time:             2023-03-11 13:35:42.2978 +0000
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        7B8DB681-53B5-3489-6FBA-1F748E440B4A

Sleep/Wake UUID:       F5D495D8-6D12-4761-94D9-6B04153788DF

Time Awake Since Boot: 350000 seconds
Time Since Wake:       2735 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff818907b4a __abort_with_payload + 10
1   dyld                          	    0x7ff818920d07 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff818920d39 abort_with_payload + 9
3   dyld                          	    0x7ff8188a81e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff8188a5660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff8188a4281 start + 2289

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bd7dd3c8  rdx: 0x00007ff7bd7dd830
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bd7dd410  rsp: 0x00007ff7bd7dd3c8
   r8: 0x00007ff7bd7dd430   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7bd7dd830  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff818907b4a  rfl: 0x0000000000000246  cr2: 0x00000001048eb000

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
