### ISSUE TITLE
authentication password

### ISSUE THREAD

**Issue by ppshashi** [cormiertyshawn895/Retroactive#353]
what is the authentication password asking.i entered GitHub password but not working

**Comment by agret** [comment]
It's the password you use to login to your Mac whenever you boot it up/resume from sleep.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
