### ISSUE TITLE
Can't find app with identifier com.apple.iTunes

### ISSUE THREAD

**Issue by blahdy** [cormiertyshawn895/Retroactive#354]
A pretty sophisticated issue, but still.

There's an audiophile app called Audirvana Plus, which has iTunes integrated mode.

On Mojave a couple of years ago it was possible to use it with retroactive iTunes installed.

After updating my home server's hardware and software the app launches on Big Sur - Ventura with the subject message and doesn't detect iTunes 12.9.5.

Very thankful for your effort, but for me the only reason to use iTunes is that app.

The reason is rather simple. Yes, they have updated their product for newer versions of macos and Music app and all, but they dropped iZotope dithering and resampling libraries, claiming to use more robust (as in cheap and lower quality) libraries. The difference is easily heard with the proper hardware.

Yes, the retro app still works standalone, but iTunes manages auto syncing the library with iDevices etc. so all this retro is irreplaceable atm in case of perfectionism.

So I would be most obliged if you helped me point Audirvana plus (or any app seeking iTunes, VLC for example) to the Retroactive iTunes.

**Comment by blahdy** [comment]
dirty fix:
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib /Applications/iTunes.app/Contents/MacOS/iTunes
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_dsp.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_musicid.3.06.1.dylib
install_name_tool -change @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_manager.3.06.1.dylib /Applications/iTunes.app/Contents/Frameworks/libgnsdk_submit.3.06.1.dylib
sudo codesign --remove-signature /Applications/iTunes.app

**Comment by james10424** [comment]
If you can edit the bundle id in the app, it would be `com.launcher.iTunes`. But scripting with iTunes wouldn't work.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
