### ISSUE TITLE
How To Open IOS Apps With Retroactive Or With Disabled Retroactive

### ISSUE THREAD

**Issue by Mlodyyfifi** [cormiertyshawn895/Retroactive#357]
Hello! My name is Filip and i need some help because i need to turn on my IOS apps, but i cant! I need to know what was that console line to disable Retroactive

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
