### ISSUE TITLE
Retroactive and M1 machines

### ISSUE THREAD

**Issue by Micropechis** [cormiertyshawn895/Retroactive#358]
I was very grateful to cormiertyshawn895 for Retroactive, I could continue to run Aperture (3.5TB of research libraries) on my Intel 27in iMac with Big Sur installed, but my Uni have provided me with an M1 Mac Studio running Ventura and it is my understanding that Aperture will not work even with Retroactive installed on that arrangement. Are there any plans for an M1 or M2 version to enable folks like me to continue using Aperture without remaining in the Stone Age?

**Comment by Woolwit** [comment]
Not running Aperture, but if it's worth the trouble to you, you might try putting Monterey on the M1. This is working for me...
I have an M1 Mac Mini, Monterey 12.6, Retroactive 1.9, and iTunes 11.4

**Comment by Micropechis** [comment]
Hi Woolwit, that is interesting, Retroactive allows iTunes to play on a Monterey M1 Mac! I might try it out for Aperture on my Uni M1 Studio. I need to buy a new MacBook Pro and not being able to run Aperture is the main reason I am not going for a new model.

**Comment by R-S-T** [comment]
Still no luck for me on my M2 MacMini. And it is not possible to go back to another system version.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
