### ISSUE TITLE
iDevices no longer show up in finder after installing iTunes

### ISSUE THREAD

**Issue by ceilingtilefan** [cormiertyshawn895/Retroactive#359]
I originally installed iTunes using Retroactive 1.9, but then found out my devices no longer show up in Finder. Uninstalling iTunes does not work and installing a new version of iTunes using Retroactive 2.0 does not fix my issue.

(macOS Big Sur 11.7.1, iTunes 12.6.5.3)

**Comment by tbffbt** [comment]
my sound card stopped connecting after installing iTunes through Retroactive too

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
