### ISSUE TITLE
No support Monterey 12.6.5

### ISSUE THREAD

**Issue by ljl78** [cormiertyshawn895/Retroactive#360]
Hello there,

The Retroactive 2.0 not support this OSX version.
The program crashed just after open it, and it seems that there won't be fixed, so I guess Retroactive has died.

Anyone know any other alternative for iTunes?

Thank you very much.

**Comment by Woolwit** [comment]
This is working for me. If other folks could add what IS working for them...
I have an M1 Mac Mini, Monterey 12.6, Retroactive 1.9, and iTunes 11.4

**Comment by riverLethe9** [comment]
I got it working. See this other comment I left: #365

**Comment by ljl78** [comment]
Thank you for the info.
I've tried to install Retroactive 1.9, but it stucks when try to Extract iTunes.
Any other solution?

Best regards.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
