### ISSUE TITLE
Cannot Download (Unable to Download)

### ISSUE THREAD

**Issue by anaclumos** [cormiertyshawn895/Retroactive#361]
Maybe Apple closed the iTunes dist server?

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/31657298/235842871-bcfa6531-5016-402d-8b34-8db0ae8ea4ae.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
