### ISSUE TITLE
Use Predownloaded Installation Path

### ISSUE THREAD

**Issue by anaclumos** [cormiertyshawn895/Retroactive#363]
We can individually download iTunes from here: https://support.apple.com/downloads/itunes

Can we skip the download part?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
