### ISSUE TITLE
FCP 7.0.3 freezes during start up on High Sierra

### ISSUE THREAD

**Issue by chris221021** [cormiertyshawn895/Retroactive#367]
Hi, I had to update my MacBook Pro Mid 2010 to High Sierra and downloaded Retroactive so that I could continue to use FCP 7.0.3 without restarting in Sierra. Retroactive installed correctly and unlocked FCP, restoring the icon. When I launch FCP, it proceeds through the initialisation, loading many components but stops with the spinning beachball of death just before it would normally open the workspace and remains unresponsive. It is using a lot of CPU in this condition and the fans run at full speed. The only way out is Force Quit.

Any ideas where to go next?

Cheers, Chris

**Comment by HoleLeeSheet** [comment]
Same. Have you solved it now?

**Comment by chris221021** [comment]
I have solved it, by reverting to Sierra with a Time Machine backup from before the problem. I've given up with Retroactive, it didn't work for me.

**Comment by HoleLeeSheet** [comment]
> I have solved it, by reverting to Sierra with a Time Machine backup from before the problem. I've given up with Retroactive, it didn't work for me.

I completely surrendered. I'm using an imac pro, can't back to 10.12. I'm gonna move the project to DR. Ciaociao, FCP7.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
