### ISSUE TITLE
Externals app trying to open itunes opens Apple Music instead

### ISSUE THREAD

**Issue by sms-ebarbeito** [cormiertyshawn895/Retroactive#369]
First of all... I don't think this is an issue but maybe you could provide a workaround for it.
I'm trying to use an external third party app called IExplorer to copy my entire iPod classic (with music, playlist, ratings and playcounts) to retroactive iTunes. But when start syncing opens Apple Music instead the already previusly opened iTunes. 
Consequently it starts copying everything into Apple Music and I can't find an elegant way to tell the mac to use Itunes.

There is a way to make iTunes prior over Apple Music?

**Comment by don-911** [comment]
I don't know exactly how to fix this, but here are a couple of ideas. I use a program called XLD to convert FLAC to ALAC and automatically add the files to iTunes. But it defaults to adding files to Music. To change that, I ran the following command in Terminal.app:

defaults write jp.tmkk.XLD XLDForceUseiTunesLibrary -bool true

Another thing you can try is to download an app called NoTunes, which will prevent iTunes or Music from opening when it's running. So you could enable it after launching iTunes, which would prevent Music from opening. It's a menu bar item, so easy to enable/disable.

https://github.com/tombonez/noTunes

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
