### ISSUE TITLE
Uninstall Apps Installed through Retroactive

### ISSUE THREAD

**Issue by kirillminiaev** [cormiertyshawn895/Retroactive#37]
First off, thank you for a great app. I installed iTunes on MacOS Catalina and used it without issue for a few months. With the latest update to Catalina the built-in Music app is now performing the way I need it to perform, and I am looking to uninstall iTunes.

What is the correct way to uninstall an app installed through Retroactive? Is there a built in method, GUI-based or command-line based? Or can I just use a typical Mac app uninstaller like CleanMyMacX or AppCleaner?

**Comment by cormiertyshawn895** [comment]
To uninstall an app installed through Retroactive, just move it to the Trash.

**Comment by Mariomcrrx** [comment]
i cannot uninstall itunes, it thinks its a system app

**Comment by cb946** [comment]
I have deleted Retroactive and iTunes. Now can i delete the iTunes folder ( Users/Me/Music/iTunes ) without it affecting the Music and Podcast apps?
