### ISSUE TITLE
EDIT: Enabling Full Disk Access doesn't work on non-English languages

### ISSUE THREAD

**Issue by vipotaenko02** [cormiertyshawn895/Retroactive#370]
I'm using native 12.6.6 Monterey install with latest Retroactive and latest iTunes (12.9.5). However, when I try to get Full Disk access, only Settings app is opened without any boxes to drag. Manually dragging iTunes app, or iTunes executable within the app doesn't get Full Disk access. The media folder is on SD card, so it fails to play the entire library. Screenshot shows everything I see after clicking "Enable Full Disk Access" and unlocking the Settings app
![image](https://github.com/cormiertyshawn895/Retroactive/assets/116735001/b29da4f4-8bb4-4dcf-a686-77ca678b5710)

**Comment by vipotaenko02** [comment]
So as it turned out, boxes does appear after changing system language to English. So it would be better to prompt the user to switch the language before using Retroactive, or (is this possible) to fix it.

**Comment by vipotaenko02** [comment]
Or, you can just prompt the user to manually add /bin/bash to this window to gain Full Disk Access.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
