### ISSUE TITLE
FCP7

### ISSUE THREAD

**Issue by kaeru1234** [cormiertyshawn895/Retroactive#371]
I have a request.
I would like to use FCP7 on the latest MacOS (Ventura).

**Comment by kristibektashi** [comment]
Highly unlikely to happen, considering it's a 32-bit application

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
