### ISSUE TITLE
feature request: support for pre-Ventura Photos app

### ISSUE THREAD

**Issue by IvanExpert** [cormiertyshawn895/Retroactive#373]
First off, thank you for Retroactive. It's amazing, and amazingly useful.

One feature Apple has stripped from Photos 8.0 in Ventura is the ability to import an iPhoto library. This can leave you hosed if that's what you need to do. Having support for an older version of Photos simply for this conversion ability would be super helpful.

I realize this is kind of an edge case that you may not want to put the effort in for, but it's simply a suggestion. Thanks again for Retroactive!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
