### ISSUE TITLE
feature request - Apple Maps with OpenGL renderer (from i.e. ElCapitan)

### ISSUE THREAD

**Issue by larsvonhier** [cormiertyshawn895/Retroactive#375]
Non-metal capable "unsupported" Macs are still quite useful running Ventura with OCLP. That macOS has some metal-only Apple apps,
so would it not be nice to have older Maps versions running which supported also OpenGL on non-metal GPUs?
I tried to dive down into the dependencies of frameworks needed but I'd guess you have been there, done it... ;-)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
