### ISSUE TITLE
Feature request: Add the ability to run macOS Server on macOS 13 and above

### ISSUE THREAD

**Issue by kristibektashi** [cormiertyshawn895/Retroactive#377]
The macOS Server app has been discontinued and no longer shows in the App Store after upgrading to macOS 13

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
