### ISSUE TITLE
iTunes installer in Retroactive 2.0 bugs out at 100%

### ISSUE THREAD

**Issue by Hector65714** [cormiertyshawn895/Retroactive#378]
When installing the last and latest version of iTunes in Retroactive at installer will bug out at 100% and instead of extracting and continuing it starts counting above 100% to 101% then 102%... Is this an existing bug? My Specifications: 2017 21.5" 4K Retina iMac with macOS Ventura 13.5 Intel Core i5, AMD Radeon Pro 555 and 16 Gb of Ram.

Screenshot: https://ibb.co/M9rXJvy

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
