### ISSUE TITLE
Retroactive 

### ISSUE THREAD

**Issue by Macintosher** [cormiertyshawn895/Retroactive#379]
Retroactive 2.0
Retroactive is gorgeous software and it made me switch to a mac studio with ventura because aperture was running. Aperture ran beautifully on ventura 13.4. After updating to 13.5, aperture can only access a part of the images - no matter what resolution/image I set - and it's quite slow. Time for an update to 2.01?
Thank you so much Bernhard

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
