### ISSUE TITLE
will sponsor iPod nano fix

### ISSUE THREAD

**Issue by drefrome** [cormiertyshawn895/Retroactive#38]
@cormiertyshawn895: nice work with Retroactive! I am wondering if some financial support would make a difference in being able to debug the iPod syncing problems, in particular for the latest gen iPod nano. Either way, greatly appreciative of your work here.

**Comment by schulzs** [comment]
I second that! I would also give Apple real money for a new iPod nano model....

**Comment by cormiertyshawn895** [comment]
### If you see "The iPod is in use by another user on this computer", or nothing happens at all when you plug your iPod into iTunes:
<img width="602" alt="in-use" src="https://user-images.githubusercontent.com/57056759/75617416-aa6d0880-5b13-11ea-9023-622193684295.png">

- Disconnect the device from your Mac, but keep iTunes open.
- Click on the Spotlight icon (magnifying glass) on the menu bar.
- Type "Terminal" and press return to open the Terminal app.
- Enter `killall AMPDevicesAgent` in the Terminal window, and press return.
- Connect the Apple device back to your Mac.

---
### If you see "iTunes cannot read the contents of the iPod. Go to the Summary tab in iPod preferences and click Restore to restore this iPod to factory settings":
<img width="602" alt="cannot-read" src="https://user-images.githubusercontent.com/57056759/75617419-ae008f80-5b13-11ea-85e7-17ffb4bc907a.png">

- Re-install iTunes [using the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/).
- After re-installing iTunes, Retroactive will ask you about iPod syncing. Click "Enable Full Disk Access", and follow on-screen instructions provided by Retroactive.

![7a](https://user-images.githubusercontent.com/57056759/75648829-2182c980-5c06-11ea-8ee7-7a8a0eacfd2f.jpg)

---
### If you try to enable VoiceOver for iPod shuffle, but see "iTunes was unable to install the VoiceOver Kit. An unknown error occurred (1701)":

- [Directly download the VoiceOver 1.4.2 installer here](https://swdist.apple.com/content/downloads/29/37/041-91732-A_LSWLP6NLRV/bk8l36k29x8d146doiwcvuv8qemu3mzxwk/VoiceOver.pkg).
- Install the downloaded VoiceOver.pkg.
- Quit and re-open iTunes.

**Comment by schulzs** [comment]
With Retroactive 1.4, iTunes corrupted my iPod (it needed to be completely restored). With Retroactive 1.5, I got the "is in use with another user" message, but after killing AMPDevicesAgents and enabling Full Disk Access for bash, it seems to work fine. I'll play with it for a while - if anything unexpected happens, I'll let you know. 

Thanks a lot!
