### ISSUE TITLE
Retroactive 2.0 (87) with iPhoto 9.6.1 and issue with right click on smart album

### ISSUE THREAD

**Issue by Tetonne** [cormiertyshawn895/Retroactive#380]
Hello thanks for this great tool
cos I'm able to use iphoto 9.6.1 on my Intel Monterey 12.6.8 thanks to retroactive 2.0 (87)

my issue :
can not use, modify existing smart album (with right click) cos it's gray with out any text (right hand side on th bottom of the picture..
after waiting, iPhoto crash.
![Capture d’écran 2023-08-19 à 08 07 44](https://github.com/cormiertyshawn895/Retroactive/assets/10786040/496bdb28-55c1-424b-98d2-638ede4e2713)

the issue always have been no matter which release of retroactive.
May be it's simple for you to correct this.
thanks in advance.
best regard

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
