### ISSUE TITLE
Ventura 13.5.1 Aperture Nikon RAW Unsupported Image

### ISSUE THREAD

**Issue by raxelbrof** [cormiertyshawn895/Retroactive#381]
Just adding to issues some have noted:

Ventura 13.5.1, Aperture, and .NEF RAWs that are natively supported by Aperture. They're producing the "Unsupported Image" error, and reprocessing causes all the thumbnails to refresh and show up as the correct images... for a few seconds, then they start switching back to the unsupported image icon.

2019 Mac Pro with Dual W5700X GPUs

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
