### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by warhorse77** [cormiertyshawn895/Retroactive#383]
Is there a way to install themes in iTunes 10.7 I'm still using 1.5 it works very well.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
