### ISSUE TITLE
iTunes 10.7 on MBA M2 15" with Ventura 13.5.1 WORKS (with a few caveats though)

### ISSUE THREAD

**Issue by schubidubi** [cormiertyshawn895/Retroactive#384]
First of all, this is seriously _amazing:_ My beloved **iTunes 10.7** – that I already had to "hack" 10 years ago to make it run on a MBP mid-2012 – **runs on my brand new MBA 15"**! Thanks to all who contributed to Retroactive for making this possible!
I have already copied all my libraries to the new Mac and started to convert them for the abysmal "Music.app" when I stumbled upon Retroactive. Installed iTunes 10.7 and all my libraries are there where I left them. Brilliant!

One issue I just noticed:
iTunes 10.7 crashes when clicking "OK" or "Cancel" in the modal **General Preferences** window:

`Process:               iTunes [52253]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               10.7 (10.7)
Build Info:            iTunes-10702101~1
Code Type:             X86-64 (Translated)
Parent Process:        Exited process [52248]
User ID:               501

Date/Time:             2023-08-30 18:04:19.8092 +0200
OS Version:            macOS 13.5.1 (22G90)
Report Version:        12
Anonymous UUID:        FE46938F-5B1A-EFD5-5353-8FEFF6B24DC8

Sleep/Wake UUID:       69DCB604-6BF3-4B01-8768-69E369DA12B8

Time Awake Since Boot: 180000 seconds
Time Since Wake:       4543 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000058ff9064b61e
Exception Codes:       0x0000000000000001, 0x000058ff9064b61e

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [52253]

VM Region Info: 0x58ff9064b61e is not in any region.  Bytes after previous region: 97373626086943  Bytes before following region: 7698453842402
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff80f3cefda objc_opt_respondsToSelector + 27
1   AppKit                        	    0x7ff812a675fc -[NSToolbarItem _validateAsCommonItem:] + 107
2   AppKit                        	    0x7ff81290bf1e -[NSToolbarItem validate] + 124
3   AppKit                        	    0x7ff81290a8c1 -[NSToolbar _autovalidateToolbarItem:] + 98
4   Foundation                    	    0x7ff810628d85 __NSFireDelayedPerform + 440
5   CoreFoundation                	    0x7ff80f837b92 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
6   CoreFoundation                	    0x7ff80f83770f __CFRunLoopDoTimer + 807
7   CoreFoundation                	    0x7ff80f83732a __CFRunLoopDoTimers + 285
8   CoreFoundation                	    0x7ff80f81d818 __CFRunLoopRun + 2210
9   CoreFoundation                	    0x7ff80f81c91c CFRunLoopRunSpecific + 560
10  HIToolbox                     	    0x7ff819766f3d RunCurrentEventLoopInMode + 292
11  HIToolbox                     	    0x7ff819766d4e ReceiveNextEventCommon + 657
12  HIToolbox                     	    0x7ff819766aa8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
13  AppKit                        	    0x7ff81281825c _DPSNextEvent + 858
14  AppKit                        	    0x7ff812817106 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
15  AppKit                        	    0x7ff812809788 -[NSApplication run] + 586
16  iTunes                        	       0x102e5ae3f 0x102e58000 + 11839
17  iTunes                        	       0x102e5ac80 0x102e58000 + 11392

[…|

Model: Mac14,15, BootROM 8422.141.2, proc 8:4:4 processors, 24 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, spdisplays_2880x1864Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: May 27 2023 01:34:59 version 20.96.31.0.8.7.148 FWID 01-126f2c4c
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
`

Any new settings are being saved though.
Other than that, since I'm using it only in strict offline mode, I couldn't be happier.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
