### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by insec404** [cormiertyshawn895/Retroactive#385]
I updated to iOS 17 Beta 6 and its not working, Its telling me i need to download when i open itunes but it never downloads the software thing

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
