### ISSUE TITLE
Emergency! FCP7 error！

### ISSUE THREAD

**Issue by HoleLeeSheet** [cormiertyshawn895/Retroactive#386]
I've run Final Cut Pro7 on macOS 10.14.6 with Retroactive before, but this time I failed, FCP always freezes on the startup interface.

My computer is an iMac Pro (2017) and this problem appeared after I upgraded the CPU and RAM for my computer (Intel Xeon W-2140B to Intel Xeon W-2190B, 32GB of RAM to 128GB of RAM), I don't know if it has anything to do with this problem.

Thanks in advanced!

Log below.
[1.txt](https://github.com/cormiertyshawn895/Retroactive/files/12566110/1.txt)

-------------------------------------------------------------
UPDATE:
The guy who replaced my CPU told me that he upgraded another iMac Pro with the same CPU: Xeon 2190b, after which he installed FCP7 and ran Retroactive, FCP7 couldn't open just like mine. So.... FCP7 recognize the CPU?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
