### ISSUE TITLE
SIP does not need to be disabled for iTunes 12.9.5 to run on Apple Silicon.

### ISSUE THREAD

**Issue by crystall1nedev** [cormiertyshawn895/Retroactive#388]
<img width="1019" alt="Screenshot 9" src="https://github.com/cormiertyshawn895/Retroactive/assets/55281754/43b22d30-1d2f-46c8-b54d-60f18895f09c">

Using install_name_tool to fix the library loading errors, you can get iTunes 12.9.5 running with SIP enabled if you codesign with an ad-hoc signature afterwards.

```
sudo codesign -fs - --deep /Applications/iTunes.app
```

**Comment by ylluminate** [comment]
Good call (although SIP is a bane to some of us generally), but one may also note that you may need to check / remove some extended attributes if you get something like this:
```
$ sudo codesign -fs - --deep /Applications/iTunes.app
Password:
/Applications/iTunes.app: replacing existing signature
/Applications/iTunes.app: resource fork, Finder information, or similar detritus not allowed
$ xattr -l /Applications/iTunes.app
com.apple.FinderInfo:
0000   00 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00    ................
0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
$ sudo xattr -c /Applications/iTunes.app
$ sudo codesign -fs - --deep /Applications/iTunes.app
/Applications/iTunes.app: replacing existing signature
```

**Comment by kristibektashi** [comment]
Does this work on macOS Sonoma?

**Comment by tbffbt** [comment]
this means I disable SIP for installation and, once everything's up and running I re-enable it?

**Comment by ylluminate** [comment]
Some of us hold great disdain for SIP and simply operate with it off. If Apple tries to force us into an iPhone-like situation with their desktop and laptop products it will be the end of the road.

**Comment by tbffbt** [comment]
it didn't work for me though, iTunes crashes

**Comment by ylluminate** [comment]
Hmm. I have been using it alright on an M1 Max with macOS 14.2 beta 4 still.

**Comment by CrappleMuzik** [comment]
How about for us tiny brains you give us a step by step procedure of what to do. I have no idea what an Adhoc is

**Comment by wwwonka** [comment]
Have someone managed to get an iPod classic 6/7 gen show up that way, when SIP is enabled?

I currently have iTunes 12.9.5, installed through Retroactive under Sonoma 14.4.

The iPod 5th gen works without any trouble, although I never managed to get the classic show up at all.

**Comment by ylluminate** [comment]
@wwwonka you know, I am very curious - can you get it to show up in Swinsian (if you try the trial of it)? I've been really pleased with its capacity to replace iTunes vs having to move to trashy Music.app...

**Comment by wwwonka** [comment]
Hey @ylluminate,
Yes. Swinsian works without any fuss. It's nostalgia more than anything that drives me in that quest...

**Comment by ylluminate** [comment]
Gotcha, having a clean and predictable UX that doesn't muddy up the water and yet still emulates the "old fashioned" iTunes is what drives me. 

James @ Swinsian is an awesome and attentive dev. I'm finding Swinsian 3 (Preview 13) to be absolutely amazing in this space right now.

(SIDEGRIPE: So flustered by Apple and all of it's insane services/daemons threaded throughout the OS with no significant benefits for us as users. I am so tired of all of the feature churn that only evolves us to the deplorable iMobile-state-of-things.

Oh how I wish I could choose what I want from Apple to be active in macOS system services and diverge from the iOS/iPadOS/* convergence.
)

**Comment by simcc** [comment]
> How about for us tiny brains you give us a step by step procedure of what to do. I have no idea what an Adhoc is

https://github.com/cormiertyshawn895/Retroactive/issues/305#issuecomment-2028526656

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
