### ISSUE TITLE
iCloud Connections hang - Strange Solution

### ISSUE THREAD

**Issue by spencerjason** [cormiertyshawn895/Retroactive#39]
I've noticed that my iCloud Library often spins its wheels for a while. The first time was a result of it uploading the Genius results for 15,000 items. :)

But it still gets stuck when launching or waking from sleep, which means anything strictly in the cloud is stuck there and I can't stream or download it.

Right now, my solution is to disable wifi then re-enable it, and almost every time it comes right up and I'm fine. Not sure if there is an iTunes 12.9.5.5 issue or Catalina/Retroactive.

**Comment by cormiertyshawn895** [comment]
You have an impressively large collection of songs! I'll update you if there's any development on resolving the hang.

**Comment by spencerjason** [comment]
Life of a DJ :) I have a few other libraries that are MUCH larger with remixes, etc.

So far, turning wifi on/off has been an easy bypass for what I gain using Retroactive.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
