### ISSUE TITLE
Aperture does not print books into pdf files on mac min M2 (Ventura 14.3)

### ISSUE THREAD

**Issue by klod44** [cormiertyshawn895/Retroactive#390]
Aperture works quite fine on my mac M2, but I cannot export a book as a pdf File.

When I clik on the "print" button, aperture checks the book as usual and then.... nothing happens!

No crash, nothing

It does not work either on my macbook air with ventura, and I have to boot with catalina to be able to print my books.

Can you help?

Thanks

Claude

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
