### ISSUE TITLE
Does Retroactive work with converted libraries?

### ISSUE THREAD

**Issue by cartographer4** [cormiertyshawn895/Retroactive#392]
I noticed that when I switched to Photos and Catalina, my xml files changed structure for both my photo library and my music library.   Does the Retroactive installed iTunes and iPhoto compensate for the changes in the library structure?   Or will only old libraries from prior to the Mac OS conversion work with these applications.  I learned about Retroactive only today, and have long ago since upgraded to Monterey and don't know if any copy of iPhoto remains in my backups, and before I dig around for it, I want to make sure I don't lose the updated information I already gathered.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
