### ISSUE TITLE
Aperture/iPhoto crash when opening 

### ISSUE THREAD

**Issue by csutedja** [cormiertyshawn895/Retroactive#393]
Hardware: MacBookAir4,1/macOS 11.7.10 (with OCLP 1.01)/Retroactive 2.0

When I launch Aperture, the icon bounces and the app opens but immediately closes. iPhoto gets a little farther, prompting me to create a library, but after making one the app crashes. It's also worth mentioning that I tried these apps in a High Sierra install and they worked, so the apps themselves are fine. Also I tried installing iTunes to see if Retroactive as a whole wasn't working, but that installed fine. Is there a way to get Aperture and iPhoto working? Or is it because I have a non-metal GPU that was root patched? Attached are the log files from both apps.
[Aperture 3.6 crash log.txt](https://github.com/cormiertyshawn895/Retroactive/files/13049195/Aperture.3.6.crash.log.txt)
[iPhoto 9.6.1 crash log.txt](https://github.com/cormiertyshawn895/Retroactive/files/13049196/iPhoto.9.6.1.crash.log.txt)

**Comment by csutedja** [comment]
also mentioning that I recently got OCLP 1.10 and its root patches and still no progress, so I don't think its a OCLP issue

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
