### ISSUE TITLE
Sizzling Keys.app still works to control iTunes 12.9.5.5 on macOS 14.1 Sonoma on Apple Silicon

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#394]
Something I've been quite enjoying and thought others might want to be aware that still works: running iTunes 12.9.5.5 with Sizzling Keys.app on macOS 14.1 Sonoma (Apple Silicon; M1 Max). Retroactive still makes iTunes work and Sizzling Keys.app is crashy, BUT it works and if you utilize Lingon X.app to start and monitor Sizzling Keys, it will restart it for you without your ever being aware and missing a beat. I'm enjoying old fashioned awesome keyboard control of iTunes whilst jamming to all of my old collections in the much better interface vs Apple's trashy new UX direction.

**Comment by ylluminate** [comment]
Was going to close this, but I felt as though it needs to remain open so folks will see these things are indeed still possible with @cormiertyshawn895's wonderful efforts.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
