### ISSUE TITLE
Make iTunes 12.9 able to run on macOS High Sierra

### ISSUE THREAD

**Issue by kristibektashi** [cormiertyshawn895/Retroactive#395]

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
