### ISSUE TITLE
Aperture, Big Sur & Virtual Machines

### ISSUE THREAD

**Issue by raxelbrof** [cormiertyshawn895/Retroactive#396]
Just wondering:

- Aperture is generally not able to run in a VM  because there's no support for graphics acceleration in macOS versions where Aperture is a supported app.
- Big Sur introduced paravirtualised graphics drivers, so Big Sur VMs do theoretically have graphics acceleration.
- Has anyone tried running a Retroactive converted Aperture install in a Big Sur VM to see if it works?

**Comment by 234gt67op** [comment]
d

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
