### ISSUE TITLE
iTunes 12.95 Can’t Open On Ventura 13.5 After SIP Is Re-Enabled

### ISSUE THREAD

**Issue by bob247365** [cormiertyshawn895/Retroactive#397]
I first downloaded it yesterday on my brand new Ventura MBP. 
Everything was fine until I re-enabled it and tried to reopen it . 
I then got the ‘iTunes quit unexpectedly’ message, repeatedly.

Today, after transferring my backed-up iTunes folder (from an older Catalina Mac running the 12.9.5 DJ) to the new Mac, I then downloaded 12.65.
Everything was fine until I tried to open iTunes and got the ‘Library cannot be read because it was created by a newer version of iTunes’ message!
Tried again today with 12.9.5 and got the same ‘iTunes quit unexpectedly’ message.

I’ve got eight more days on my fourteen day return window for the new Mac.
Since I’m not holding my breathe for a fix by then, I’ll download 12.65, delete all the files on the Mac, then load some of my files by dragging and dropping into the iTunes main window and start and fill a new .itl etc. file from scratch.
If I don’t lose too much meta that needs to be manually re-added, I’m good to go.
If not, I’ll just return the Ventura, then load some of them into my High Sierra Mac.

Here’s a copy of the crash report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 2409224A-05A6-4B7B-B296-6C8DEFA77F0B
CrashReporter Key:   2F83723D-1731-C235-EDD7-2591D7402BED
Hardware Model:      Mac14,6
Process:             iTunes [586]
Path:                /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:          com.apple.iTunes
Version:             12.9.5 (12.9.5)
Code Type:           X86-64 (Native)
Role:                Unspecified
Parent Process:      Exited process [583]
Coalition:           com.launcher.iTunes [706]

Date/Time:           2023-10-27 19:05:38.5476 -0700
Launch Time:         2023-10-27 19:05:38.5431 -0700
OS Version:          macOS 13.5 (22G74)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: CODESIGNING 1 Taskgated Invalid Signature

Triggered by Thread:  0

Thread 0 Crashed:
0                                 	    0x7ff7ffe9777c 0x7ff7ffe94000 + 14204

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000030e91ca98   pc: 0x00007ff7ffe9777c cpsr: 0x00001000
   far: 0x0000000000000000  esr: 0x00000000  Address size fault

Binary Images:
       0x20663a000 -        0x2066d5fff  (*) <31e1c182-e611-3883-97a3-4334a21c90bd> ???
    0x7ff7ffe94000 -     0x7ff7ffec3fff  (*) <15ccd9bf-9a15-3540-a1ff-3abea3e2ca9d> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"iTunes","timestamp":"2023-10-27 19:05:38.00 -0700","app_version":"12.9.5","slice_uuid":"91006ee5-c8c4-3a53-b7f7-69a3b2fd991a","build_version":"12.9.5","platform":0,"bundleID":"com.apple.iTunes","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5 (22G74)","roots_installed":0,"name":"iTunes","incident_id":"2409224A-05A6-4B7B-B296-6C8DEFA77F0B"}
{
  "uptime" : 69,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,6",
  "coalitionID" : 706,
  "osVersion" : {
    "train" : "macOS 13.5",
    "build" : "22G74",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-27 19:05:38.5476 -0700",
  "incident" : "2409224A-05A6-4B7B-B296-6C8DEFA77F0B",
  "pid" : 586,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-27 19:05:38.5431 -0700",
  "procStartAbsTime" : 1658545267,
  "procExitAbsTime" : 1658647352,
  "procName" : "iTunes",
  "procPath" : "\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes",
  "bundleInfo" : {"CFBundleShortVersionString":"12.9.5","CFBundleVersion":"12.9.5","CFBundleIdentifier":"com.apple.iTunes"},
  "buildInfo" : {"ProjectName":"iTunes","SourceVersion":"1200012009005005","BuildVersion":"9"},
  "storeInfo" : {"deviceIdentifierForVendor":"A8324FA6-5C0A-53AE-BB34-E0498FE08946","thirdParty":true},
  "parentProc" : "Exited process",
  "parentPid" : 583,
  "coalitionName" : "com.launcher.iTunes",
  "crashReporterKey" : "2F83723D-1731-C235-EDD7-2591D7402BED",
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 16777216,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":66,"code":1,"namespace":"CODESIGNING","indicator":"Taskgated Invalid Signature"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":6619,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":13129337496},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":140703127140220,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":14204,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8697126912,
    "size" : 638976,
    "uuid" : "31e1c182-e611-3883-97a3-4334a21c90bd",
    "name" : ""
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127126016,
    "size" : 196608,
    "uuid" : "15ccd9bf-9a15-3540-a1ff-3abea3e2ca9d",
    "name" : ""
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1168K resident=0K(0%) swapped_out_or_unallocated=1168K(100%)\nWritable regions: Total=24.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=24.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                       15.9M        6 \nVM_ALLOCATE (reserved)             500K        1         reserved VM address space (unallocated)\n__DATA                              80K        3 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         368K        4 \n__TEXT                             816K        2 \nmapped file                        6.9G       33 \n===========                     =======  ======= \nTOTAL                              7.0G       53 \nTOTAL, minus reserved VM space     7.0G       53 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "b969e14087aa658fb8f1ee95f85779ebd20c78c0",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645c2d2f9e69a025b0a37e29",
      "factorPackIds" : {

      },
      "deploymentId" : 240000003
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: Mac14,6, BootROM 8422.141.2, proc 12:8:4 processors, 96 GB, SMC 
Graphics: Apple M2 Max, Apple M2 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Jun 11 2023 05:20:59 version 23.20.95.0.40.50.92 FWID 01-ec505a98
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
