### ISSUE TITLE
iPhoto loses pix, closes unexpectedly

### ISSUE THREAD

**Issue by CrowDaddy** [cormiertyshawn895/Retroactive#398]
Shawn,  We appreciate greatly the work you did on Retroactive;  it has enabled my wife to continue using her iPhoto libraries.

However, just after updating to 13.6.1 ( or perhaps shortly before) iPhoto began losing pix when closed and re-opened; now it has also started closing randomly.  Can you suggest a cause and solution?  
If I start Retroactive again, when there is already a converted iPhoto, will it create a new one and replace the old??  Possibly iPhoto itself has become corrupted.

Also, different issue:  can you suggest a consultant who could ( for a fee) help my wife move off iPhoto?  Among other things would be deciding between Lightroom and Bridge.

Thanks again!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
