### ISSUE TITLE
Crashes when trying to print 

### ISSUE THREAD

**Issue by marmon23** [cormiertyshawn895/Retroactive#4]
Thanks a lot for this! While exploring, I found that doing File->Print causes the program to crash.

**Comment by cormiertyshawn895** [comment]
Please [download and launch Retroactive 1.2](https://github.com/cormiertyshawn895/Retroactive/releases/download/1.2/Retroactive.1.2.zip), then choose to modify Aperture again. Printing should be available after re-modifying Aperture with Retroactive 1.2.

Retroactive 1.2 contains bug fixes and additional enhancements:
- Restores the ability to add adjustments and use Quick Brushes in Aperture
- Restores the ability to print photos in Aperture and iPhoto
- Resolves an issue where Aperture and iPhoto may fail to launch (Error 13)
- Adds support for modifying Aperture and iPhoto to be compatible with macOS Catalina before upgrading to macOS Catalina

**Comment by marmon23** [comment]
Thanks a lot. I just saw your email and will try that now.

Best.

__martin
