### ISSUE TITLE
How can I Un-Instal the App? Other than removing it to the trash

### ISSUE THREAD

**Issue by panahead** [cormiertyshawn895/Retroactive#40]
How can I Un-Instal the App? Other than removing it to the trash? Can I  remove any preferences from the library etc.?
Now that Apple has fixed the "Remote" app I no longer need to use Retractive and have 2 music apps... iTunes and Music on my machine.. What I am looking for is a way to control the volume of the Music app on my desktop via a keystroke when the app is not in the foreground... IE: I am listening to music via the music app but am on Safari.. the phones rings and I want to quickly lower the volume in the Music app without having to go back to Music... Also I am using "Airplay to send music to separate zones in my house... there used to be an app called Sizzlekeys.. but with Catalina it no longer works... I found this app https://github.com/alberti42/iTunes-Volume-Control and it works fine on my wife's computer that never had retroactive installed... but I have 2 machines both running Catalina and it doesn't work on either machine? I had previously installed Retractive on both of those machines... thoughts? suggestions?

Thanks,

**Comment by cormiertyshawn895** [comment]
To uninstall an app you have installed through Retroactive, just move it to the Trash.
