### ISSUE TITLE
Aperture issues with sonoma

### ISSUE THREAD

**Issue by teofiloX** [cormiertyshawn895/Retroactive#401]
In Aperture (after sonoma update?) the editing toolbars (for rotating cropping etc...) are gone in fullscreenmode and viewer mode.
Fullscreen toolbar appears sometimes in upper third but is not accessible.
Crashig more frequent (maybe because of this).
Would be great if this could be fixed.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
