### ISSUE TITLE
Aperture on Sonoma

### ISSUE THREAD

**Issue by foggy09** [cormiertyshawn895/Retroactive#403]
I have the original DVD and tried to install on Sonoma but it says can't install Failed.
Any ideas how I could install it so I can run Aperture 2 with Retroactive 2?

**Comment by phrank303** [comment]
I can't remember how I’ve installed Aperture, but Aperture version 3.6 is running under Mac OS 14.
Anyway, it's useless, because RAW files will be rendered new and displayed as "Unsupported image format"…
I haven't found a workaround yet.

**Comment by foggy09** [comment]
Thanks for the info. Much appreciated

**Comment by ttimes** [comment]
Also, selecting the Settings menu results in a crash. Still, that it works at all is very impressive. Thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
