### ISSUE TITLE
iTunes files with umlauts and accent marks are disappearing

### ISSUE THREAD

**Issue by sewolawen73** [cormiertyshawn895/Retroactive#405]
This is a strange thing I noticed happening.  I run iTunes via Retroactive (the latest version) on Mac OSX Sonoma 14.1.2 and link my files on a WD external drive ( formatted to exFAT).  Yesterday I noticed that bands or tracks that have accent marks or umlauts (like Motörhead, Blue Öyster Cult, or tracks by Magma) would disappear off my hard drive every time I'd try to play the tracks or just pass through them.  I do have my entire library saved in 2 different hard drives, but this is really annoying to have to keep replacing my files only to have them disappear. (and I don't want to have to rename the files without the accent marks.  This is over 30,000 music files that I've curated for 15 years!)

Please help!

**Comment by RedTartan04** [comment]
I vaguely remember this has been a problem with iTunes years ago and my also be linked to exFAT? Not sure. Did it work for you with older iTunes on older macOS?

**Comment by sewolawen73** [comment]
Yes.  Everything worked well up until recently when this started happening.  Basically, I reformatted this live drive to APFS and the files work fine now. It's annoying that I had to do that, but glad that I didn't lose any files in the process.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
