### ISSUE TITLE
Aperture problem in Catalina

### ISSUE THREAD

**Issue by Lamision11-2019** [cormiertyshawn895/Retroactive#406]
Until recently I experienced no issues with Aperture 3.6 in Catalina.  But in the past weeks I can no longer export an Aperture Library to an external hard drive.  When I try and export I receive a warning saying: "The library has not been exported to "(null)" because the operation was cancelled.  And tonight when I open a Library and click on an image the image turns black and  within seconds and stays black.  
Tonight I backed up my Mac on an external SSD using Time Machine and tried to restore the OS with the Time Machine backup.  The problem persists and has become worse after the OS was restored from the Time Machine copy.  Now when I open the library every image in the selected Project will turn black and .. one by one... until the entire Project is blacked out.
Does anyone have any idea as to resolve this problem?  Can I reinstall Retroactive without destroying my entire Aperture Library?  Now I can't even back up any of the files in my numerous Projects as every image turns black when I click on the project, and I can't export the project without getting that warning mentioned above.  I have years of images in this library, so any advice would be much appreciated.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
