### ISSUE TITLE
Aperture 3.6 Help file

### ISSUE THREAD

**Issue by buvoltz** [cormiertyshawn895/Retroactive#407]
It's great to be able to run Aperture 3.6 on Mac Ventura 13.6! I installed on my MacBook Air M1. When I open "help" in the top menu it displays but when I click on a topic I get an error of no internet connection. I have Aperture 3.6 working on an iMac running High Sierra and the help system works fine. Thanks much!

**Comment by buvoltz** [comment]
Today I installed on my 2017 4k Retina iMac in my studio and Aperture 3.6 works fine, except the same help issue with no internet message while my WIFI is working fine in all other apps. Also, on both my 2020 M1 MacBook and the 4k Retina iMac Loupe works fine but does not have the black outline. This may be an issue with Retina displays? This makes it hard to see and move but it will display the magnification values so if I click just above I'm able to move the lens. Both Macs are running Ventura 13.6. I'm very happy to have Aperture running on these more modern Macs I have! Before your software I was limited to just my 2011 iMac with High Sierra.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
