### ISSUE TITLE
iTunes can't sync (to iPod) - dont have enough privileges - fixed.

### ISSUE THREAD

**Issue by Kyzerii** [cormiertyshawn895/Retroactive#409]
Hey everyone. Wanted to quickly leave this fix I found where iTunes couldn't sync music or anything to my iPod classic giving the error that you dont have enough privileges. I spent 3 hrs looking around the internet to try find a fix however I couldn't find any. looking through the GitHub comments it seems the author has abandoned this project as he hasn't responded since like 2020 so contacting him wouldn't help. I spent another few hrs trying to fix this till I did so and here it is. first off make sure that you aren't getting the pop up saying this iPod is in use by another computer. if you are then you can find the fix for that under the GitHub post by the author. just eject and unplug iPod, run "killall AMPDevicesAgent" in terminal, then replug iPod. Then to fix the issue I had I had a feeling it was to do with access/privelages thanks to the code. I had enabled full disk access but that wasn't helping, Then finally the solution I found was to go into applications folder or wherever your iTunes is stored. right click it and click get info. then go down and expand the section called sharing and privileges. then click the lock icon and enter your password to enable editing. then set all the names under the "names" section to read and write. then in the Botton click the plus icon and add your name onto the list (my name wasn't on it automatically) then make sure that's also set to read and write. then shut the lock icon by clicking it again. then restart iTunes. after doing that I can finally sync to my iPod . YAAAAY. hope this helps.

**Comment by wwwonka** [comment]
Hey @Kyzerii, thank you for sharing. 

May I ask if you are on Apple Silicon or Intel and which OS you are using. For me the eperience has been highly volatile, as in my iPod classic 7th gen will show up 10% of the time only to show that I must restore it.

I am on Sonoma and M1 Max, from what I read here, @cormiertyshawn895 is saying himself that things are not possible on Apple Silicon.
https://github.com/cormiertyshawn895/Retroactive/issues/289#issuecomment-1235054919

An image, to make things clearer, this is as far as I can manage to go, (even when changing the permissions as you proposed):
![Screenshot 2023-12-31 at 02 44 29@2x](https://github.com/cormiertyshawn895/Retroactive/assets/16738328/933700ad-b85c-4e01-b612-8adfb129fa42)

Quite frustrating.
But... Are you saying there might be a chance, actually?

**Comment by wwwonka** [comment]
Ok...

After much experimentation, I can say that it does in fact work (partially) on Apple Silicon.

Seems like it's working perfectly fine with an iPod 5th Generation but won't make a 7th gen classic even appear.

The other thing I can say is that it only works with iPods formatted in HFS+. Having a FAT partitionned iPod will make iTunes crash.

I am currently on Sonoma 14.2.1 as of writing this message.

If someone has better results with a 7th gen classic, please feel free to join this thread. I would be very happy to make it work; I'll be using Swinsian in the meantime.

**Comment by the-P1neapple** [comment]
> May I ask if you are on Apple Silicon or Intel and which OS you are using. For me the eperience has been highly volatile, as in my iPod classic 7th gen will show up 10% of the time only to show that I must restore it.

Hey @wwwonka I was having the same issues as you on an M2 Macbook Pro with my Shuffle Gen 4. I found that by running iTunes as sudo with `sudo /Applications/iTunes.app/Contents/MacOS/iTunes` was the only way around this for me so it would work 100% of the time.

Let me know if this works out for you.

**Comment by wwwonka** [comment]
Hey @the-P1neapple,
Glad to hear you got things working on your side. 

Sadly no,my 7th gen classic remains inivisible to iTunes 12.9.5 even if Im opening iTunes as sudo; 

I find it even weirder that iTunes 11.4 recognizes it without any fuss...
But that avenue remains unreliable as it crashes as as soon as I try to copy a song over to the iPod.

I've settled with Swinsian for now but I miss iTunes for the podcasts and look & feel.

Sighs.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
