### ISSUE TITLE
iTunes on macOS Sonoma Does Not Connect to Apple Servers

### ISSUE THREAD

**Issue by pedropablopicasso** [cormiertyshawn895/Retroactive#410]
I updated macOS from Ventura to Sonoma this past week and iTunes has had issues connecting to Apple's servers since, meaning no Apple Music nor iTunes Store connectivity to speak of. I consistently get a pop-up every time I open the program, after it asks me to sign in to my Apple ID with an "iTunes Store session has expired" message.

"There was a temporary problem completing your request. An unknown error occurred (-45016). Try again later."

I'll probably have to downgrade back to Ventura from here, but I'd like to know if there is any other workaround for the time being.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
