### ISSUE TITLE
Aperture cannot print books

### ISSUE THREAD

**Issue by klod44** [cormiertyshawn895/Retroactive#411]
Aperture works fine both on my macmini with sonoma and macbook air with Monterey

I can print single pictures, but I cannot print books. Aperture actually checks all pages, and then, nothing happens: no dialog box for choosing paper format or pages to print. Nothing, but I can go on editing my book. Just I cannot print it.

I must revert to Catalina (on my macbook air) to print my books, which is rather cumbersome.

thank you for helping

Claude

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
