### ISSUE TITLE
Is Retroactive abandoned at this point?

### ISSUE THREAD

**Issue by thisplantguy** [cormiertyshawn895/Retroactive#412]
@cormiertyshawn895 Like some others have mentioned, Retroactive seems to be fully broken as of Sonoma. I saw the last update was more than 1 year ago. I don't want to look a gift-horse in the mouth, but are you planning on updating this software at any point in the future?  I and tons of other folks would really love that! Or, if anyone else can pick up the mantle, that would be great as well.

**Comment by Edern1** [comment]
I use aperture 3.6 since many years.
After upgrading to Sonoma 14.3 it won't open again.
Is their a chance for the future that aperture will run again.
For me the best software to organize and edit images.

**Comment by wlwinston28** [comment]
Yes, Shawn, you're a genius. Can you update Retroactive so as to allow Aperture to work on Sonoma 14.3 and beyond? I need at least one more opportunity to export my Aperture libraries to folders on my hard drive from which I can create Lightroom catalogs. Hoping.

**Comment by paulotaviodr** [comment]
> @cormiertyshawn895 Like some others have mentioned, Retroactive seems to be fully broken as of Sonoma. I saw the last update was more than 1 year ago. I don't want to look a gift-horse in the mouth, but are you planning on updating this software at any point in the future? I and tons of other folks would really love that! Or, if anyone else can pick up the mantle, that would be great as well.

It broke as of Sonoma 14.2 Public Beta 4. Until 14.2 PB3 it was working just fine (well, at least iPhoto was).

It seems to be that some of the required components are no longer situated in the same folders on macOS. I've tried doing some changes, but it's more complex than just moving files (and my knowledge allows). However, it does not seem overly complicated.

We need a fork. This dev did a tremendous job with Retroactive (have y'all seen his Medium post explaining how he made it possible?) but it also seems that he's "moved on"... so it's time for a fork.

**Comment by cormiertyshawn895** [comment]
Thanks everyone for reporting this issue. [Retroactive 2.1](https://github.com/cormiertyshawn895/Retroactive/releases) resolves the problem where Aperture and iPhoto quit unexpectedly on macOS Sonoma 14.2 or later.

Retroactive only receives limited support. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by wlwinston28** [comment]
Many thanks— it works!

ww

**Comment by thisplantguy** [comment]
Thanks Tyshawn for doing 2.1! At least for me though, it’s not working. I just downloaded it, and I’ve got csrutil disabled for a different reason, but that should let Retroactive do its thing. However, even after opening it up by right-clicking and clicking open, the icon does the “opening” animation quite briefly but then nothing occurs. I also had Console open and was streaming logs, but am not sure what I should be looking for.  I’m on an M2 Ultra Mac Studio with MacOS 14.3.1 for reference.

I also ran the command to disable Gatekeeper before trying to run Retroactive, but ran into the same issue.

**Comment by Edern1** [comment]
Many many Thanks Tyshawn for doing this upgrade again. Using Sonoma 14.3.1 it works on a Intel iMac 2019
The only thing it starts with reporting this system config isn't compatible with the installed ImageIO-Version, but this happened also before by Sonoma 14.2

**Comment by DavidJameson** [comment]
---You should transition from Retroactive to a wide range of supported apps---
The thing is, I'm trying to transition BACK to Aperture.  Lightroom sucks and I was thrilled to discover your stuff that made Aperture work again.
Unfortunately I discovered that if I open Preferences (which I wanted to do to change the location for the library), Aperture just instantly crashes.
