### ISSUE TITLE
iTunes 11.4 crashes trying to sync to iPod Classic

### ISSUE THREAD

**Issue by jck946** [cormiertyshawn895/Retroactive#414]
My client just bought a 160GB iPod classic online. We installed Retroactive 2.0 and through it, iTunes 11.4 on his Intel iMac running Ventura 13.6.3. Created a new iTunes Library, added the contents of the Music library, exported playlists from Music as XML files, imported to iTunes. Connected iPod. Went to Music tab, set to sync entire library (±55GB). Sync starts, iTunes crashes after a few seconds. Now whenever iTunes is launched with iPod connected, it tries to sync and crashes. Any suggestions for how to proceed? Is it likely a corrupt prefs file, permissions issue, version compatibility,....? Much gratitude for the Retroactive software and this forum.

**Comment by SunnyFloppyDiskStudios** [comment]
does itunes have `full disk access` permission in system settings?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
