### ISSUE TITLE
iTunes 11.4 not syncing

### ISSUE THREAD

**Issue by ghost** [cormiertyshawn895/Retroactive#415]
I have an M1 Mac and installed iTunes version 11.4, I tried to sync my iPhone 4 but as soon as I click on Sync it kind of starts and then finishes, but this of course doesn't do anything.
I have attached a screenshot video of what happens. 

https://github.com/cormiertyshawn895/Retroactive/assets/150492969/e2aee32e-c1cd-4eaf-9da0-08bb2e456678

**Comment by cormiertyshawn895** [comment]
v

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
