### ISSUE TITLE
Installing an older OS on my Imac

### ISSUE THREAD

**Issue by philsfilm** [cormiertyshawn895/Retroactive#416]
I downloaded the Mojave installer but, no matter what external drive I tried to assign it to, I got the message that it was “too old to open on this Mac OS”. Is there any way to get around this? My goal is to be able to run FCP 7 after installing Retroactive.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
