### ISSUE TITLE
Swinsian as option for iTunes migration

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#417]
I believe that [Swinsian](https://swinsian.com/) offers a close one-to-one migration + feature set from iTunes. There is a new beta that is in progress that seems to be pretty close to parity with iTunes and its capacity to import.

The developer, James, is responsive and seems vested in his product. I find this encouraging and comforting since a solid iTunes replacement is so sorely needed that has a complete one-to-one feature parity.

At this point the price point of Swinsian is most certainly worth it given the time investment so many of us have made in trying to keep iTunes going. 

It is my hope that James will continue to carefully review iTunes 12.9.5.5 and get us to the point where it is a precise duplication as a kind of benchmark and then only add in new features that don't change the UX considerably.

I suppose he could also have a "feature mode" that could go "back in time" to previous iTunes versions UI/UX as well if desired, but iTunes 12.9.5.5 is certainly the lock-in point for my preferences with nearly all functionality.

**Comment by cormiertyshawn895** [comment]
Great recommendation! Added [Swinsian](https://swinsian.com) to [Transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

To get the latest features in Swinsian 3 Beta, open the Swinsian menu, then press and hold the option key and choose “Check for Updates (Beta)”.

**Comment by ylluminate** [comment]
Also without having to turn that on and to start with the beta, there is this:
https://swinsian.com/sparkle_beta/sparklecast.xml

**Comment by ylluminate** [comment]
Two other things to note:
- Swinsian's memory footprint is multiple times smaller than iTunes.
- To perform a proper migration one should export their iTunes library before importing it so as to be sure to capture everything since Apple doesn't reliably save the xml library file any longer: 
![export](https://p153.p0.n0.cdn.zight.com/items/QwuX4949/2d69f1b2-a4e2-4055-bbe9-99e7c73b7eb7.png?v=89bc1640558ff83bb49b5e825b125410)
