### ISSUE TITLE
Logic Pro 9 won't launch

### ISSUE THREAD

**Issue by Adollars2000** [cormiertyshawn895/Retroactive#418]
Hey, I hope that you're still supporting this project.
Everytime logic will finish downloading the essential tools it will fail and crash/quit. I'm running MacOS High Sierra 10.13.6 on a Mac Mini late 2014

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
