### ISSUE TITLE
Open iTunes by default instead of Music

### ISSUE THREAD

**Issue by mmshivesh** [cormiertyshawn895/Retroactive#42]
Is there any way to open iTunes by default instead of the Music app when using the media controls or when a direct link is opened (for example: shared apple music links)?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
