### ISSUE TITLE
ITUNES IS NOT WORKING!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by CrappleMuzik** [cormiertyshawn895/Retroactive#420]
I bought a brand new Macbook Pro and it will not let me use iTunes.
  Model Name:	MacBook Pro
  Model Identifier:	Mac15,7
  Model Number:	MRW23LL/A
  Chip:	Apple M3 Pro
  Total Number of Cores:	12 (6 performance and 6 efficiency)
  Memory:	36 GB
  System Firmware Version:	10151.81.1
  OS Loader Version:	10151.81.1
  Activation Lock Status:	Enabled

I've tried everything. 
Removing the preferences file, which I have none.
Rebooted the computer
Reinstalled multiple times
Authorized the computer
Rebooted the program only
Signing into iTunes, won't let me do that
Disabled the option of syncing any devices automatically
 
I open up iTunes and get the error code: 42408
Then when I try to sign into iTunes, I get the temp error of 9039.
Then a following error after I click ok of 11571

What is that I'm doing wrong? I installed Retroactive exactly as instructed and then installed iTunes through that.

**Comment by CrappleMuzik** [comment]
waiting...

**Comment by ylluminate** [comment]
Given the state of things and the recommendation by @cormiertyshawn895, I would highly suggest you move to [Swinsian](https://swinsian.com/). I have moved to the beta (Version 3.0 Preview 13 (595)) now and am highly pleased with it and the developer's responsiveness and care for his app. This has now proven to be on par wrt features with and even uses less system resources than iTunes.

**Comment by mirko77** [comment]
@ylluminate thanks for the suggestion. However, if I am not mistaken, Swinsian does not feature crossfade and loudness normalisation (ReplayGain or similar) which are available in iTunes.
At least, not on the stable version (2.3.6)

**Comment by ylluminate** [comment]
@mirko77 I'm using Swinsian 3.0 Preview 15 (597) (You get get from here and use the free trial: https://swinsian.com/sparkle_beta/sparklecast.xml) and it's pretty friggin' awesome. It has gapless playback and I have zero problems with volume levels.

Check out the changelog for all 3 releases to see if what you want is addressed:
https://www.swinsian.com/sparkle_beta/release_notes/changelog_3.0.0_597.html

And if you've got a problem, just email James. He's pretty awesome and cares about making great software.

I've migrated an enormous library over to it and it's really fantastic compared to iTunes now. I'm really grateful for the less system resource usage and more responsive feel.

**Comment by Dr-Reality** [comment]
Hi all, I'm definitely in a similar boat, experiencing the same 42408 error – in my case when trying to select the .itl iTunes library file imported from my previous laptop, where I had managed to run iTunes on Retroactive perfectly, thanks to cormiertyshawn895. Also running a new M3 (Air) with Sonoma (14.3).

Anyone have more insight on this? For my part, I don't have strong feelings about iTunes features – I just want to keep my music library, with playlists and 'date added' info intact. So thanks @ylluminate for the Swinsian recommendation, but I'm assuming this won't be possible there. Does anyone know if this is a compatibility issue with our hardware? Is it an issue specifically with importing an old iTunes library from another system? Any solutions, no matter how laborious, would be miraculous to me!

**Comment by ylluminate** [comment]
Fwiw @Dr-Reality, I was able to import these attributes with my importation. I'm presently on Swinsian 3.0 Preview 18.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by ylluminate** [comment]
Thanks for making Retroactive a reality for as long as you did @cormiertyshawn895. I did get some good years of use out of it before moving on to Swinsian.
