### ISSUE TITLE
Chroma Keyer not working FCP7.

### ISSUE THREAD

**Issue by ChristoferKraft** [cormiertyshawn895/Retroactive#421]
Yeah I was trying to key some green screen stuff out it did not work.
Any help?
Also It won't let me zoom on the video and time line like it does on the og version when I pinch trackpad.
Crk.
Thanks.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
