### ISSUE TITLE
Working Last.fm Scrobbler for iTunes 12.9.5.5

### ISSUE THREAD

**Issue by nemorosus** [cormiertyshawn895/Retroactive#422]
Hey all... I had Retroactive installed since who knows when, but I remember having issues with the scrobbler - finding only ones that recognise the Music app, and by no chance iTunes.

https://github.com/nemorosus/Last.fm-for-Retroactive-iTunes

This is the one that works with Ventura 14.4, works with iTunes 12.9 via Retroactive and scrobbles without any major issues so far.
I only don't know if it would work with Apple ARM, however on that someone with an Apple chip can chime in if they're curious :)

Much luv to the Retroactive crew,
You're my freaking idols!
💕

![Screenshot 2024-03-22 at 04 06 40](https://github.com/cormiertyshawn895/Retroactive/assets/6278519/37e544e4-fa48-44bd-84f6-752e81626dd1)

![Screenshot 2024-03-22 at 04 15 12](https://github.com/cormiertyshawn895/Retroactive/assets/6278519/e243591b-bfea-4e51-8b39-777dbcd82c5c)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
