### ISSUE TITLE
FC7, Retroactive and MOTU HDX-SDI (PCIe)

### ISSUE THREAD

**Issue by m0m0g33k** [cormiertyshawn895/Retroactive#423]
Hi, 

I have acquired the MOTU HDX-SDI PCIe video interface, that only works with FC7
https://motu.com/video-products/hdx-sdi/specs.html

When I run FC7 with Retroactive applied, works fine, but in order to install the Sequence, Capture, Control presets and Drivers i need to reinstall a package, the MOTU Universal Video Installer (https://motu.com/en-us/download/#category=4&product=252)

I have now the next versions in the MOTU interface: driver 2.34, firmware 1.08b8, Bootloader 1.0

![image](https://github.com/cormiertyshawn895/Retroactive/assets/13736711/c7891af1-8412-401e-a536-15cad4a97cd9)
I am running macOS Mojave 10.14.6

The problem is, when I reinstall the drivers/presets (after patch with Retroactive), FC7 don't starts.

Can this be handled as an issue or request?

Thanks a lot.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
