### ISSUE TITLE
iTunes 12.9.5 URL

### ISSUE THREAD

**Issue by furbies** [cormiertyshawn895/Retroactive#424]
Hi

is it possible to get the url for the iTunes 12.9.5 dmg that Retroactive downloads / uses?

I'm wanting to uninstall iTunes (which I installed using Retroactive on Monterey) because I've finally given up using iTunes because it is unable to import CDs or do backups.

If I had the iTunes dmg I've got 2 Apps that can read the install script(s) and I'd be able to see where iTunes secreted all it's bits and bobs and then I'd be able to manually delete all of iTunes

tia

furbies

**Comment by furbies** [comment]
Or can I just AppCleaner from FreeMacSoft to "delete" or "uninstall" all it can locate ?
![Screen Shot 2024-04-21 at 2 36 34 pm](https://github.com/cormiertyshawn895/Retroactive/assets/31633438/bdea131e-536f-4ebe-8d87-2b64cf5545d8)

**Comment by cormiertyshawn895** [comment]
Using AppCleaner to uninstall should be fine.

Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
