### ISSUE TITLE
Itunes 11.4 crashes on Ventura

### ISSUE THREAD

**Issue by elfuego1994** [cormiertyshawn895/Retroactive#425]
I downloaded retroactive to be able to sync my music collection with my ipod classic & found that the only version of itunes where that could work is in the 11.4 classic version, it worked very well until I mindlessly upgraded my mac software to ventura, from that point I cannot open it anymore. 
it gives me different error messages before shutting down, one is the version I'm using is too old and in another one it tells me my library got corrupted and just deletes everything and starts a new library.
Sometimes it can run for a bit until I open settings, or try to sync my ipod. 
I've tried reinstalling many times but every time again it crashes. 
Is there anything I can do to prevent this? All help would be greatly appreciated.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
