### ISSUE TITLE
Aperture crashes while opening a RAW image in Monterey

### ISSUE THREAD

**Issue by GregorPQ** [cormiertyshawn895/Retroactive#426]
[Aperture crash.rtf.zip](https://github.com/cormiertyshawn895/Retroactive/files/15132110/Aperture.crash.rtf.zip)

Jpeg-images work fine, including editing and exporting.
The crash happens always while loading the RAW data, display of the preview works fine.
Here is the report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Aperture [13055]
Path:                  /Applications/Aperture.app/Contents/MacOS/Aperture
Identifier:            com.apple.Aperture3
Version:               3.6 (3.6)
Build Info:            Aperture-500021000000000~3
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-04-26 16:46:03.6380 +0200
OS Version:            macOS 12.7.4 (21H1123)
Report Version:        12
Anonymous UUID:        101FAE15-7235-C44F-EB89-BB0302C1000F

Sleep/Wake UUID:       81F63EF4-A0EE-42C2-A286-66AEFF759492

Time Awake Since Boot: 45000 seconds
Time Since Wake:       27023 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Application Specific Signatures:
Graphics kernel error: 0x00000001

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff80f4e5fce __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80f51c1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff80f467d14 abort + 123
3   libGPUSupportMercury.dylib    	    0x7ff91fc2362f gpusGenerateCrashLog + 157
4   AMDRadeonX4000GLDriver        	       0x1048cb022 gpusKillClientExt + 9
5   libGPUSupportMercury.dylib    	    0x7ff91fc24a23 gpusSubmitDataBuffers + 164
6   AMDRadeonX4000GLDriver        	       0x1048a5440 glrATI_Hwl_SubmitPacketsWithToken + 112
7   GLEngine                      	    0x7ffa28597844 glFinishRender_Exec + 43
8   Aperture                      	       0x1001318a8 0x100112000 + 129192
9   AppKit                        	    0x7ff81260b6d3 -[_NSOpenGLViewBackingLayer display] + 824
10  QuartzCore                    	    0x7ff816b2362b CA::Layer::display_if_needed(CA::Transaction*) + 873
11  QuartzCore                    	    0x7ff816c7af86 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 640
12  QuartzCore                    	    0x7ff816b04a89 CA::Transaction::commit() + 777
13  AppKit                        	    0x7ff8120c2d71 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285
14  AppKit                        	    0x7ff81280ad3c ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
15  CoreFoundation                	    0x7ff80f5e2615 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
16  CoreFoundation                	    0x7ff80f5e24aa __CFRunLoopDoObservers + 543
17  CoreFoundation                	    0x7ff80f5e192c __CFRunLoopRun + 840
18  CoreFoundation                	    0x7ff80f5e0f24 CFRunLoopRunSpecific + 562
19  HIToolbox                     	    0x7ff8187015e6 RunCurrentEventLoopInMode + 292
20  HIToolbox                     	    0x7ff818701213 ReceiveNextEventCommon + 283
21  HIToolbox                     	    0x7ff8187010e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
22  AppKit                        	    0x7ff811f56aa9 _DPSNextEvent + 927
23  AppKit                        	    0x7ff811f55166 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
24  Aperture                      	       0x10057ea81 0x100112000 + 4639361
25  AppKit                        	    0x7ff811f47818 -[NSApplication run] + 586
26  ProKit                        	       0x10113a39a NSProApplicationMain + 333
27  Aperture                      	       0x1001220b4 0x100112000 + 65716
28  Aperture                      	       0x100121a44 0x100112000 + 64068

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
