### ISSUE TITLE
iTunes 12.9.5 network sharing skipping songs

### ISSUE THREAD

**Issue by james10424** [cormiertyshawn895/Retroactive#427]
I had 12.9.5 on Mojave, playing over the local network on Windows's 12.9.5 did not skip any songs.

Now I have 12.9.5 on Monterey and playing over network on Windows is skipping every song at random time (same song, random skip). Sometimes after 30s, sometimes at the end.

Does Retroactive modify iTunes in any way that could affect this network sharing function?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
