### ISSUE TITLE
Retroactive Issu

### ISSUE THREAD

**Issue by lf111** [cormiertyshawn895/Retroactive#43]
Hello, 
Retroactive open well, but when I click on any app to unlock (Final cut Pro 7 for example), nothing happens, no window appears...
On High Sierra 10.13.6
Thanks a lot for your help

**Comment by cormiertyshawn895** [comment]
Can you upload a screenshot of what you see?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
