### ISSUE TITLE
Request: Preview 5 Support

### ISSUE THREAD

**Issue by RC128tech** [cormiertyshawn895/Retroactive#430]
Thanks for Retroactive, this is a fantastic tool.

I'm still using several OS X tools from Snow Leopard in Sonoma.

- TextEdit 1.6 is working with patched info.plist. I prefer the seperate search/replace window.
- Calculator 10.8 is also working with patched info.plist. I prefer the classic design.
- iTunes 10.7 is working thanks to Retroactive. It sounds better than Apple Music on my 2015 MacBook Pro.

I would like to get support for Preview 5.0.3 from Snow Leopard. I'm using the tool for more than a decade
and found no suitable replacement. The important feature is the ability to paste-in-place, so the
clipboard content is not centered. Preview 5 requires from Snow Leopard 10.6.8 this file:

_/System/Library/PrivateFrameworks/MeshKit.framework_

In Mavericks and Yosemite Preview 5 is working after installing the framework in the correct place,
but crashes when opening a PDF file. I solved the problem by removing the PDF file support entries in the info.plist.

Best Regards.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
