### ISSUE TITLE
Request: Mojave iTunes Support

### ISSUE THREAD

**Issue by RC128tech** [cormiertyshawn895/Retroactive#431]
There should be support for Mojave. If the iTunes application is faulty in Mojave,
there is no way to reinstall it because there is no standalone.

I used Retroactive in Mojave by changing the system version in

_/System/Library/CoreServices/SystemVersion.plist_

the MinimumRequiredSystemVersion from 14 to 15. It worked and now I install
all iTunes versions. I used 10.7 again and it works.

However, the after changing the SystemVersion.plist to 14 again, iTunes won't start
because it requires version 15. I could solve the problem by copying the program

_/Applications/iTunes.app_

into another folder.

So, it's not difficult: Change in Retroactive the SystemVersion from 15 to 14,
in the main tool and the created executables.

Best Regards

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
