### ISSUE TITLE
Internet Connection messages

### ISSUE THREAD

**Issue by RC128tech** [cormiertyshawn895/Retroactive#432]
Hello,

is it possible to disable messages for the internet connection or completely delete internet access?
iTunes opens a requester on every start for an internet connection.

Best Regards

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
