### ISSUE TITLE
aperture: several features disappear in sonoma 14.5

### ISSUE THREAD

**Issue by klod44** [cormiertyshawn895/Retroactive#433]
several buttons or fields are not displayed: 
-in navigation window
   - search box
   - search filters
-in display window
   - 100% diplay 
   - order book button
 
moreover, the print button or the print book item in file menu do not do anything

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
