### ISSUE TITLE
aperture: several features unavailable in sonoma 14.5 update

### ISSUE THREAD

**Issue by klod44** [cormiertyshawn895/Retroactive#434]
several buttons or fields are not displayed:

**in navigation window**
1. search box
2. search filters

**in display window**
1.     100% displaybutton
2.      display scale slider
3.     order book button
4.     theme and hardcover buttons
5.   moreover, the print button and the print book item in file menu do not do anything

I love using aperture for editing photobooks, but it is becoming quite awkward and I must revert to catalina to get a usable version. Too bad as I plan to purcahse a M3 macbook air.
Thank you for helping

Claude

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
