### ISSUE TITLE
aperture in sonoma 15.4: sorry, a few more issues

### ISSUE THREAD

**Issue by klod44** [cormiertyshawn895/Retroactive#435]
several buttons or fields are not displayed:

**in navigation window**

1.     search box missing
2.     search filters missing

**in display window**

1.  100% displaybutton missing
2.  display scale slider missing
3. order book button missing
4. theme and hardcover buttons both missing
5. edit content and edit layout buttons both missing 
6. print button and  print book item in file menu do not do anything

I love using aperture for editing photobooks, but it is becoming quite awkward and I must revert to catalina to get a usable version. Too bad as I plan to purcahse a M3 macbook air.
Thank you for helping

Claude

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
