### ISSUE TITLE
Retroactive can't be used to download Pro Application Update 2010-02

### ISSUE THREAD

**Issue by johnklos** [cormiertyshawn895/Retroactive#436]
On a clean Mojave system, Retroactive can't find Final Cut Pro. "Locate Manually..." works, though.

However, the "(2) Download and update to Final Cut Pro 7.0.3 (2010-02)" button can't be used because the "You need to install Final Cut Pro 7 first." message comes up, even after unlocking Final Cut Pro.

Note that Apple no longer hosts the update, so I had to download from Archive.org:

https://web.archive.org/web/20210407052104if_/https://download.info.apple.com/Mac_OS_X/061-8474.20100915.wtoKR/ProApplicationsUpdate2010-02.dmg

Otherwise, this work amazingly. Thanks!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
