### ISSUE TITLE
Rounded corners missing on macOS Sequoia (15)

### ISSUE THREAD

**Issue by theMackabu** [cormiertyshawn895/Retroactive#437]
<img width="1145" alt="Screenshot 2024-07-18 at 12 42 05 PM" src="https://github.com/user-attachments/assets/95c8afff-bfe1-4b58-9b31-be1b40bb417e">
Quite a simple problem, might be impossible to fix but the rounded corners of the app and all dropdowns/dialogs have gone missing.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
