### ISSUE TITLE
AEDeterminePermissionToAutomateTarget issues

### ISSUE THREAD

**Issue by dnicolson** [cormiertyshawn895/Retroactive#44]
Using [Mac Media Key Forwarder 2.8](http://milgra.com/downloads/mmkf/MacMediaKeyForwarder2.8.zip) (the release before it supported Catalina) results in the Touch Bar becoming unusable for controlling media playback.

It looks as if the proxying of iTunes permission requests is the cause of the issue. Is anyone aware of a way to fix this on Catalina? Perhaps changing the bundle identifier could be a solution?

macOS 10.15.2 (19C57)
iTunes 12.9.5.5
Music 1.0.2.37

**Comment by cormiertyshawn895** [comment]
It looks like the ScriptingBridge framework can't find any application with the iTunes bundle identifier.
