### ISSUE TITLE
FCP Suite, DVD Studio...

### ISSUE THREAD

**Issue by ekinoxben** [cormiertyshawn895/Retroactive#45]
I've just tried Retroactive and it work great with FCP. But I wonder if it could be extended to other apps in the suite, like DVD Studio Pro?

**Comment by JohnD0406** [comment]
I would kill for CinemaTools (part of the Final Cut Studio 3 package).

**Comment by snam11** [comment]
if you can add support for DVD studio pro it would be awesome. dvdsp is still the only soft for mac able to create professional dvd images(ddp images).
i guess also compressor is mandatory for having dvdsp working(if the imported media files is not  compatible with dvd standard, it need to be converted using compressor)

**Comment by snam11** [comment]
@cormiertyshawn895 you think is not possible? should we stick on sierra to have dvdsp/compressor working?
I don't mean to put pressure or something, just to know if we can have hopes on it,or we simply need to move on and forget about it...
thanx for your effort and good work with fcp

**Comment by palnudb** [comment]
I too am looking to run FCP Studio 2 and DVD Studio On OSX 10.13.6

TIA palnudb

**Comment by spring63127** [comment]
DVD Studio Please save my life!

**Comment by JeremyJayN** [comment]
I'm a professional DVD author, doing Hollywood work. Another passionate request for DVD Studio Pro,please. I'm so tired of keeping dinosaur computers and OSes running for one app.

**Comment by tombelluk** [comment]
Another request to add DVDSP (and Cinema Tools too please) to the Retroactive fix!! Just had an old ElCapitan machine die and had to install Mojave.... TIA!

**Comment by JeremyJayN** [comment]
Yes please please please!! DVDSP on Mojave would be life changing for me.

Jeremy Neish
Angel Studios - Senior Content Manager,
Multimedia Strategist, & Data Archivist
mobile: (801) 706-4224

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
