### ISSUE TITLE
Playback suddenly no longer works in iTunes 

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#46]
iTunes 12.9.5.5 was working marvelously, but suddenly (no idea what could have changed) playback seems to have broken. Now when I play on any song the play button activates and acts as though it will play, but the time does not progress and no sound is emitted from the computer.

Any thoughts?

**Comment by cormiertyshawn895** [comment]
Which version of macOS are you running, and are you playing from Apple Music or your local iTunes library?

**Comment by twilightsophie** [comment]
This is apparently a problem with iTunes itself, not Retroactive. There are articles about it if you Google. 

I'm having a similar problem but without the visible progress bar. If I double click there's a slight visual flash as though it's adding, then the song doesn't play, with no progress bar at all. Adding to queue just queue's it up, it still doesn't play. It was working fine two weeks ago before I went away.

Upgraded to the newest Retroactive today and re-installed, but no joy. Can "Show in Finder" and "Get Info" and it finds the file but still won't play. Does play in Music. My Mac refuses to upgrade to the newest Catalina though, so I'm stuck on 10.15.2. 

Perhaps triggered by joining Apple Music and then choosing not to show the Apple Music features?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).

**Comment by ylluminate** [comment]
Swinsian 3 (Preview) has been really great as my migration option to keep EVERYTHING intact from iTunes: https://swinsian.com/sparkle_beta/sparklecast.xml

Thanks for keeping things going as long as you did Tyshawn.
