### ISSUE TITLE
Thanks for your excellent App.

### ISSUE THREAD

**Issue by dadatta** [cormiertyshawn895/Retroactive#47]
Retroactive is really cool that can help me run iTunes 10.7 and iPhoto in Catalina. I'm looking forward to Retroactive support for more apps such as iBooks 1.0，Photo Booth 6.0 and Safari 4.0. 
Thank you again.

**Comment by cormiertyshawn895** [comment]
That's a cool request. I'll keep it in mind.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
