### ISSUE TITLE
iTunes on Catalina: no permissions Apple Events

### ISSUE THREAD

**Issue by Larry1976NL** [cormiertyshawn895/Retroactive#48]
In my setup iTunes has to send Apple Events to Radiologik DJ, and vice versa. This won't work. Also the developer of Radiologik can't get it done.

**Comment by cormiertyshawn895** [comment]
It looks like the ScriptingBridge framework can't find any application with the iTunes bundle identifier. This could be #44.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
