### ISSUE TITLE
10.15.4 Beta 2 iTunes error messages at launch

### ISSUE THREAD

**Issue by Rysiek13** [cormiertyshawn895/Retroactive#50]
With macOS 10.15.4 Beta (19E234g), launching iTunes gives error messages 11571 and -42408.

I guess this is it for Retroactive and iTunes?

**Comment by Rysiek13** [comment]
Also... AppleTV is no longer able to “find” the iTunes library for streaming.

**Comment by cormiertyshawn895** [comment]
### Retroactive 1.5 improves iTunes compatibility with macOS Catalina 10.15.4.

- Resolves an issue where authenticating with Apple Music, iTunes Store, or App Store may fail in iTunes 12.9.5 and iTunes 12.6.5 running on macOS Catalina 10.15.4 (-42408, -45076, and 11571).
- Resolves an issue where iTunes cannot read the contents of a connected iOS or iPadOS device.
- Resolves an issue where iTunes 10.7 may prompt to reinstall itself (-42401).
- Adds support for installing iTunes 11.4.

<p align="center">
  <a href="https://github.com/cormiertyshawn895/Retroactive/releases/download/1.5/Retroactive.1.5.zip" alt="Download Retroactive"><img width="282" height="68" src="https://raw.githubusercontent.com/cormiertyshawn895/Retroactive/master/screenshots/resources/download-button.png" alt="Download Retroactive"></a>
</p>

**Comment by Rysiek13** [comment]
Thank you! Will give 1.5 a try.
