### ISSUE TITLE
Retroactive Stalls on Extraction

### ISSUE THREAD

**Issue by CatalinaEstaNoBueno** [cormiertyshawn895/Retroactive#52]
I'm a nobody...  Running Catalina 10.15.3 on a 2019 27inch iMac 6 core i5. I'm trying to run your Retroactive 1.5 and it stalls in the Extract iTunes portion. The first attempt I cancelled it after waiting 2 hours on that step. Second attempt is still stalling after an hour. Any suggestions?
Thanks so much.

**Comment by cormiertyshawn895** [comment]
This sounds like you clicked "Cancel" when Retroactive asked you to enter your password during extraction, which will cause extraction to fail. [The latest version](https://github.com/cormiertyshawn895/Retroactive/releases/download/1.5/Retroactive.1.5.zip) has improved error reporting, and will prompt you if that's the case.

Can you delete Retroactive from your Mac, [download the latest version](https://github.com/cormiertyshawn895/Retroactive/releases/download/1.5/Retroactive.1.5.zip), and try to install iTunes again?

If this still doesn't work, can you try to install a different version of iTunes in Retroactive? For example, iTunes 12.6.5 will install faster even with slow internet connections.
