### ISSUE TITLE
iTunes Playback Stutters when browsing the internet

### ISSUE THREAD

**Issue by spencerjason** [cormiertyshawn895/Retroactive#53]
Running iTunes 12.9.5.5 with Retroactive 1.5 (upgraded from 1.3) and noticed that graphic intensive websites (Facebook, pages with ads, etc) will cause the playback of a song to stutter. Playback is fine once the page loads, but I don't remember this ever happening in 1.3.

**Comment by cormiertyshawn895** [comment]
This is very, very strange. Are you playing local music or streaming songs from Apple Music?

**Comment by spencerjason** [comment]
No subscription to Apple Music, though I do subscribe to iTunes Match so sometimes tracks are pulled from the cloud. Most of them are local files though (certainly the ones in question).

I noticed today that is seems connected to opening or using web browsers only. It will stutter playback simply from launching Safari or Microsoft Edge on my Mac. I can launch pretty much anything else without the same issue, including much more resource-intensive apps like Photoshop, Illustrator, and Word. 

Retroactive 1.5
iTunes 12.9.5.5
MacOS 10.15.3 (Catalina)
2012 Mac Mini Dual-Core i5 w/16GB Ram

**Comment by mmshivesh** [comment]
Can confirm this still happens on Catalina 10.15.6 running iTunes 12.9.5.5 and an active Apple Music subscription. Installed using Retroactive 1.9. 

I have the almost same experience where browsing the internet stutters playback in iTunes

**Comment by spencerjason** [comment]
Since my initial post, I've moved to a 2018 MacMini Six-Core i5 and still experience the issue.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
