### ISSUE TITLE
Cannot open iTunes 11.4 because of iTunes Library.itl file

### ISSUE THREAD

**Issue by rib3ye** [cormiertyshawn895/Retroactive#54]
After clicking `Launch iTunes` through the Retroactive launcher, iTunes starts, then gives the following error:
`The file “iTunes Library.itl” cannot be read because it was created by a newer version of iTunes. Would you like to download iTunes now?`
Then iTunes quits.

I am running Catalina 10.15.3 and I also have Music 1.0.3.1 installed.

**Comment by cormiertyshawn895** [comment]
Hold down the option key on your keyboard and open iTunes from Launchpad, Retroactive, or Finder.

iTunes will ask you to "Choose iTunes Library". Choose "Create Library...", and create a new iTunes library.
<img width="642" alt="choose-library" src="https://user-images.githubusercontent.com/57056759/75851680-33e43b00-5d9f-11ea-827c-a042921b951d.png">
