### ISSUE TITLE
### Retroactive 1.5 improves iTunes compatibility with macOS Catalina 10.15.4.

### ISSUE THREAD

**Issue by markbjohnson** [cormiertyshawn895/Retroactive#55]
### Retroactive 1.5 improves iTunes compatibility with macOS Catalina 10.15.4.

- Resolves an issue where authenticating with Apple Music, iTunes Store, or App Store may fail in iTunes 12.9.5 and iTunes 12.6.5 running on macOS Catalina 10.15.4 (-42408, -45076, and 11571).
- Resolves an issue where iTunes cannot read the contents of a connected iOS or iPadOS device.
- Resolves an issue where iTunes 10.7 may prompt to reinstall itself (-42401).
- Adds support for installing iTunes 11.4.

<p align="center">
  <a href="https://github.com/cormiertyshawn895/Retroactive/releases/download/1.5/Retroactive.1.5.zip" alt="Download Retroactive"><img width="282" height="68" src="https://raw.githubusercontent.com/cormiertyshawn895/Retroactive/master/screenshots/resources/download-button.png" alt="Download Retroactive"></a>
</p>

_Originally posted by @cormiertyshawn895 in https://github.com/cormiertyshawn895/Retroactive/issues/50#issuecomment-590019812_

**Comment by markbjohnson** [comment]
Latest build of Catalina (3/3) with 1.5 (38) using iTunes 12.6.5 still syncs okay with iPad Pro, but now fails with iPhone Pro 11 (worked prior to this build). Error is XXX cannot be used because it requires iTunes 12.10.5 or later. Would you like to download the latest version of iTunes now?" error.

**Comment by cormiertyshawn895** [comment]
Older versions of iTunes aren’t able to communicate with the latest iPhone. This is a limitation in iTunes.
