### ISSUE TITLE
iPhoto Library Manager issue

### ISSUE THREAD

**Issue by timwarner69** [cormiertyshawn895/Retroactive#56]
I have a large library of photos, so I use iPhoto Library Manager to control libraries of my photos & open up iPhoto accordingly. This obviously stopped working when I upgraded to Catalina. I installed your software, which worked a treat & allowed iPhoto to open again. However, when I open iPhoto through iPhoto Library Manager it gives an error: "iPhoto Library Manager was unable to open the library 'x'. The library 'x' is of a newer version (9.6.1) than the installed version of iPhoto (null)". iPhoto shows version 9.6.1 (910.42) when opened, so I don't understand.

Retroactive version 1.5.
iPhoto Library Manager version 4.2.7 (954)

Please help.

**Comment by Tetonne** [comment]
same issue here with 10.15.4

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
