### ISSUE TITLE
iTunes Download Size

### ISSUE THREAD

**Issue by atlasvii** [cormiertyshawn895/Retroactive#57]
Moreso a question perhaps, but why is the download size for iTunes over 5gb? I was tethering because I assumed it'd be about 150mb.

Thanks!

**Comment by cormiertyshawn895** [comment]
> I was tethering because I assumed it'd be about 150mb.

I am very sorry to hear that Retroactive has used more data than expected when tethering. I will add a download size alert for tethered Wi-Fi connections in the future.

> Moreso a question perhaps, but why is the download size for iTunes over 5gb?

iTunes 12.9.5 is not available as a standalone download. Therefore, Retroactive needs to download the full macOS Mojave installer to extract iTunes 12.9.5.

**Comment by blaiddu** [comment]
how completely delete all unnecessary stuff after deleting iTunes? were is located. iTunes 12.6.5 was installed

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
