### ISSUE TITLE
Logic Pro 9 does not detect any third party plugins

### ISSUE THREAD

**Issue by lottanbettan** [cormiertyshawn895/Retroactive#58]
On **Mojave** with **Logic pro 9.1.8** and **Retroactive 1.6**:

Logic Pro 9 does not detect any external third party 32-bit plugins (installed in HD/Library/Audio/Plug-Ins/Components/). I only tried with 32-bit plugins so I do not know about 64-bit.

All plugins runs perfectly as stand alone apps, so the plugins themselves are not the problem.

Error message on Logic start after new external plugin installation: "the 32-bit AU server has quit unexpectedly". After a restart this error is gone, but still no plugins.

I tried trashing "com.apple.audiounits.cache", rebooting computer and restarting Logic, without success. The only effect is that Logic re-scans all 26 internal apple plugins (not located in HD/Library/Audio/Plug-Ins/Components/ by the way), but still does not see the external third party plugins.

Otherwise everything works fine, including all internal apple plugins! Great app!

**Comment by lottanbettan** [comment]
An update, now Mojave with Logic pro 9.1.8 and Retroactive **1.7**:

Still the same problem with third party plug ins.

And still "the 32-bit AU server has quit unexpectedly" on app start, even if this is said to be fixed in 1.7. Maybe i'm doing something wrong? Do I have to reinstall Logic to make the new Retroactive 1.7 patching process successful?

If Logic 9 would work with third party 32 bit plugins on newer macOSs you would be crowned as king in some audio forums :)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
