### ISSUE TITLE
Won't use Aperature 3.4.5?

### ISSUE THREAD

**Issue by Laurajeanpt** [cormiertyshawn895/Retroactive#61]
I have the disc and a copied version from my old Mac and when I try to open it with Retroactive it says I need 3.6 version? Can you please verify? Is there any work around?

**Comment by cormiertyshawn895** [comment]
You need to locate a copy of Aperture 3.6 before using Retroactive. 

The workaround is to locate Aperture 3.6 on another Mac, and AirDrop it to your Mac.
