### ISSUE TITLE
Can't synchronise my iPod with retroactive

### ISSUE THREAD

**Issue by Michel50400** [cormiertyshawn895/Retroactive#62]
Hello, and first of all **thank you for your great work** 🥇
I use an iPod Classic that doesn't work quite well with Catalina and I would be glad to be able to keep using iTunes with Retroactive !

But I've try it a few times and I can't get to make it work... I think the problem is related to full disk access. Anyway, here's how I proceed :

- I've downloaded the last version of Retroactive (1.6), 
- I choose to Install iTunes and select iTunes 12.9.5 (but i've also tried with 12.6.5 unsuccessfully)
- I authenticate and wait during the download (and you're right, i spin up during the process)
- The extraction seems to do fine
- When it comes to configure iTunes, i get the "Enable full disc access" window which says "drag me", but i don't really know what to drag, so i drag both the iTunes app created in launchpad and the Retroactive apps that is in my Downloads folder. 
- When I drag the retroactive app, I get a message saying "retroactive won't get full access until it's closed"

![Capture d’écran 2020-03-23 à 12 23 01](https://user-images.githubusercontent.com/62540804/77312099-a17dea00-6d01-11ea-9761-7182443ca94d.png)

- But nothing seems to happen in retroactive. If I click again on "Enable full disk access" I see this window again, with both retroactive and iTunes checked 
![Capture d’écran 2020-03-23 à 12 22 32](https://user-images.githubusercontent.com/62540804/77312063-8c08c000-6d01-11ea-8d6f-474f00f8f194.png)

- At this point, if i try to close retroactive, a window tells me it's not possible and would corrupt my installation, so I click on "I don't need to sync an iPod" (which is false).

- Then iTunes opens with a message "iTunes can't read this iPod, please restore it". If I try to restore it with iTunes, i get an error message "couldn't be restored - unknown error 1433" . So I restore it with Finder, and it works.

- Then I open iTunes, get the "already used" message,  kill AMPDeviceAgent, and I can display it on iTunes. **But, when I try to sync it with iTunes, I get a new error message "iPod can't be synced, error 54".**

I think it's because I didn't properly gave full access to iTunes, but I can't figure out what I've done wrong. I can see that user schulzs mentioned a solved similar problem [here](https://github.com/cormiertyshawn895/Retroactive/issues/38) but i'm not an native english speaker and I don't get what "enabling Full Disk Access for bash" means.

I'm a little bit desperate, and would be glad if you've an idea how to get it to work for me.
Thanks a lot,

**Comment by cormiertyshawn895** [comment]
You are dragging the wrong thing into Full Disk Access. 

Instead of dragging the Retroactive app or the iTunes app into the list, **drag the "Drag me into the list" bubble itself (screenshot) into the list**. Then you should be good to go.

![drag](https://user-images.githubusercontent.com/57056759/77473943-79f75200-6dd3-11ea-8bfd-311290ee950e.png)

**Comment by Michel50400** [comment]
Noooo way ! It was just that easy !  😀
Your answer solved my problem. 
Many thanks on you 🙏👍
