### ISSUE TITLE
The iPhone "iPhone" cannot be synced. There is not enough memory available

### ISSUE THREAD

**Issue by opq8** [cormiertyshawn895/Retroactive#63]
Hi folks, has anyone else run into a "not enough memory available" when trying to sync their iPhone (with iOS 13.4) using iTunes 12.9, with Retroactive 1.6 + Catalina 10.15.4?

I've tried the obvious:
* Restarting iTunes
* Restarting my Mac
* Deleting my iOS backup from iTunes

The iPhone sync'ed fine with the exact SW config via iTunes 12.9 on Mojave on the same PC just before upgrading to Catalina.

An older iOS device with a much smaller device backup and simpler sync (smaller music playlist, fewer photos) seems to sync fine.

![Screenshot](https://user-images.githubusercontent.com/57631672/77502058-fc553580-6e16-11ea-8b2c-dd4c7588787a.png)

Thanks!

**Edit:** I think I've narrowed it down to the Pictures I'm syncing.

I have 3 pictures folders checked (about 50 photos total), and if I uncheck those, the sync completes fine.

Unfortunately, deleting the iPod Photo Cache folder results iTunes complaining about files not found... and if I look in the Photos folder, a new "iPod Photo Cache" folder is generated but with a very small "Photo database" file and none of the "FXX" subfolders.. could something there be broken?

**Comment by JMardenslp** [comment]
I can confirm the workaround with photos - I had the same issue, and unchecking Sync Photos made it go away.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
