### ISSUE TITLE
iTunes 12.4.3 would be amazing

### ISSUE THREAD

**Issue by iamnotscavullo** [cormiertyshawn895/Retroactive#66]
Please, consider iTunes 12.4.3. This version is the best looking version and the last with custom color background  for albums and movies.
Best regards friend.

**Comment by ShikiSuen** [comment]
I have the same request, too.

**Comment by DimitarNestorov** [comment]
Duplicate: #21

**Comment by cormiertyshawn895** [comment]
Duplicate of #21
