### ISSUE TITLE
iTunes 12.6.5 

### ISSUE THREAD

**Issue by JuanPerezPerez1** [cormiertyshawn895/Retroactive#67]
iTunes 12.6.5 cannot download applications anymore. OS Catalina 10.15.4

**Comment by cormiertyshawn895** [comment]
In April 2020, Apple has rolled out a server-side change that prevents all Mac users from purchasing and downloading iOS apps with iTunes. 

- You can use [Apple Configurator 2](https://apps.apple.com/app/apple-configurator-2/id1037126344) to [download iOS apps on your Mac](https://www.youtube.com/watch?v=M_3t06FEhR0).
- You can continue to use [iTunes 12.6.5](https://support.apple.com/HT208079) to purchase and download iOS apps on a Windows PC.

The Retroactive app and its README have been updated to recommend using [Apple Configurator 2](https://apps.apple.com/app/apple-configurator-2/id1037126344) instead.

![configurator-hint](https://user-images.githubusercontent.com/57056759/78525190-492bfb00-778b-11ea-8301-ebac281a3d64.jpg)
