### ISSUE TITLE
iTunes 10.7 won't sync iPod touch

### ISSUE THREAD

**Issue by autli** [cormiertyshawn895/Retroactive#69]
Installed iTunes 10.7 on OS 10.15.4 with Retroactive 1.6. This works but I am not able to sync my iPod touch 7. Gen. iOS 13.4.
After connection the message shows up: "This iPod touch needs iTunes 12.5". But I would like to stay with 10.7 (mostly because of "redirected arrow store buttons to library" feature)
(Bash ist active in "Full Disk Access" and killall AMPDevicesAgent done)
Any additional steps I could try?

**Comment by cormiertyshawn895** [comment]
iTunes 10.7 only supports syncing iOS devices running iOS 6.1.6 or earlier, as well as iPod nano, iPod shuffle, and iPod classic.

Syncing with any iOS or iPadOS device running iOS 13.4 or later requires iTunes 12.9.5.
