### ISSUE TITLE
iTunes 12.6.5 backup error -42

### ISSUE THREAD

**Issue by ghost** [cormiertyshawn895/Retroactive#7]
Hi,

first of all thank you for the amazing app. I installed it on a test container under catalina. The installation worked just fine, but I have one issue with iTunes 12.6.5.

Whenever I try to backup my iPhone X (iOS 13.2) the backup failed with error code -42. That is not a big deal, because therefore I can use other ways. I was not able to find an information regarding that error code. Is there something you can do to fix that type of an issue? 

Thx in advance.

**Comment by walterdavis** [comment]
I think that Catalina moves the backup of iDevices into the Finder, so you may want to look there.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
