### ISSUE TITLE
Just want to say THANK YOU!!!

### ISSUE THREAD

**Issue by Andres-Brito** [cormiertyshawn895/Retroactive#70]
Dear friends:

I delayed update my Mac to Catalina because iTunes! I've been working in my huge music library for about 15 years and it was a pity to lose such a great treasure. Finaly, I found RETROACTIVE and this has been a big gladness for me because now I'm able not only to have iTunes back again, but also to have it with COVERFLOW, a "stravaganza" for my music collection also I missed so much!

![fetch](https://user-images.githubusercontent.com/63593743/79122670-3a97a200-7d90-11ea-88fe-74164fcfb10c.png)

You are great developers and I just want to say THANK YOU for this great effort!

**Comment by cormiertyshawn895** [comment]
This is awesome! ❤️
Thank you for the kind words and keep up your music collection.
