### ISSUE TITLE
iTunes does not startup after installation on macOS Catalina 10.15.4 (19E287)

### ISSUE THREAD

**Issue by pavelbaramov** [cormiertyshawn895/Retroactive#72]
Hi,

I just tried the Retroactive app on macOS Catalina 10.15.4 (19E287) and tried to install iTunes (regular and with the retro look) and it just does not start. Also the iTunes icon shows that is incompatible.
How can I give you more logs and debug info?

<img width="111" alt="Screenshot 2020-04-15 at 12 41 30" src="https://user-images.githubusercontent.com/13537609/79323098-7197c000-7f16-11ea-80cc-b3762c79dcb4.png">

**Comment by Andres-Brito** [comment]
This is weird, friend! I can run iTunes with macOS Catalina 10.15.4 (19E287) in a perfect way...

**Comment by cormiertyshawn895** [comment]
Could you please:
- Open Spotlight
- Search for "Terminal" and press the `return` key to open it
- Paste into Terminal `ls -R -lh /Applications/iTunes.app > ~/Desktop/log.txt`, and press `return`
- Locate `log.txt` on your Desktop, drag it into the comment box on this page, then post `log.txt` as an attachment?

**Comment by Jeeosch** [comment]
I have the exact same issue!
Log is attached.

Please help!
1000 THX!

[log.txt](https://github.com/cormiertyshawn895/Retroactive/files/4514438/log.txt)

**Comment by Jeeosch** [comment]
Strange enough, but after a restart all is back to normal ...

**Comment by slavanossar** [comment]
I also had this issue, on closer inspection the Dock icon was trying to open `/Applications/iTunes.app/iTunes.app` for some reason.

Dragging the app out of the dock to remove it and then opening the app through Finder fixed it, and it could be added to the Dock again.

**Comment by Andres-Brito** [comment]
This is the proof iTunes runs in Catalina and iPod sync works perfectly.

<img width="2048" alt="Captura de pantalla 2020-04-24 a las 10 41 19" src="https://user-images.githubusercontent.com/63593743/80199429-35044c80-8619-11ea-8268-026c46fbbcb4.png">

**Comment by pavelbaramov** [comment]
@cormiertyshawn895 here it is

[log.txt](https://github.com/cormiertyshawn895/Retroactive/files/4528569/log.txt)

**Comment by pavelbaramov** [comment]
> This is the proof iTunes runs in Catalina and iPod sync works perfectly.
> 
> <img alt="Captura de pantalla 2020-04-24 a las 10 41 19" width="2000" src="https://user-images.githubusercontent.com/63593743/80199429-35044c80-8619-11ea-8268-026c46fbbcb4.png">

@Andres-Brito 
Which version of Catalina do you have?

**Comment by pavelbaramov** [comment]
With the new update of **Retroactive Version 1.6 (52)** iTunes works for me.
