### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by berrald** [cormiertyshawn895/Retroactive#73]
I can use Aperture again!
How can I make a donation to thank you?

**Comment by paul-hand** [comment]
+1 for that. Absolutely thrilled and looking to send a donation ...

Cheers

**Comment by cormiertyshawn895** [comment]
Duplicate of #20 

Thank you for your generosity! ❤️

I am super happy to hear Retroactive is able to help you with your photography workflows. Currently, this project does not take any donations.
