### ISSUE TITLE
Aperture Import Skips Videos

### ISSUE THREAD

**Issue by parrotheadjb** [cormiertyshawn895/Retroactive#74]
I understand Aperture won't play videos in Catalina, which is fine. However, it also won't import them into the library. That's less ok. Using Import Folders as Projects, any videos inside will be skipped (using referenced library). If I try to drag the video into a project, it pops up a message saying 0 items were imported into the library, same as after Import Folders as Projects.

This is a big challenge to keeping the library going on Aperture. Ideas appreciated!

**Comment by andredmelo** [comment]
First of all thank you @cormiertyshawn895 for putting this amazing tool together!
I have a problem that I believe might be related to this post.
When importing from an iPhone I get a notice saying some files are not compatible, It asks me to choose a folder and all the video files (.mov) are put there and not processed (put into correct folder and renamed).
And the newly generated video files don't even show up in the Import window at all.
I just can't find an alternative software to download into a (generated by date) folder, rename (with great flexibility) and then effectively delete them from iPhone that does it so well as Aperture...

Thank you for all input!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
