### ISSUE TITLE
Is there a way to run multiple versions of iTunes with Retroactive?

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#75]
I quite miss some of the old features of the older iTunes, however I also like to have the newer version as well. Is it possible to run multiple versions of iTunes somehow via Retroactive while retaining preferences and different music libraries?

**Comment by cormiertyshawn895** [comment]
Once you have installed a version of iTunes using Retroactive, you can move `/Applications/iTunes.app` to a different folder (such as Documents, or Desktop). After that, you can install a different version of iTunes using Retroactive.

You need to create multiple libraries to work with multiple versions of iTunes. When switching between multiple iTunes versions, hold down the option key and choose a compatible library.
