### ISSUE TITLE
iPhone / iPad In Use notifications

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#76]
After installing the most recent Retroactive and reinstalling iTunes 12.9.5.5 I get constant notifications for my iPhone and iPad in Catalina (10.15.4):
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/12uyKQZw/Image%202020-04-28%20at%2012.03.45%20PM.png)

After leaving my system for several hours I have probably close to 100 notifications...

**Comment by cormiertyshawn895** [comment]
If you connect an Apple device to your Mac, and either see nothing in iTunes, or "The device is in use by another user on this computer":

- Disconnect the device from your Mac, but keep iTunes open.
- Click on the Spotlight icon (magnifying glass) on the menu bar.
- Type "Terminal" and press return to open the Terminal app.
- Enter killall AMPDevicesAgent in the Terminal window, and press return.
- Connect the Apple device back to your Mac.
