### ISSUE TITLE
catalina/latest retroactive/opens sometimes

### ISSUE THREAD

**Issue by yycwrangler** [cormiertyshawn895/Retroactive#77]
Hi Folks

For starters great app when it works..Thank you..Cat 10.15.4, latest iTunes download. Have 26 gb space. App downloads and then I go through the steps of linking the app to my computer. One thing that seems to cause me problems is when I go to security and privacy, unlock the padlock it states drag app to security list..I have done that several times and it shows retroactive in my allow access list..each time I have checked it shows retroactive with a check mark. I shut the computer down and restart, plug in my iPhone 8 and sometime the iTunes retroactive icon shows up and for the most times it doesn't show up..Am I doing something wrong. Do I have to start Catalinas version of iTunes first..Would love to get this working properly as I love the app..Cheers Al

**Comment by cormiertyshawn895** [comment]
If you connect an Apple device to your Mac, and either see nothing in iTunes, or "The device is in use by another user on this computer":

- Disconnect the device from your Mac, but keep iTunes open.
- Click on the Spotlight icon (magnifying glass) on the menu bar.
- Type "Terminal" and press return to open the Terminal app.
- Enter killall AMPDevicesAgent in the Terminal window, and press return.
- Connect the Apple device back to your Mac.

**Comment by Neucleus** [comment]
This still isn't working for me. iPod is working, but I get the 'device used by another user' error when I connect iphone...and I can't drag songs in to it. I noticed that the iPhone doesn't show in Finder either
When I enter the 'killall AMPDevicesAgent' command, I get _No matching processes belonging to you were found_

**Comment by guofoo** [comment]
I'm having the same error message as above for my iPhone. The killall command also didn't work for me. But I used Activity Monitor to find the process and kill it manually and tried again. But the same error happens. I tried killing both AMP* processes also but same result.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
