### ISSUE TITLE
iTunes media keys not working (rewind, play/pause, fast forward/skip)

### ISSUE THREAD

**Issue by DaLuce2020** [cormiertyshawn895/Retroactive#79]
The keyboard buttons do not control iTunes in Catalina. They control the Music app instead.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
