### ISSUE TITLE
Other apps...

### ISSUE THREAD

**Issue by ylluminate** [cormiertyshawn895/Retroactive#8]
Appreciate your having pulled this together. Have you poked around with other apps such as [Levelator](http://www.conversationsnetwork.org/levelator)? This and other apps have been keeping me back from taking the scary plunge...

**Comment by cormiertyshawn895** [comment]
I looked at Levelator. It's a wxWidgets app with some 32-bit native libraries (`level`, `libsndfile.1.dylib`). 

Python parts of the app can be re-wrapped in a 64-bit wrapper, but the `level` native library can't. Without Levelator's source code, it will be very difficult to bring the app to macOS Catalina.

Luckily, Levelator is also available for Windows, which means you can use [the Windows version of Levelator](http://cdn.conversationsnetwork.org/LevelatorSetup-2.1.1.exe) with [CrossOver 19](https://www.codeweavers.com/products/crossover-mac), which continues to support 32-bit Windows apps on macOS Catalina.

You can also set up a macOS Mojave virtual machine on macOS Catalina, and [run Levelator there](https://appletoolbox.com/need-to-run-32-bit-apps-on-macos-catalina-use-a-mojave-virtual-machine/).

**Comment by Casuallynoted** [comment]
I’m curious if any of the games that used to be bundled with Mac, like Freeverse’s Big Bang Board Games, can be swiveled to work on Catalina.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
