### ISSUE TITLE
itunes - sync only checked songs and videos (greyed out)

### ISSUE THREAD

**Issue by thechillingadventures** [cormiertyshawn895/Retroactive#81]
I have the latest update installed 12.9.5.5. However, I've noticed that in iTunes, I cannot sync songs, only manually add songs. I've only just started to use Retroactive, so I'm not sure if this was always the case.
<img width="809" alt="Screen Shot 2020-05-01 at 8 10 03 PM" src="https://user-images.githubusercontent.com/64508853/80850059-fe659d80-8be7-11ea-9be9-596e639483e5.png">

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
