### ISSUE TITLE
Aperture: "random" quality on thumbnails

### ISSUE THREAD

**Issue by michaelherger** [cormiertyshawn895/Retroactive#82]
With my retro activated Aperture I get pretty random results for the thumbnail quality. Sometimes it's ok, as usual. Sometimes it shows really bad JPEG artefacts, like a highly compressed image. This can change within the same import from the same camera, pictures taken within seconds from each other. See below screenshot:

![Bildschirmfoto 2020-05-02 um 07 58 09](https://user-images.githubusercontent.com/2789989/80856489-c774a380-8c4a-11ea-89ec-66da0393e08d.png)

I tried various settings for the preview images. But the results seem to be pretty random, as can be seen by this example. Anybody seen this, too?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
