### ISSUE TITLE
Mojave Final Cut open issue

### ISSUE THREAD

**Issue by Shawn-Yeh** [cormiertyshawn895/Retroactive#83]
Thank you for sharing your program.
I installed Final Cut 7 on Mojave(2020 iMac 27) and unlock it. Retroactive shows successfully unlocked but when I launch Final Cut 7, it only jumps one time on the dock and does nothing else. The Final Cut won't open. Is there anything I can try to make it work? Thank you.

**Comment by cormiertyshawn895** [comment]
If you have installed plug-ins for Final Cut Pro 7, remove the plug-ins, then launch Final Cut Pro 7 again.

If Final Cut Pro 7 continues to crash, please send me the crash report to troubleshoot:
- Search for "Console" in Spotlight, and launch Console
- Click on "System Reports" in the sidebar
- Find the most recent crash report that starts with "Final Cut Pro", right click on it, and "Reveal in Finder"
- Attach the crash report by dragging it into the comment field on this Github issue page, or email the crash report to cormiertyshawn895@gmail.com

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
