### ISSUE TITLE
App request: Front Row

### ISSUE THREAD

**Issue by dillonjohnbrown** [cormiertyshawn895/Retroactive#84]
Can Front Row be made to work with Retroactive? It is the one app I miss from the Snow Leopard days.

Thank you for all the hard work it must have taken to get this software working!

**Comment by Casuallynoted** [comment]
Would love to see Front Row as well!

**Comment by cormiertyshawn895** [comment]
Front Row requires the QuickTime framework, which has been removed from macOS Catalina. However, it may be possible to add support for running Front Row on macOS Mojave. It is also possible (but very time consuming) to re-implement Front Row using modern technologies, and make sure its appearance match the original Front Row app.

[Kodi](https://kodi.tv) is a free alternative to Front Row, and is compatible with all modern versions of macOS.
