### ISSUE TITLE
can't sync my iphoto library and iPhone with Itunes

### ISSUE THREAD

**Issue by Tetonne** [cormiertyshawn895/Retroactive#85]
Hello and thanks for this great software :-)
i'm using it on catalina 10.15.4 and it works great even if i have 2 problems :
first one i can not sync my iphoto library and iPhone with Itunes.
iTunes 12.9.5 can't détect my iphoto library, so i can not have my sélected photos on my iPhone :-(
i read thing on internet that i must create a n other library :(
and that iPhoto Library Manager can help... (i use it in the past on mojave and before...

this app say : The merge could not be started because it cannot be performed with the installed version of iPhoto ((null)) if i want to merge.

and if i want o merge withe existing : The library “empty” cannot be used as the destination for the merge because its version (9.6.1) is not the same as the installed version of iPhoto ((null)).

so may be the issue is due to the fact that iPhoto as been modified, 
what can i do to make OS believe it the genuine iphoto apps?

do you plan to make new apps working with catalina?
iDVD.app iMovie 9.app?

best regards

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
