### ISSUE TITLE
iTunes and iPhoto option unavailable

### ISSUE THREAD

**Issue by pasoxfan** [cormiertyshawn895/Retroactive#86]
Hello, I downloaded retroactive and it opened fine but when I went to launch it, the options for iTunes and iPhoto were shaded out.  Not sure why?  i'm running Mohave. Do I have to install Catalina first for this to work? I get the notification for apple, however, that iPhoto and iTunes will be uninstalled.

Thanks!

**Comment by dowsmith** [comment]
I have a similar problem: I'm running Mojave, and want to unlock/fix iTunes.
However,  Aperture, iPhoto and iTunes are all greyed out.

**Comment by LightmoonXD** [comment]
i checked the introduction page of this app and found macos mojave can not support this function now.i hope the developer can add it soon.XD

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
