### ISSUE TITLE
Retroactive is unlocking iTunes:  Hanging

### ISSUE THREAD

**Issue by btcaffar** [cormiertyshawn895/Retroactive#88]
I try to close retroactive, and I keep getting this message:

"Retroactive is unlocking iTunes.  Quitting Retroactive will result in a corrupted copy of iTunes."\

How long should this take?  Thanks for you help.

**Comment by thechillingadventures** [comment]
I'm having the same issue after trying to update.

**Comment by cormiertyshawn895** [comment]
Can you try to force quit Retroactive, then unlock iTunes again?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
