### ISSUE TITLE
Clarifying support on FCP7 with Catalina

### ISSUE THREAD

**Issue by free-hongkong** [cormiertyshawn895/Retroactive#89]
Does it mean Retroactive only support Macs older than "late-2019" on Catalina?
It will not work on a 2020 Mac with Catalina?

**Comment by cormiertyshawn895** [comment]
Retroactive supports unlocking Final Cut Pro 7 on macOS Mojave and macOS High Sierra. 

If your Mac is running macOS Catalina, but is released before Late 2019, you can install macOS Mojave on a secondary APFS volume, install Final Cut Pro 7 on macOS Mojave, then use Retroactive to unlock Final Cut Pro 7.

If your Mac is running macOS Catalina and is released after Late 2019, you can not use Final Cut Pro 7.

To check when your Mac is released, click on the Apple logo, and choose "About this Mac".
