### ISSUE TITLE
Learn what to do if your RAW photos show up as “Unsupported Image Format”

### ISSUE THREAD

**Issue by AlainAvon** [cormiertyshawn895/Retroactive#9]
In Aperture, if your RAW photos show up as “*Unsupported Image Format*”, open the “*Photos*” menu, click on “*Reprocess original…*”, and reprocess all photos. 

![](https://raw.githubusercontent.com/cormiertyshawn895/Retroactive/master/screenshots/reprocess.jpg)

After reprocessing your RAW photos, you will be able to preview and adjust them as before. 

_💡 Tip: 
If some RAW photos still show up as "*Unsupported Image Format*" after reprocessing, repeat the process above to reprocess all photos again. In other words, you may need to reprocess all photos twice._

**Comment by AlainAvon** [comment]
Original issue by AlainAvon:

Hi, 
I just created a new Catalina session on my iMac. Then i copied a Aperture App from a Mojave session and applied Retroactive on it.  Like magic Aperture then started from Catalina !
Unfortunately when i tried to open RAW files (Canon 5D) , an error message appeared , something like "Aperture can't open this kind of file"
Have you any idea to fix this ?
Hope my english makes sense . I'm french.
Thanks for your help.
Alain
Cannes / France

<img width="956" alt="Capture d’écran 2019-10-30 à 19 05 02" src="https://user-images.githubusercontent.com/57185126/67886414-afac4d80-fb49-11e9-99d9-0f98d2dcab2a.png">
Here is the error message (in French sorry) ...

Note that there is no problem with jpg files. Only RAW files

**Comment by cormiertyshawn895** [comment]
I can open RAW files from EOS 5D, 5D Mark 2, 5D Mark 3, and 5DS in Aperture. Can you attach the RAW file that can't be opened by Aperture?

**Comment by eralbru** [comment]
Same issue here. I have uploaded CR2 file to Dropbox because it's too large for attaching it here.
https://www.dropbox.com/s/28ubyfsrc7m6h25/IMG_0062.CR2?dl=0

**Comment by AlainAvon** [comment]
I don't know if it will hep but i made several tests:
#1 : I exported on the desktop a RAW file that Aperture can't open. Other applications or finder can open it.
#2 : I imported in Aperture a RAW file (from the same Canon 5DII camera)  ... and this time Aperture can read it !
#3 : I made the same tests with another Aperture library and same issues can be reported

**Comment by cormiertyshawn895** [comment]
I can successfully import the CR2 file @eralbru uploaded. This looks like a permission issue for me.

Try these:
- Directly drag the RAW file from Finder into Aperture. Does this work?
- When you opened the Import panel for the first time, did Aperture ask you "Aperture would like to access files in your Desktop folder"?
<img width="532" alt="Screen Shot 2019-10-31 at 7 14 02 PM" src="https://user-images.githubusercontent.com/57056759/67997848-2d885b80-fc13-11e9-999e-c70649120ee6.png">

- Check System Preferences > Security & Privacy > Aperture. Are "Desktop Folder" and "Documents Folder" checked? If they are not checked, check them.
<img width="780" alt="Screen Shot 2019-10-31 at 7 15 11 PM" src="https://user-images.githubusercontent.com/57056759/67997856-3416d300-fc13-11e9-8bc7-ae1f038310d6.png">

- Add Aperture to System Preferences > Security & Privacy > Full Disk Access.

**Comment by AlainAvon** [comment]
Thanks for your reply

#1 _"Directly drag the RAW file from Finder into Aperture. Does this work?"_
Yes . I can drag and drop a RAW file on Aperture and watch it normally 

#2 _"When you opened the Import panel for the first time, did Aperture ask you "Aperture would like to access files in your Desktop folder"?"_
No. 

#3 and #4. _"Check System Preferences > Security & Privacy > Aperture. Are "Desktop Folder" and "Documents Folder" checked? If they are not checked, check them."
"Add Aperture to System Preferences > Security & Privacy > Full Disk Access."_
I added Aperture in "Full disk Access"  
but "Full disk access" (not "Desktop Folder" and "Documents Folder")  is now mentioned in "Files and folders"

Unfortunately nothing new after that. I can't watch RAW files anymore...

**Comment by superfancy8** [comment]
(Watching this conversation before updating to Catalina...)

**Comment by gbooker** [comment]
To add another bit of oddness to the mix:

- My experiences are similar to @AlainAvon's reply above
- A direct sync of the aperture library to a machine running Mojave (using rsync, permissions are preserved) and the raw files are all readable by aperture there
  - I checked the permissions on these files; there is nothing special about them
- Aperture on Catalina can read the newer raw files but not the older ones (Dec of 2014 is the oldest I can read them)
  - These raw files all came from the same camera
- If I tell Aperture on Catalina to use the JPEG file as the original, it has no issue displaying the preview.  The JPEG and CR2 are in the same directory and have the same permissions.

**Comment by Tiggmeister** [comment]
I've had the same issue. I then reprocessed the files from original as a new version and they all showed up. But the previous adjustments weren't preserved.

**Comment by Tiggmeister** [comment]
I'd make a backup copy of the Aperture Catalog first and use that for the Catalina version. I tried looking at my catalog from Catalina and then back at the same catalog in Mojave and it crashed and needed rebuilding.

**Comment by cormiertyshawn895** [comment]
@gbooker Can you zip up a library containing RAW files that can't be read by Aperture on macOS Catalina, and share it with me through Dropbox, WeTransfer, Google Drive, or email (cormiertyshawn895@gmail.com)?

**Comment by cormiertyshawn895** [comment]
There is an easy solution. In Aperture, choose Photos > Reprocess Original... > Reprocess Photos. After reprocessing your RAW photos, you will be able to preview and adjust them as before in Aperture. 

![reprocess-photos](https://user-images.githubusercontent.com/57056759/68523926-7627c080-0274-11ea-8729-4f641a8377da.jpg)

---

This problem only occurs if you have originally imported RAW images using Aperture 3.4.5 or below under an older version of macOS. 

If you try to adjust one of these RAW photos that were imported in Aperture 3.4.5 on macOS Mojave, Aperture will mention "This photo was adjusted using an earlier version of Apple's RAW processing", but the photo is displayed properly.

If you try to preview or adjust one of these RAW photos on macOS Catalina without reprocessing them first, Aperture will not preview the photo, and alert you with "Unsupported Image Format".

![old-raw-processing](https://user-images.githubusercontent.com/57056759/68523735-192b0b00-0272-11ea-9d9a-e2cc296538aa.jpeg)

**Comment by cormiertyshawn895** [comment]
There is an easy solution.

In Aperture, choose Photos > Reprocess Original... > Reprocess Photos.
![reprocess-photos](https://user-images.githubusercontent.com/57056759/68523926-7627c080-0274-11ea-8729-4f641a8377da.jpg)

After reprocessing your RAW photos, you will be able to preview and adjust them as before in Aperture.

**Comment by AlainAvon** [comment]
@cormiertyshawn895 
Many thanks ! 
Seems to be working. But I have had to do 'Reprocess photos" two times. After the first process some photos could be watched and some other not (even if there were from the same project and same day)...
{EDIT}  I tried with another Aperture library and I also have had to do  'Reprocess photos" two times...

**Comment by eralbru** [comment]
I can confirm this solution is also working for me.

Thank you so much!

/Ralf

Von: Tyshawn Cormier <notifications@github.com>
Antworten an: cormiertyshawn895/Retroactive <reply@reply.github.com>
Datum: Samstag, 9. November 2019 um 07:11
An: cormiertyshawn895/Retroactive <Retroactive@noreply.github.com>
Cc: Ralf Brunckhorst <ralf.brunckhorst@ericsson.com>, Mention <mention@noreply.github.com>
Betreff: Re: [cormiertyshawn895/Retroactive] Aperture don't read RAW files (#9)


There is an easy solution.

In Aperture, choose Photos > Reprocess Original... > Reprocess Photos.
[Das Bild wurde vom Absender entfernt. reprocess-photos]<https://protect2.fireeye.com/v1/url?k=5bcd06df-0747d3da-5bcd4644-861010bc36ff-7a945fa070d6683e&q=1&e=1e3b05c3-4276-4c5b-b0bc-88b906039f24&u=https%3A%2F%2Fuser-images.githubusercontent.com%2F57056759%2F68523926-7627c080-0274-11ea-8729-4f641a8377da.jpg>

After reprocessing your RAW photos, you will be able to preview and adjust them as before in Aperture.

**Comment by gbooker** [comment]
> Seems to be working. But I have had to do 'Reprocess photos" two times. After the first process some photos could be watched and some other not (even if there were from the same project and same day)...

> The first time it told me `x images were reprocessed.  x images are unsupported` (which `x` is the number I had selected).  Additionally some previews were removed.  Run it again and it just said `x images were reprocessed.` and they all showed up again.

I have updated the issue description and README to describe the need to reprocess all photos twice. Thank you for sharing your findings! ❤️

**Comment by phrank303** [comment]
I have the same issue on MacOS 13 on a MacBook Pro 14 M1. 
To Reprocess the images doesn't help. For me it looks liken Aperture (unboxed) can't access Apple’s RAW profiles…

**Comment by jwr** [comment]
Unfortunately, no amount of reprocessing makes CR2 files work in Aperture again. The previews appear for a couple of seconds, and then are replaced with "Unsupported image format".

**Comment by don-911** [comment]
I have the same issue for my NEF files. When I open a library for the first time, the thumbnails are there, but when I click on a photo, it shows the photo for a split second, and then changes to "Unsupported image format". If I re-process the images, the thumbnail comes back for a short while, and then disappears again after clicking on them. And sometimes aperture crashes. I'm using an M to Mac running 13.6.2, and I have given Aperture Full Disk Access.

**Comment by phrank303** [comment]
Has anything improved in the meantime? 
I've just made a test, intalled Retroactive again under Mac OS 14, but it seems like Aperture can't read RAW files anymore. JPEGs can be displayed, but any new or old RAW files will displayed as "Unsupported image format". Reprocess doesn't work either. Aperture is not showing up in "Files and Folders" Privacy & Security settings.

Thanks Apple.
