### ISSUE TITLE
iTunes no longer reading contents of iPod

### ISSUE THREAD

**Issue by Two-For-Mirth** [cormiertyshawn895/Retroactive#91]
This was working like a dream a week ago, but when I tried to plug in / manually manage my iPod today, I got this error message:

iTunes cannot read the contents of the iPod. Go to the Summary tab in iPod preferences and click Restore to restore this iPod to factory settings.

I haven't done any major software updates, so I am not sure why I am suddenly getting this message after everything was working so well for more than a month.

**Comment by b0gdanw** [comment]
Try to install these updates
`http://swcdn.apple.com/content/downloads/52/53/001-05974-A_IZY89AAHPZ/4h6g5p8myvkxiyr2a3ei2lwyetrfxhpuqb/CoreTypes.pkg
http://swcdn.apple.com/content/downloads/52/53/001-05974-A_IZY89AAHPZ/4h6g5p8myvkxiyr2a3ei2lwyetrfxhpuqb/MobileDeviceSU2.pkg`

**Comment by Two-For-Mirth** [comment]
Thank you so much for the suggestion. I installed these and restarted, but unfortunately I'm still having the same problem. I've tried de-installing my anti-virus software, as I read that might be causing the issue, and I've tried a different cord to connect with the same results, though I haven't been able to test the device on another computer. Any other suggestions most appreciated!

**Comment by b0gdanw** [comment]
Other suggestions, try to install iTunesAccess
`http://swcdn.apple.com/content/downloads/18/35/041-88780-A_GJANMA4WUP/xb3d8yo46hniuyttg61e1ozp4xcmuhufh5/iTunesAccess.pkg`
and give iTunes Full Disk Access.

**Comment by Two-For-Mirth** [comment]
Thank you again for your kind suggestion! I had been trying to figure out how to give iTunes full disk access on my own, but didn't know how to go about it. Unfortunately, I tried this and got the error: "This package is incompatible with this version of macOS." Oh dear.

**Comment by cormiertyshawn895** [comment]
Can you try these steps?
- Open Retroactive again.
- Choose to install iTunes, and choose the version of iTunes you have already installed.
- Retroactive should ask you to enable Full Disk Access. Follow the instructions on screen to provide Full Disk Access.
![7a](https://user-images.githubusercontent.com/57056759/85916169-dd45b580-b802-11ea-87bc-8465f2d20269.jpg)

**Comment by Two-For-Mirth** [comment]
That did the trick! Thank you so, so much. This really makes my day!

**Comment by zzzuppp** [comment]
cormiertyshawn895 - I also have iPod recognition problems. Tried all three versions of iTunes, but the newer ones both said 'can't read this iPod' (it's a Classic, and it reads on my old - High Sierra - Mac in iTunes 12.8.2.3) and it didn't show up on the oldest one at all when connected. So I redownloaded the newest version, and tried the tips above. Two of the pkgs opened and installed, but the iTunes access one says 'This package is incompatible with this version of OS' - 10.15.5 in my case, and won't install. So I tried reinstalling the same version of iTunes once more, as in your last tip above, but I didn't get the 'One more thing' screenshot above...don't know why not. It's driving me insane - I have over 10,000 music files on the Classic which I need for my work.
Any more tips? Thanks in advance

**Comment by fabulousrice** [comment]
My 12.9.5 install of iTunes is also unable to read my iPod nano. What is the name of the security preference pane that needs to be authorized in the "Turn on Full Access" list? I'm not sure I see it there and I'm not sure it's checked.
