### ISSUE TITLE
Weird beahviour of iTunes

### ISSUE THREAD

**Issue by Andres-Brito** [cormiertyshawn895/Retroactive#92]
It has happened twice this week: the music is working and, suddenly, iTunes repeats the few last second of the song and adds those few last seconds at the end of the mp3 file.

Anyone else?

**Comment by cormiertyshawn895** [comment]
This is very strange. Does this also happen if you play the same music file in macOS Catalina's built-in Music app?

**Comment by Andres-Brito** [comment]
Thank you for your question. No it doesn't. And it only happens when iTunes crash sometimes.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
