### ISSUE TITLE
Mojave FCP 7.0.3 crash on splash screen

### ISSUE THREAD

**Issue by tilltill77** [cormiertyshawn895/Retroactive#93]
Hi, thanks for this great program! Unfortunately FCP refuses to start here.
I installed it from my DVD, Retroactive successfully updated to 7.0.3, FCP shows the splash screen, tells that it loads the effects, then the splash without additional information, and then it crashes/quits, leaving the Finder and the Retroactive window.
I use OS X 10.14.6 on a MacBook pro late 2019, rebooted, re-installed FCP again and went to the Retroactive process a second time, did a shift-log-in without extensions. Same behaviour.
Does FCP somehow need Qmaster? Could't install it without but of course Qmaster is grey.
Please let me know if you have any ideas what to try.
And thanks again.

**Comment by cormiertyshawn895** [comment]
If you have installed plug-ins for Final Cut Pro 7, remove the plug-ins, then launch Final Cut Pro 7 again.

If Final Cut Pro 7 continues to crash, please send me the crash report to troubleshoot:
- Search for "Console" in Spotlight, and launch Console
- Click on "System Reports" in the sidebar
- Find the most recent crash report that starts with "Final Cut Pro", right click on it, and "Reveal in Finder"
- Attach the crash report by dragging it into the comment field on this Github issue page, or email the crash report to cormiertyshawn895@gmail.com

**Comment by tilltill77** [comment]
Hi thanks for your answer! There are no plug-ins and there ist no crash report for Final Cut Pro. Instead there is an always growing number of qmasterd crashes. I attached one. Hope this helps.
[qmasterd_2020-06-29-203339_none-and-grey-2.txt](https://github.com/cormiertyshawn895/Retroactive/files/4847403/qmasterd_2020-06-29-203339_none-and-grey-2.txt)

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
