### ISSUE TITLE
Doesn't work on new MacBook 13.3 2020 with 10th Gen

### ISSUE THREAD

**Issue by benmullyuk** [cormiertyshawn895/Retroactive#95]
Worked fine on my 2017 MacBook, but now following the install goes through all the steps, and when finished the iTunes logo has a no entry sign and if you try to open it says "You can't open the application iTunes because it is not supported on this type of Mac."

Any ideas???

<img width="897" alt="Screenshot 2020-05-27 at 16 56 26" src="https://user-images.githubusercontent.com/66026113/83044277-e264e880-a03b-11ea-9348-a59d87ef499e.png">

**Comment by benmullyuk** [comment]
Just checked some other entries and I'm running Catalina 10.15.4 (19E2269) and also did a log file. Any help greatly appreciated!!
[log.txt](https://github.com/cormiertyshawn895/Retroactive/files/4690267/log.txt)

**Comment by benmullyuk** [comment]
Just done a complete clean install of Catalina 10.15.5 (19F96) with new log file. Still doesn't work :-( Just seems to skip step 3 on the installer and go straight to iPod support.

**Comment by benmullyuk** [comment]
Just done a complete clean install of Catalina 10.15.5 (19F96) and Retroactive was 1st thing I ran, errors still, here's with new log file. Still doesn't work :-( Just seems to skip step 3 on the installer and go straight to iPod support.
[log.txt](https://github.com/cormiertyshawn895/Retroactive/files/4691843/log.txt)

**Comment by cormiertyshawn895** [comment]
Can you try this:
- Click on the Spotlight button on the top right corner of your display
- Search for "Terminal", then press return to open it
- Paste in `/Applications/iTunes.app/Contents/MacOS/iTunes`
- Press the return key

After following these steps, does iTunes open for you? If iTunes still doesn't open, can you select everything in Terminal (command+a), then paste it into the comment field?

**Comment by benmullyuk** [comment]
Just tried v1.8 and it works fine now thanks!
