### ISSUE TITLE
Media Won't Play on iPod Classic

### ISSUE THREAD

**Issue by Auch0909** [cormiertyshawn895/Retroactive#96]
Downloaded Retroactive, but all of the media I've put onto my iPod since downloading it (3 CDs and Podcasts) won't work when I try to play them on my iPod. In fact, it doesn't do anything and if I hold down the forward key, it just skips to the next track (which doesn't play either). The audio does work on the iTunes itself.

Thanks!

**Comment by cormiertyshawn895** [comment]
This is odd.
 
Can you try to sync some music to your iPod using the built-in Music app in macOS Catalina, and see if the music can be played? If the music plays, it's probably an iTunes problem. If the music doesn't play, it may be an issue with your audio file or iPod device.

**Comment by Auch0909** [comment]
I think I tried to load too much onto my iPod while iTunes was catching up and that only became clear a week or so later when I reloaded things.

**Comment by cormiertyshawn895** [comment]
Sweet!
