### ISSUE TITLE
Final Cut Pro 7 Does Not Run

### ISSUE THREAD

**Issue by WallFlyFilms** [cormiertyshawn895/Retroactive#97]
Hi,
I copied FCP 7 from an older computer, downloaded and ran retroactive, was told that I had successfully unlocked the program and that I could launch it. But--bummer--it didn't work! I am running Mojave 10.4.5

Any help? I am so looking forward to using FCP 7 again

**Comment by cormiertyshawn895** [comment]
If you have installed plug-ins for Final Cut Pro 7, remove the plug-ins, then launch Final Cut Pro 7 again.

If Final Cut Pro 7 continues to crash, please send me the crash report to troubleshoot:
- Search for "Console" in Spotlight, and launch Console
- Click on "System Reports" in the sidebar
- Find the most recent crash report that starts with "Final Cut Pro", right click on it, and "Reveal in Finder"
- Attach the crash report by dragging it into the comment field on this Github issue page, or email the crash report to cormiertyshawn895@gmail.com

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
