### ISSUE TITLE
Problem with iTunes

### ISSUE THREAD

**Issue by ekantrowitz** [cormiertyshawn895/Retroactive#98]
I'm on Catalina 10.15.5.  Ran retroactive 1.7 just for iTunes.  Proceed all the way.  When I get to Launch iTunes.  I get this error message

You have installed an older version of iTunes (11.4), which is not compatible with your current iTunes library (12.7.4).
Would you like to create a new iTunes library to use with iTunes 11.4?
Don't worry. Your existing iTunes library won't be deleted. Instead, it will be renamed.

I say create new library and wait for about 1 hr and nothing happens.  I close Retroactive and try to start iTunes and get
The application "iTunes" cannot be opened.

Any items what to do?

**Comment by cormiertyshawn895** [comment]
Can you try this:
- Click on the Spotlight button on the top right corner of your display
- Search for "Terminal", then press return to open it
- Paste in `/Applications/iTunes.app/Contents/MacOS/iTunes`
- Press the return key

After following these steps, does iTunes open for you? If iTunes still doesn't open, can you select everything in Terminal (command+a), then paste it into the comment field?

**Comment by ekantrowitz** [comment]
Thanks for the reply.   I saw that 1.8 was available. I downloaded it and that worked.  Thanks

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
