### ISSUE TITLE
iTunes does not recognize iPad, iPhone

### ISSUE THREAD

**Issue by Alex-1946** [cormiertyshawn895/Retroactive#99]
Thanks for a great App.

**Comment by Alex-1946** [comment]
The problem: iTunes will not recognize iphone/ipad. I followed your earlier recommendation and downloaded Retroactive again. Step One completed and went automatically to Step Two. Step Two complete but Step 3 was ignored and the new tab opened announcing that iTunes was available to open. However, iTunes still does not see the iphone/ipad. I repeated the entire process again with the same result. What am I missing?   MacBook Pro / Catalina15.5.  Thanks for the help.

**Comment by cormiertyshawn895** [comment]
Which version of iTunes did you choose to install from Retroactive?

Can you try these steps:
- Disconnect the device from your Mac, but keep iTunes open.
- Click on the Spotlight icon (magnifying glass) on the menu bar.
- Type "Terminal" and press return to open the Terminal app.
- Enter killall AMPDevicesAgent in the Terminal window, and press return.
- Connect the Apple device back to your Mac.

**Comment by benmullyuk** [comment]
I was having the same issue and the killall command worked for me. Thanks!!!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
